! Fortran support module for direct C wrappers
! Auto-generated by f90wrap

module f90wrap__issue258_derived_type_attributes_direct_support

    use dta_ct, only: dta_ct_t_inner => t_inner, dta_ct_t_outer => t_outer
    use dta_cc, only: dta_cc_t_inner => t_inner, dta_cc_t_outer => t_outer
    use dta_tt, only: dta_tt_t_inner => t_inner, dta_tt_t_outer => t_outer
    use dta_tc, only: dta_tc_t_inner => t_inner, dta_tc_t_outer => t_outer
    use iso_c_binding
    implicit none

contains

    subroutine dta_ct_f90wrap_t_inner__allocate(ptr) bind(C, name='__dta_ct_MOD_f90wrap_t_inner__allocate')
        type(c_ptr), intent(out) :: ptr
        type(dta_ct_t_inner), pointer :: fptr

        allocate(fptr)
        ptr = c_loc(fptr)
    end subroutine dta_ct_f90wrap_t_inner__allocate

    subroutine dta_ct_f90wrap_t_inner__deallocate(ptr) bind(C, name='__dta_ct_MOD_f90wrap_t_inner__deallocate')
        type(c_ptr), intent(inout) :: ptr
        type(dta_ct_t_inner), pointer :: fptr

        if (c_associated(ptr)) then
            call c_f_pointer(ptr, fptr)
            deallocate(fptr)
            ptr = c_null_ptr
        end if
    end subroutine dta_ct_f90wrap_t_inner__deallocate

    subroutine dta_ct_t_inner_initialise(self, this) bind(C, name='__dta_ct_MOD_t_inner_initialise')
        type(c_ptr), value :: self
        type(c_ptr), intent(out) :: this

        ! Default initialization (Fortran handles this automatically)
        ! Just return the same pointer
        this = self
    end subroutine dta_ct_t_inner_initialise

    subroutine dta_ct_t_inner_finalise(self, this) bind(C, name='__dta_ct_MOD_t_inner_finalise')
        type(c_ptr), value :: self
        type(c_ptr), intent(inout) :: this

        ! Default finalization (cleanup happens at deallocation)
        ! Return the same pointer
        this = self
    end subroutine dta_ct_t_inner_finalise

    subroutine dta_ct_f90wrap_t_inner__get__value(self_ptr, value) bind(C, name='__dta_ct_MOD_f90wrap_t_inner__get__value')
        type(c_ptr), value :: self_ptr
        integer , intent(out) :: value
        type(dta_ct_t_inner), pointer :: self

        call c_f_pointer(self_ptr, self)
        value = self%value
    end subroutine dta_ct_f90wrap_t_inner__get__value

    subroutine dta_ct_f90wrap_t_inner__set__value(self_ptr, value) bind(C, name='__dta_ct_MOD_f90wrap_t_inner__set__value')
        type(c_ptr), value :: self_ptr
        integer , intent(in) :: value
        type(dta_ct_t_inner), pointer :: self

        call c_f_pointer(self_ptr, self)
        self%value = value
    end subroutine dta_ct_f90wrap_t_inner__set__value

    subroutine dta_ct_f90wrap_t_outer__allocate(ptr) bind(C, name='__dta_ct_MOD_f90wrap_t_outer__allocate')
        type(c_ptr), intent(out) :: ptr
        type(dta_ct_t_outer), pointer :: fptr

        allocate(fptr)
        ptr = c_loc(fptr)
    end subroutine dta_ct_f90wrap_t_outer__allocate

    subroutine dta_ct_f90wrap_t_outer__deallocate(ptr) bind(C, name='__dta_ct_MOD_f90wrap_t_outer__deallocate')
        type(c_ptr), intent(inout) :: ptr
        type(dta_ct_t_outer), pointer :: fptr

        if (c_associated(ptr)) then
            call c_f_pointer(ptr, fptr)
            deallocate(fptr)
            ptr = c_null_ptr
        end if
    end subroutine dta_ct_f90wrap_t_outer__deallocate

    subroutine dta_ct_t_outer_initialise(self, this) bind(C, name='__dta_ct_MOD_t_outer_initialise')
        type(c_ptr), value :: self
        type(c_ptr), intent(out) :: this

        ! Default initialization (Fortran handles this automatically)
        ! Just return the same pointer
        this = self
    end subroutine dta_ct_t_outer_initialise

    subroutine dta_ct_t_outer_finalise(self, this) bind(C, name='__dta_ct_MOD_t_outer_finalise')
        type(c_ptr), value :: self
        type(c_ptr), intent(inout) :: this

        ! Default finalization (cleanup happens at deallocation)
        ! Return the same pointer
        this = self
    end subroutine dta_ct_t_outer_finalise

    subroutine dta_ct_f90wrap_t_outer__get__value(self_ptr, value) bind(C, name='__dta_ct_MOD_f90wrap_t_outer__get__value')
        type(c_ptr), value :: self_ptr
        integer , intent(out) :: value
        type(dta_ct_t_outer), pointer :: self

        call c_f_pointer(self_ptr, self)
        value = self%value
    end subroutine dta_ct_f90wrap_t_outer__get__value

    subroutine dta_ct_f90wrap_t_outer__set__value(self_ptr, value) bind(C, name='__dta_ct_MOD_f90wrap_t_outer__set__value')
        type(c_ptr), value :: self_ptr
        integer , intent(in) :: value
        type(dta_ct_t_outer), pointer :: self

        call c_f_pointer(self_ptr, self)
        self%value = value
    end subroutine dta_ct_f90wrap_t_outer__set__value

    subroutine dta_cc_f90wrap_t_inner__allocate(ptr) bind(C, name='__dta_cc_MOD_f90wrap_t_inner__allocate')
        type(c_ptr), intent(out) :: ptr
        type(dta_cc_t_inner), pointer :: fptr

        allocate(fptr)
        ptr = c_loc(fptr)
    end subroutine dta_cc_f90wrap_t_inner__allocate

    subroutine dta_cc_f90wrap_t_inner__deallocate(ptr) bind(C, name='__dta_cc_MOD_f90wrap_t_inner__deallocate')
        type(c_ptr), intent(inout) :: ptr
        type(dta_cc_t_inner), pointer :: fptr

        if (c_associated(ptr)) then
            call c_f_pointer(ptr, fptr)
            deallocate(fptr)
            ptr = c_null_ptr
        end if
    end subroutine dta_cc_f90wrap_t_inner__deallocate

    subroutine dta_cc_t_inner_initialise(self, this) bind(C, name='__dta_cc_MOD_t_inner_initialise')
        type(c_ptr), value :: self
        type(c_ptr), intent(out) :: this

        ! Default initialization (Fortran handles this automatically)
        ! Just return the same pointer
        this = self
    end subroutine dta_cc_t_inner_initialise

    subroutine dta_cc_t_inner_finalise(self, this) bind(C, name='__dta_cc_MOD_t_inner_finalise')
        type(c_ptr), value :: self
        type(c_ptr), intent(inout) :: this

        ! Default finalization (cleanup happens at deallocation)
        ! Return the same pointer
        this = self
    end subroutine dta_cc_t_inner_finalise

    subroutine dta_cc_f90wrap_t_inner__get__value(self_ptr, value) bind(C, name='__dta_cc_MOD_f90wrap_t_inner__get__value')
        type(c_ptr), value :: self_ptr
        integer , intent(out) :: value
        type(dta_cc_t_inner), pointer :: self

        call c_f_pointer(self_ptr, self)
        value = self%value
    end subroutine dta_cc_f90wrap_t_inner__get__value

    subroutine dta_cc_f90wrap_t_inner__set__value(self_ptr, value) bind(C, name='__dta_cc_MOD_f90wrap_t_inner__set__value')
        type(c_ptr), value :: self_ptr
        integer , intent(in) :: value
        type(dta_cc_t_inner), pointer :: self

        call c_f_pointer(self_ptr, self)
        self%value = value
    end subroutine dta_cc_f90wrap_t_inner__set__value

    subroutine dta_cc_f90wrap_t_outer__allocate(ptr) bind(C, name='__dta_cc_MOD_f90wrap_t_outer__allocate')
        type(c_ptr), intent(out) :: ptr
        type(dta_cc_t_outer), pointer :: fptr

        allocate(fptr)
        ptr = c_loc(fptr)
    end subroutine dta_cc_f90wrap_t_outer__allocate

    subroutine dta_cc_f90wrap_t_outer__deallocate(ptr) bind(C, name='__dta_cc_MOD_f90wrap_t_outer__deallocate')
        type(c_ptr), intent(inout) :: ptr
        type(dta_cc_t_outer), pointer :: fptr

        if (c_associated(ptr)) then
            call c_f_pointer(ptr, fptr)
            deallocate(fptr)
            ptr = c_null_ptr
        end if
    end subroutine dta_cc_f90wrap_t_outer__deallocate

    subroutine dta_cc_t_outer_initialise(self, this) bind(C, name='__dta_cc_MOD_t_outer_initialise')
        type(c_ptr), value :: self
        type(c_ptr), intent(out) :: this

        ! Default initialization (Fortran handles this automatically)
        ! Just return the same pointer
        this = self
    end subroutine dta_cc_t_outer_initialise

    subroutine dta_cc_t_outer_finalise(self, this) bind(C, name='__dta_cc_MOD_t_outer_finalise')
        type(c_ptr), value :: self
        type(c_ptr), intent(inout) :: this

        ! Default finalization (cleanup happens at deallocation)
        ! Return the same pointer
        this = self
    end subroutine dta_cc_t_outer_finalise

    subroutine dta_cc_f90wrap_t_outer__get__value(self_ptr, value) bind(C, name='__dta_cc_MOD_f90wrap_t_outer__get__value')
        type(c_ptr), value :: self_ptr
        integer , intent(out) :: value
        type(dta_cc_t_outer), pointer :: self

        call c_f_pointer(self_ptr, self)
        value = self%value
    end subroutine dta_cc_f90wrap_t_outer__get__value

    subroutine dta_cc_f90wrap_t_outer__set__value(self_ptr, value) bind(C, name='__dta_cc_MOD_f90wrap_t_outer__set__value')
        type(c_ptr), value :: self_ptr
        integer , intent(in) :: value
        type(dta_cc_t_outer), pointer :: self

        call c_f_pointer(self_ptr, self)
        self%value = value
    end subroutine dta_cc_f90wrap_t_outer__set__value

    subroutine dta_tt_f90wrap_t_inner__allocate(ptr) bind(C, name='__dta_tt_MOD_f90wrap_t_inner__allocate')
        type(c_ptr), intent(out) :: ptr
        type(dta_tt_t_inner), pointer :: fptr

        allocate(fptr)
        ptr = c_loc(fptr)
    end subroutine dta_tt_f90wrap_t_inner__allocate

    subroutine dta_tt_f90wrap_t_inner__deallocate(ptr) bind(C, name='__dta_tt_MOD_f90wrap_t_inner__deallocate')
        type(c_ptr), intent(inout) :: ptr
        type(dta_tt_t_inner), pointer :: fptr

        if (c_associated(ptr)) then
            call c_f_pointer(ptr, fptr)
            deallocate(fptr)
            ptr = c_null_ptr
        end if
    end subroutine dta_tt_f90wrap_t_inner__deallocate

    subroutine dta_tt_t_inner_initialise(self, this) bind(C, name='__dta_tt_MOD_t_inner_initialise')
        type(c_ptr), value :: self
        type(c_ptr), intent(out) :: this

        ! Default initialization (Fortran handles this automatically)
        ! Just return the same pointer
        this = self
    end subroutine dta_tt_t_inner_initialise

    subroutine dta_tt_t_inner_finalise(self, this) bind(C, name='__dta_tt_MOD_t_inner_finalise')
        type(c_ptr), value :: self
        type(c_ptr), intent(inout) :: this

        ! Default finalization (cleanup happens at deallocation)
        ! Return the same pointer
        this = self
    end subroutine dta_tt_t_inner_finalise

    subroutine dta_tt_f90wrap_t_inner__get__value(self_ptr, value) bind(C, name='__dta_tt_MOD_f90wrap_t_inner__get__value')
        type(c_ptr), value :: self_ptr
        integer , intent(out) :: value
        type(dta_tt_t_inner), pointer :: self

        call c_f_pointer(self_ptr, self)
        value = self%value
    end subroutine dta_tt_f90wrap_t_inner__get__value

    subroutine dta_tt_f90wrap_t_inner__set__value(self_ptr, value) bind(C, name='__dta_tt_MOD_f90wrap_t_inner__set__value')
        type(c_ptr), value :: self_ptr
        integer , intent(in) :: value
        type(dta_tt_t_inner), pointer :: self

        call c_f_pointer(self_ptr, self)
        self%value = value
    end subroutine dta_tt_f90wrap_t_inner__set__value

    subroutine dta_tt_f90wrap_t_outer__allocate(ptr) bind(C, name='__dta_tt_MOD_f90wrap_t_outer__allocate')
        type(c_ptr), intent(out) :: ptr
        type(dta_tt_t_outer), pointer :: fptr

        allocate(fptr)
        ptr = c_loc(fptr)
    end subroutine dta_tt_f90wrap_t_outer__allocate

    subroutine dta_tt_f90wrap_t_outer__deallocate(ptr) bind(C, name='__dta_tt_MOD_f90wrap_t_outer__deallocate')
        type(c_ptr), intent(inout) :: ptr
        type(dta_tt_t_outer), pointer :: fptr

        if (c_associated(ptr)) then
            call c_f_pointer(ptr, fptr)
            deallocate(fptr)
            ptr = c_null_ptr
        end if
    end subroutine dta_tt_f90wrap_t_outer__deallocate

    subroutine dta_tt_t_outer_initialise(self, this) bind(C, name='__dta_tt_MOD_t_outer_initialise')
        type(c_ptr), value :: self
        type(c_ptr), intent(out) :: this

        ! Default initialization (Fortran handles this automatically)
        ! Just return the same pointer
        this = self
    end subroutine dta_tt_t_outer_initialise

    subroutine dta_tt_t_outer_finalise(self, this) bind(C, name='__dta_tt_MOD_t_outer_finalise')
        type(c_ptr), value :: self
        type(c_ptr), intent(inout) :: this

        ! Default finalization (cleanup happens at deallocation)
        ! Return the same pointer
        this = self
    end subroutine dta_tt_t_outer_finalise

    subroutine dta_tt_f90wrap_t_outer__get__value(self_ptr, value) bind(C, name='__dta_tt_MOD_f90wrap_t_outer__get__value')
        type(c_ptr), value :: self_ptr
        integer , intent(out) :: value
        type(dta_tt_t_outer), pointer :: self

        call c_f_pointer(self_ptr, self)
        value = self%value
    end subroutine dta_tt_f90wrap_t_outer__get__value

    subroutine dta_tt_f90wrap_t_outer__set__value(self_ptr, value) bind(C, name='__dta_tt_MOD_f90wrap_t_outer__set__value')
        type(c_ptr), value :: self_ptr
        integer , intent(in) :: value
        type(dta_tt_t_outer), pointer :: self

        call c_f_pointer(self_ptr, self)
        self%value = value
    end subroutine dta_tt_f90wrap_t_outer__set__value

    subroutine dta_tc_f90wrap_t_inner__allocate(ptr) bind(C, name='__dta_tc_MOD_f90wrap_t_inner__allocate')
        type(c_ptr), intent(out) :: ptr
        type(dta_tc_t_inner), pointer :: fptr

        allocate(fptr)
        ptr = c_loc(fptr)
    end subroutine dta_tc_f90wrap_t_inner__allocate

    subroutine dta_tc_f90wrap_t_inner__deallocate(ptr) bind(C, name='__dta_tc_MOD_f90wrap_t_inner__deallocate')
        type(c_ptr), intent(inout) :: ptr
        type(dta_tc_t_inner), pointer :: fptr

        if (c_associated(ptr)) then
            call c_f_pointer(ptr, fptr)
            deallocate(fptr)
            ptr = c_null_ptr
        end if
    end subroutine dta_tc_f90wrap_t_inner__deallocate

    subroutine dta_tc_t_inner_initialise(self, this) bind(C, name='__dta_tc_MOD_t_inner_initialise')
        type(c_ptr), value :: self
        type(c_ptr), intent(out) :: this

        ! Default initialization (Fortran handles this automatically)
        ! Just return the same pointer
        this = self
    end subroutine dta_tc_t_inner_initialise

    subroutine dta_tc_t_inner_finalise(self, this) bind(C, name='__dta_tc_MOD_t_inner_finalise')
        type(c_ptr), value :: self
        type(c_ptr), intent(inout) :: this

        ! Default finalization (cleanup happens at deallocation)
        ! Return the same pointer
        this = self
    end subroutine dta_tc_t_inner_finalise

    subroutine dta_tc_f90wrap_t_inner__get__value(self_ptr, value) bind(C, name='__dta_tc_MOD_f90wrap_t_inner__get__value')
        type(c_ptr), value :: self_ptr
        integer , intent(out) :: value
        type(dta_tc_t_inner), pointer :: self

        call c_f_pointer(self_ptr, self)
        value = self%value
    end subroutine dta_tc_f90wrap_t_inner__get__value

    subroutine dta_tc_f90wrap_t_inner__set__value(self_ptr, value) bind(C, name='__dta_tc_MOD_f90wrap_t_inner__set__value')
        type(c_ptr), value :: self_ptr
        integer , intent(in) :: value
        type(dta_tc_t_inner), pointer :: self

        call c_f_pointer(self_ptr, self)
        self%value = value
    end subroutine dta_tc_f90wrap_t_inner__set__value

    subroutine dta_tc_f90wrap_t_outer__allocate(ptr) bind(C, name='__dta_tc_MOD_f90wrap_t_outer__allocate')
        type(c_ptr), intent(out) :: ptr
        type(dta_tc_t_outer), pointer :: fptr

        allocate(fptr)
        ptr = c_loc(fptr)
    end subroutine dta_tc_f90wrap_t_outer__allocate

    subroutine dta_tc_f90wrap_t_outer__deallocate(ptr) bind(C, name='__dta_tc_MOD_f90wrap_t_outer__deallocate')
        type(c_ptr), intent(inout) :: ptr
        type(dta_tc_t_outer), pointer :: fptr

        if (c_associated(ptr)) then
            call c_f_pointer(ptr, fptr)
            deallocate(fptr)
            ptr = c_null_ptr
        end if
    end subroutine dta_tc_f90wrap_t_outer__deallocate

    subroutine dta_tc_t_outer_initialise(self, this) bind(C, name='__dta_tc_MOD_t_outer_initialise')
        type(c_ptr), value :: self
        type(c_ptr), intent(out) :: this

        ! Default initialization (Fortran handles this automatically)
        ! Just return the same pointer
        this = self
    end subroutine dta_tc_t_outer_initialise

    subroutine dta_tc_t_outer_finalise(self, this) bind(C, name='__dta_tc_MOD_t_outer_finalise')
        type(c_ptr), value :: self
        type(c_ptr), intent(inout) :: this

        ! Default finalization (cleanup happens at deallocation)
        ! Return the same pointer
        this = self
    end subroutine dta_tc_t_outer_finalise

    subroutine dta_tc_f90wrap_t_outer__get__value(self_ptr, value) bind(C, name='__dta_tc_MOD_f90wrap_t_outer__get__value')
        type(c_ptr), value :: self_ptr
        integer , intent(out) :: value
        type(dta_tc_t_outer), pointer :: self

        call c_f_pointer(self_ptr, self)
        value = self%value
    end subroutine dta_tc_f90wrap_t_outer__get__value

    subroutine dta_tc_f90wrap_t_outer__set__value(self_ptr, value) bind(C, name='__dta_tc_MOD_f90wrap_t_outer__set__value')
        type(c_ptr), value :: self_ptr
        integer , intent(in) :: value
        type(dta_tc_t_outer), pointer :: self

        call c_f_pointer(self_ptr, self)
        self%value = value
    end subroutine dta_tc_f90wrap_t_outer__set__value

end module f90wrap__issue258_derived_type_attributes_direct_support
