/* File: _mymodulemodule.c
 * This file is auto-generated with f2py (version:2.3.3).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Tue Oct 21 20:18:59 2025
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
/*need_includes0*/


    /* custom abort handler - James Kermode <james.kermode@gmail.com> */
    #include <signal.h>
#include <setjmp.h>

    #define ABORT_BUFFER_SIZE 1024
    extern jmp_buf environment_buffer;
    extern char abort_message[ABORT_BUFFER_SIZE];
    void f90wrap_abort_(char *message, int len);
    void f90wrap_abort_int_handler(int signum);

    #include <stdlib.h>
    #include <string.h>

    jmp_buf environment_buffer;
    char abort_message[ABORT_BUFFER_SIZE];

    void f90wrap_abort_(char *message, int len_message)
    {
      strncpy(abort_message, message, ABORT_BUFFER_SIZE);
      abort_message[ABORT_BUFFER_SIZE-1] = '\0';
      longjmp(environment_buffer, 0);
    }

    // copy of f90wrap_abort_ with a second underscore
    // void (*f90wrap_abort__)(char *, int) = &f90wrap_abort_;
    void f90wrap_abort__(char *message, int len_message)
    {
      strncpy(abort_message, message, ABORT_BUFFER_SIZE);
      abort_message[ABORT_BUFFER_SIZE-1] = '\0';
      longjmp(environment_buffer, 0);
    }


    void f90wrap_abort_int_handler(int signum)
    {
      char message[] = "Interrupt occured";
      f90wrap_abort_(message, strlen(message));
    }

    /* end of custom abort handler  */
    
/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *_mymodule_error;
static PyObject *_mymodule_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/

#define PRINTPYOBJERR(obj)\
    fprintf(stderr,"_mymodule.error is related to ");\
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");


#define pyobj_from_double1(v) (PyFloat_FromDouble(v))

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/* See fortranobject.h for definitions. The macros here are provided for BC. */
#define rank f2py_rank
#define shape f2py_shape
#define fshape f2py_shape
#define len f2py_len
#define flen f2py_flen
#define slen f2py_slen
#define size f2py_size


#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif


#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/* New SciPy */
#define TRYPYARRAYTEMPLATECHAR case NPY_STRING: *(char *)(PyArray_DATA(arr))=*v; break;
#define TRYPYARRAYTEMPLATELONG case NPY_LONG: *(long *)(PyArray_DATA(arr))=*v; break;
#define TRYPYARRAYTEMPLATEOBJECT case NPY_OBJECT: PyArray_SETITEM(arr,PyArray_DATA(arr),pyobj_from_ ## ctype ## 1(*v)); break;

#define TRYPYARRAYTEMPLATE(ctype,typecode) \
        PyArrayObject *arr = NULL;\
        if (!obj) return -2;\
        if (!PyArray_Check(obj)) return -1;\
        if (!(arr=(PyArrayObject *)obj)) {fprintf(stderr,"TRYPYARRAYTEMPLATE:");PRINTPYOBJERR(obj);return 0;}\
        if (PyArray_DESCR(arr)->type==typecode)  {*(ctype *)(PyArray_DATA(arr))=*v; return 1;}\
        switch (PyArray_TYPE(arr)) {\
                case NPY_DOUBLE: *(npy_double *)(PyArray_DATA(arr))=*v; break;\
                case NPY_INT: *(npy_int *)(PyArray_DATA(arr))=*v; break;\
                case NPY_LONG: *(npy_long *)(PyArray_DATA(arr))=*v; break;\
                case NPY_FLOAT: *(npy_float *)(PyArray_DATA(arr))=*v; break;\
                case NPY_CDOUBLE: *(npy_double *)(PyArray_DATA(arr))=*v; break;\
                case NPY_CFLOAT: *(npy_float *)(PyArray_DATA(arr))=*v; break;\
                case NPY_BOOL: *(npy_bool *)(PyArray_DATA(arr))=(*v!=0); break;\
                case NPY_UBYTE: *(npy_ubyte *)(PyArray_DATA(arr))=*v; break;\
                case NPY_BYTE: *(npy_byte *)(PyArray_DATA(arr))=*v; break;\
                case NPY_SHORT: *(npy_short *)(PyArray_DATA(arr))=*v; break;\
                case NPY_USHORT: *(npy_ushort *)(PyArray_DATA(arr))=*v; break;\
                case NPY_UINT: *(npy_uint *)(PyArray_DATA(arr))=*v; break;\
                case NPY_ULONG: *(npy_ulong *)(PyArray_DATA(arr))=*v; break;\
                case NPY_LONGLONG: *(npy_longlong *)(PyArray_DATA(arr))=*v; break;\
                case NPY_ULONGLONG: *(npy_ulonglong *)(PyArray_DATA(arr))=*v; break;\
                case NPY_LONGDOUBLE: *(npy_longdouble *)(PyArray_DATA(arr))=*v; break;\
                case NPY_CLONGDOUBLE: *(npy_longdouble *)(PyArray_DATA(arr))=*v; break;\
                case NPY_OBJECT: PyArray_SETITEM(arr, PyArray_DATA(arr), pyobj_from_ ## ctype ## 1(*v)); break;\
        default: return -2;\
        };\
        return 1


/************************ See f2py2e/cfuncs.py: cfuncs ************************/

static int
double_from_pyobj(double* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
        *v = PyFloat_AsDouble(obj);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    tmp = PyNumber_Float(obj);
    if (tmp) {
        *v = PyFloat_AsDouble(tmp);
        Py_DECREF(tmp);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = _mymodule_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int try_pyarr_from_double(PyObject* obj,double* v) {
    TRYPYARRAYTEMPLATE(double,'d');
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(f90wrap_mytype__get__val,F90WRAP_MYTYPE__GET__VAL)(int*,double*);
extern void F_FUNC_US(f90wrap_mytype__set__val,F90WRAP_MYTYPE__SET__VAL)(int*,double*);
extern void F_FUNC_US(f90wrap_mymodule__mytype_initialise,F90WRAP_MYMODULE__MYTYPE_INITIALISE)(int*);
extern void F_FUNC_US(f90wrap_mymodule__mytype_finalise,F90WRAP_MYMODULE__MYTYPE_FINALISE)(int*);
extern void F_FUNC_US(f90wrap_mymodule__mysubroutine,F90WRAP_MYMODULE__MYSUBROUTINE)(double*,double*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/************************** f90wrap_mytype__get__val **************************/
static char doc_f2py_rout__mymodule_f90wrap_mytype__get__val[] = "\
f90wrap_val = f90wrap_mytype__get__val(this)\n\nWrapper for ``f90wrap_mytype__get__val``.\
\n\nParameters\n----------\n"
"this : input rank-1 array('i') with bounds (4)\n"
"\nReturns\n-------\n"
"f90wrap_val : float";
/* extern void F_FUNC_US(f90wrap_mytype__get__val,F90WRAP_MYTYPE__GET__VAL)(int*,double*); */
static PyObject *f2py_rout__mymodule_f90wrap_mytype__get__val(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_as_array = NULL;
    int capi_this_intent = 0;
    PyObject *this_capi = Py_None;
    double f90wrap_val = 0;
    static char *capi_kwlist[] = {"this",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:_mymodule.f90wrap_mytype__get__val",\
        capi_kwlist,&this_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=4;
    capi_this_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_mymodule._mymodule.f90wrap_mytype__get__val: failed to create array from the 1st argument `this`";
    capi_this_as_array = ndarray_from_pyobj(  NPY_INT,1,this_Dims,this_Rank,  capi_this_intent,this_capi,capi_errmess);

    if (capi_this_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _mymodule_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      this = (int *)(PyArray_DATA(capi_this_as_array));
    /* Processing variable f90wrap_val */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(this,&f90wrap_val);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("d",f90wrap_val);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable f90wrap_val */
    if((PyObject *)capi_this_as_array!=this_capi) {
        Py_XDECREF(capi_this_as_array); }
    }  /* if (capi_this_as_array == NULL) ... else of this */
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/********************** end of f90wrap_mytype__get__val **********************/

/************************** f90wrap_mytype__set__val **************************/
static char doc_f2py_rout__mymodule_f90wrap_mytype__set__val[] = "\
f90wrap_mytype__set__val(this,f90wrap_val)\n\nWrapper for ``f90wrap_mytype__set__val``.\
\n\nParameters\n----------\n"
"this : input rank-1 array('i') with bounds (4)\n"
"f90wrap_val : input float";
/* extern void F_FUNC_US(f90wrap_mytype__set__val,F90WRAP_MYTYPE__SET__VAL)(int*,double*); */
static PyObject *f2py_rout__mymodule_f90wrap_mytype__set__val(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_as_array = NULL;
    int capi_this_intent = 0;
    PyObject *this_capi = Py_None;
    double f90wrap_val = 0;
    PyObject *f90wrap_val_capi = Py_None;
    static char *capi_kwlist[] = {"this","f90wrap_val",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:_mymodule.f90wrap_mytype__set__val",\
        capi_kwlist,&this_capi,&f90wrap_val_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=4;
    capi_this_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_mymodule._mymodule.f90wrap_mytype__set__val: failed to create array from the 1st argument `this`";
    capi_this_as_array = ndarray_from_pyobj(  NPY_INT,1,this_Dims,this_Rank,  capi_this_intent,this_capi,capi_errmess);

    if (capi_this_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _mymodule_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      this = (int *)(PyArray_DATA(capi_this_as_array));
    /* Processing variable f90wrap_val */
        f2py_success = double_from_pyobj(&f90wrap_val,f90wrap_val_capi,"_mymodule.f90wrap_mytype__set__val() 2nd argument (f90wrap_val) can't be converted to double");
    if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(this,&f90wrap_val);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*if (f2py_success) of f90wrap_val*/
    /* End of cleaning variable f90wrap_val */
    if((PyObject *)capi_this_as_array!=this_capi) {
        Py_XDECREF(capi_this_as_array); }
    }  /* if (capi_this_as_array == NULL) ... else of this */
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/********************** end of f90wrap_mytype__set__val **********************/

/******************** f90wrap_mymodule__mytype_initialise ********************/
static char doc_f2py_rout__mymodule_f90wrap_mymodule__mytype_initialise[] = "\
this = f90wrap_mymodule__mytype_initialise()\n\nWrapper for ``f90wrap_mymodule__mytype_initialise``.\
\n\nReturns\n-------\n"
"this : rank-1 array('i') with bounds (4)";
/* extern void F_FUNC_US(f90wrap_mymodule__mytype_initialise,F90WRAP_MYMODULE__MYTYPE_INITIALISE)(int*); */
static PyObject *f2py_rout__mymodule_f90wrap_mymodule__mytype_initialise(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_as_array = NULL;
    int capi_this_intent = 0;
    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:_mymodule.f90wrap_mymodule__mytype_initialise",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=4;
    capi_this_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "_mymodule._mymodule.f90wrap_mymodule__mytype_initialise: failed to create array from the hidden `this`";
    capi_this_as_array = ndarray_from_pyobj(  NPY_INT,1,this_Dims,this_Rank,  capi_this_intent,Py_None,capi_errmess);

    if (capi_this_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _mymodule_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      this = (int *)(PyArray_DATA(capi_this_as_array));
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(this);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_this_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_this_as_array == NULL) ... else of this */
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************** end of f90wrap_mymodule__mytype_initialise *****************/

/********************* f90wrap_mymodule__mytype_finalise *********************/
static char doc_f2py_rout__mymodule_f90wrap_mymodule__mytype_finalise[] = "\
f90wrap_mymodule__mytype_finalise(this)\n\nWrapper for ``f90wrap_mymodule__mytype_finalise``.\
\n\nParameters\n----------\n"
"this : input rank-1 array('i') with bounds (4)";
/* extern void F_FUNC_US(f90wrap_mymodule__mytype_finalise,F90WRAP_MYMODULE__MYTYPE_FINALISE)(int*); */
static PyObject *f2py_rout__mymodule_f90wrap_mymodule__mytype_finalise(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_as_array = NULL;
    int capi_this_intent = 0;
    PyObject *this_capi = Py_None;
    static char *capi_kwlist[] = {"this",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:_mymodule.f90wrap_mymodule__mytype_finalise",\
        capi_kwlist,&this_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=4;
    capi_this_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_mymodule._mymodule.f90wrap_mymodule__mytype_finalise: failed to create array from the 1st argument `this`";
    capi_this_as_array = ndarray_from_pyobj(  NPY_INT,1,this_Dims,this_Rank,  capi_this_intent,this_capi,capi_errmess);

    if (capi_this_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _mymodule_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      this = (int *)(PyArray_DATA(capi_this_as_array));
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(this);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_this_as_array!=this_capi) {
        Py_XDECREF(capi_this_as_array); }
    }  /* if (capi_this_as_array == NULL) ... else of this */
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************** end of f90wrap_mymodule__mytype_finalise ******************/

/*********************** f90wrap_mymodule__mysubroutine ***********************/
static char doc_f2py_rout__mymodule_f90wrap_mymodule__mysubroutine[] = "\
f90wrap_mymodule__mysubroutine(a,b,tt)\n\nWrapper for ``f90wrap_mymodule__mysubroutine``.\
\n\nParameters\n----------\n"
"a : input float\n"
"b : in/output rank-0 array(float,'d')\n"
"tt : input rank-1 array('i') with bounds (4)";
/* extern void F_FUNC_US(f90wrap_mymodule__mysubroutine,F90WRAP_MYMODULE__MYSUBROUTINE)(double*,double*,int*); */
static PyObject *f2py_rout__mymodule_f90wrap_mymodule__mysubroutine(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    double a = 0;
    PyObject *a_capi = Py_None;
    double b = 0;
    PyObject *b_capi = Py_None;
    int *tt = NULL;
    npy_intp tt_Dims[1] = {-1};
    const int tt_Rank = 1;
    PyArrayObject *capi_tt_as_array = NULL;
    int capi_tt_intent = 0;
    PyObject *tt_capi = Py_None;
    static char *capi_kwlist[] = {"a","b","tt",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOO|:_mymodule.f90wrap_mymodule__mysubroutine",\
        capi_kwlist,&a_capi,&b_capi,&tt_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable a */
        f2py_success = double_from_pyobj(&a,a_capi,"_mymodule.f90wrap_mymodule__mysubroutine() 1st argument (a) can't be converted to double");
    if (f2py_success) {
    /* Processing variable b */
        f2py_success = double_from_pyobj(&b,b_capi,"_mymodule.f90wrap_mymodule__mysubroutine() 2nd argument (b) can't be converted to double");
    if (f2py_success) {
    /* Processing variable tt */
    tt_Dims[0]=4;
    capi_tt_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_mymodule._mymodule.f90wrap_mymodule__mysubroutine: failed to create array from the 3rd argument `tt`";
    capi_tt_as_array = ndarray_from_pyobj(  NPY_INT,1,tt_Dims,tt_Rank,  capi_tt_intent,tt_capi,capi_errmess);

    if (capi_tt_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _mymodule_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      tt = (int *)(PyArray_DATA(capi_tt_as_array));
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(&a,&b,tt);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
    f2py_success = try_pyarr_from_double(b_capi,&b);
    if (f2py_success) {
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
    } /*if (f2py_success) of b pyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_tt_as_array!=tt_capi) {
        Py_XDECREF(capi_tt_as_array); }
    }  /* if (capi_tt_as_array == NULL) ... else of tt */
    /* End of cleaning variable tt */
    } /*if (f2py_success) of b*/
    /* End of cleaning variable b */
    } /*if (f2py_success) of a*/
    /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************* end of f90wrap_mymodule__mysubroutine *******************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"f90wrap_mytype__get__val",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_mytype__get__val,F90WRAP_MYTYPE__GET__VAL),  (f2py_init_func)f2py_rout__mymodule_f90wrap_mytype__get__val,doc_f2py_rout__mymodule_f90wrap_mytype__get__val},
    {"f90wrap_mytype__set__val",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_mytype__set__val,F90WRAP_MYTYPE__SET__VAL),  (f2py_init_func)f2py_rout__mymodule_f90wrap_mytype__set__val,doc_f2py_rout__mymodule_f90wrap_mytype__set__val},
    {"f90wrap_mymodule__mytype_initialise",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_mymodule__mytype_initialise,F90WRAP_MYMODULE__MYTYPE_INITIALISE),  (f2py_init_func)f2py_rout__mymodule_f90wrap_mymodule__mytype_initialise,doc_f2py_rout__mymodule_f90wrap_mymodule__mytype_initialise},
    {"f90wrap_mymodule__mytype_finalise",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_mymodule__mytype_finalise,F90WRAP_MYMODULE__MYTYPE_FINALISE),  (f2py_init_func)f2py_rout__mymodule_f90wrap_mymodule__mytype_finalise,doc_f2py_rout__mymodule_f90wrap_mymodule__mytype_finalise},
    {"f90wrap_mymodule__mysubroutine",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_mymodule__mysubroutine,F90WRAP_MYMODULE__MYSUBROUTINE),  (f2py_init_func)f2py_rout__mymodule_f90wrap_mymodule__mysubroutine,doc_f2py_rout__mymodule_f90wrap_mymodule__mysubroutine},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "_mymodule",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit__mymodule(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = _mymodule_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module _mymodule (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("2.3.3");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module '_mymodule' is auto-generated with f2py (version:2.3.3).\nFunctions:\n"
"    f90wrap_val = f90wrap_mytype__get__val(this)\n"
"    f90wrap_mytype__set__val(this,f90wrap_val)\n"
"    this = f90wrap_mymodule__mytype_initialise()\n"
"    f90wrap_mymodule__mytype_finalise(this)\n"
"    f90wrap_mymodule__mysubroutine(a,b,tt)\n"
".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("2.3.3");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    _mymodule_error = PyErr_NewException ("_mymodule.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "__mymodule_error", _mymodule_error);
    Py_DECREF(_mymodule_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }





/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#if Py_GIL_DISABLED
    // signal whether this module supports running with the GIL disabled
    PyUnstable_Module_SetGIL(m , Py_MOD_GIL_USED);
#endif

#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"_mymodule");
#endif

    if (PyType_Ready(&PyFortran_Type) < 0) {
        return NULL;
    }

    return m;
}
#ifdef __cplusplus
}
#endif
