/* File: _pywrappermodule.c
 * This file is auto-generated with f2py (version:2.3.3).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Tue Oct 21 20:19:16 2025
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
#include <string.h>
#include <math.h>


    /* custom abort handler - James Kermode <james.kermode@gmail.com> */
    #include <signal.h>
#include <setjmp.h>

    #define ABORT_BUFFER_SIZE 1024
    extern jmp_buf environment_buffer;
    extern char abort_message[ABORT_BUFFER_SIZE];
    void f90wrap_abort_(char *message, int len);
    void f90wrap_abort_int_handler(int signum);

    #include <stdlib.h>
    #include <string.h>

    jmp_buf environment_buffer;
    char abort_message[ABORT_BUFFER_SIZE];

    void f90wrap_abort_(char *message, int len_message)
    {
      strncpy(abort_message, message, ABORT_BUFFER_SIZE);
      abort_message[ABORT_BUFFER_SIZE-1] = '\0';
      longjmp(environment_buffer, 0);
    }

    // copy of f90wrap_abort_ with a second underscore
    // void (*f90wrap_abort__)(char *, int) = &f90wrap_abort_;
    void f90wrap_abort__(char *message, int len_message)
    {
      strncpy(abort_message, message, ABORT_BUFFER_SIZE);
      abort_message[ABORT_BUFFER_SIZE-1] = '\0';
      longjmp(environment_buffer, 0);
    }


    void f90wrap_abort_int_handler(int signum)
    {
      char message[] = "Interrupt occured";
      f90wrap_abort_(message, strlen(message));
    }

    /* end of custom abort handler  */
    
/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *_pywrapper_error;
static PyObject *_pywrapper_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/

#define PRINTPYOBJERR(obj)\
    fprintf(stderr,"_pywrapper.error is related to ");\
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");

#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)


#define STRINGMALLOC(str,len)\
    if ((str = (string)malloc(len+1)) == NULL) {\
        PyErr_SetString(PyExc_MemoryError, "out of memory");\
        goto capi_fail;\
    } else {\
        (str)[len] = '\0';\
    }


#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/* See fortranobject.h for definitions. The macros here are provided for BC. */
#define rank f2py_rank
#define shape f2py_shape
#define fshape f2py_shape
#define len f2py_len
#define flen f2py_flen
#define slen f2py_slen
#define size f2py_size


#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)


/*
STRINGPADN replaces null values with padding values from the right.

`to` must have size of at least N bytes.

If the `to[N-1]` has null value, then replace it and all the
preceding, nulls with the given padding.

STRINGPADN(to, N, PADDING, NULLVALUE) is an inverse operation.
*/
#define STRINGPADN(to, N, NULLVALUE, PADDING)                   \
    do {                                                        \
        int _m = (N);                                           \
        char *_to = (to);                                       \
        for (_m -= 1; _m >= 0 && _to[_m] == NULLVALUE; _m--) {  \
             _to[_m] = PADDING;                                 \
        }                                                       \
    } while (0)


#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif


#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(_pywrapper_error,errstring);\
        /*goto capi_fail;*/\
    } else 

/*
STRINGCOPYN copies N bytes.

`to` and `from` buffers must have sizes of at least N bytes.
*/
#define STRINGCOPYN(to,from,N)                                  \
    do {                                                        \
        int _m = (N);                                           \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, _m);             \
    } while (0)


/************************ See f2py2e/cfuncs.py: cfuncs ************************/

/*
  Create a new string buffer `str` of at most length `len` from a
  Python string-like object `obj`.

  The string buffer has given size (len) or the size of inistr when len==-1.

  The string buffer is padded with blanks: in Fortran, trailing blanks
  are insignificant contrary to C nulls.
 */
static int
string_from_pyobj(string *str, int *len, const string inistr, PyObject *obj,
                  const char *errmess)
{
    PyObject *tmp = NULL;
    string buf = NULL;
    npy_intp n = -1;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",
               (char*)str, *len, (char *)inistr, obj);
#endif
    if (obj == Py_None) {
        n = strlen(inistr);
        buf = inistr;
    }
    else if (PyArray_Check(obj)) {
        PyArrayObject *arr = (PyArrayObject *)obj;
        if (!ISCONTIGUOUS(arr)) {
            PyErr_SetString(PyExc_ValueError,
                            "array object is non-contiguous.");
            goto capi_fail;
        }
        n = PyArray_NBYTES(arr);
        buf = PyArray_DATA(arr);
        n = strnlen(buf, n);
    }
    else {
        if (PyBytes_Check(obj)) {
            tmp = obj;
            Py_INCREF(tmp);
        }
        else if (PyUnicode_Check(obj)) {
            tmp = PyUnicode_AsASCIIString(obj);
        }
        else {
            PyObject *tmp2;
            tmp2 = PyObject_Str(obj);
            if (tmp2) {
                tmp = PyUnicode_AsASCIIString(tmp2);
                Py_DECREF(tmp2);
            }
            else {
                tmp = NULL;
            }
        }
        if (tmp == NULL) goto capi_fail;
        n = PyBytes_GET_SIZE(tmp);
        buf = PyBytes_AS_STRING(tmp);
    }
    if (*len == -1) {
        /* TODO: change the type of `len` so that we can remove this */
        if (n > NPY_MAX_INT) {
            PyErr_SetString(PyExc_OverflowError,
                            "object too large for a 32-bit int");
            goto capi_fail;
        }
        *len = n;
    }
    else if (*len < n) {
        /* discard the last (len-n) bytes of input buf */
        n = *len;
    }
    if (n < 0 || *len < 0 || buf == NULL) {
        goto capi_fail;
    }
    STRINGMALLOC(*str, *len);  // *str is allocated with size (*len + 1)
    if (n < *len) {
        /*
          Pad fixed-width string with nulls. The caller will replace
          nulls with blanks when the corresponding argument is not
          intent(c).
        */
        memset(*str + n, '\0', *len - n);
    }
    STRINGCOPYN(*str, buf, n);
    Py_XDECREF(tmp);
    return 1;
capi_fail:
    Py_XDECREF(tmp);
    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = _pywrapper_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


/*
  try_pyarr_from_string copies str[:len(obj)] to the data of an `ndarray`.

  If obj is an `ndarray`, it is assumed to be contiguous.

  If the specified len==-1, str must be null-terminated.
*/
static int try_pyarr_from_string(PyObject *obj,
                                 const string str, const int len) {
#ifdef DEBUGCFUNCS
fprintf(stderr, "try_pyarr_from_string(str='%s', len=%d, obj=%p)\n",
        (char*)str,len, obj);
#endif
    if (!obj) return -2; /* Object missing */
    if (obj == Py_None) return -1; /* None */
    if (!PyArray_Check(obj)) goto capi_fail; /* not an ndarray */
    if (PyArray_Check(obj)) {
        PyArrayObject *arr = (PyArrayObject *)obj;
        assert(ISCONTIGUOUS(arr));
        string buf = PyArray_DATA(arr);
        npy_intp n = len;
        if (n == -1) {
            /* Assuming null-terminated str. */
            n = strlen(str);
        }
        if (n > PyArray_NBYTES(arr)) {
            n = PyArray_NBYTES(arr);
        }
        STRINGCOPYN(buf, str, n);
        return 1;
    }
capi_fail:
    PRINTPYOBJERR(obj);
    PyErr_SetString(_pywrapper_error, "try_pyarr_from_string failed");
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(f90wrap_m_string_test__string_in,F90WRAP_M_STRING_TEST__STRING_IN)(string,size_t);
extern void F_FUNC_US(f90wrap_m_string_test__string_in_array,F90WRAP_M_STRING_TEST__STRING_IN_ARRAY)(int*,string*,size_t);
extern void F_FUNC_US(f90wrap_m_string_test__string_in_array_hardcoded_size,F90WRAP_M_STRING_TEST__STRING_IN_ARRAY_HARDCODED_SIZE)(string*,size_t);
extern void F_FUNC_US(f90wrap_m_string_test__string_to_string,F90WRAP_M_STRING_TEST__STRING_TO_STRING)(string,string,size_t,size_t);
extern void F_FUNC_US(f90wrap_m_string_test__string_to_string_array,F90WRAP_M_STRING_TEST__STRING_TO_STRING_ARRAY)(int*,int*,string*,string*,size_t,size_t);
extern void F_FUNC_US(f90wrap_m_string_test__string_out,F90WRAP_M_STRING_TEST__STRING_OUT)(string,size_t);
extern void F_FUNC_US(f90wrap_m_string_test__string_out_optional,F90WRAP_M_STRING_TEST__STRING_OUT_OPTIONAL)(string,size_t);
extern void F_FUNC_US(f90wrap_m_string_test__string_out_optional_array,F90WRAP_M_STRING_TEST__STRING_OUT_OPTIONAL_ARRAY)(int*,string*,size_t);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************** f90wrap_m_string_test__string_in **********************/
static char doc_f2py_rout__pywrapper_f90wrap_m_string_test__string_in[] = "\
f90wrap_m_string_test__string_in(input)\n\nWrapper for ``f90wrap_m_string_test__string_in``.\
\n\nParameters\n----------\n"
"input : input string(len=-1)";
/* extern void F_FUNC_US(f90wrap_m_string_test__string_in,F90WRAP_M_STRING_TEST__STRING_IN)(string,size_t); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_string_test__string_in(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    string input = NULL;
    int slen(input);
    PyObject *input_capi = Py_None;
    static char *capi_kwlist[] = {"input",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:_pywrapper.f90wrap_m_string_test__string_in",\
        capi_kwlist,&input_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable input */
    slen(input) = -1;
    f2py_success = string_from_pyobj(&input,&slen(input),"",input_capi,"string_from_pyobj failed in converting 1st argument`input' of _pywrapper.f90wrap_m_string_test__string_in to C string");
    if (f2py_success) {
        STRINGPADN(input, slen(input), '\0', ' ');
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(input,slen(input));
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
        STRINGFREE(input);
    }  /*if (f2py_success) of input*/
    /* End of cleaning variable input */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************** end of f90wrap_m_string_test__string_in ******************/

/******************* f90wrap_m_string_test__string_in_array *******************/
static char doc_f2py_rout__pywrapper_f90wrap_m_string_test__string_in_array[] = "\
f90wrap_m_string_test__string_in_array(input)\n\nWrapper for ``f90wrap_m_string_test__string_in_array``.\
\n\nParameters\n----------\n"
"input : input rank-1 array('S') with bounds (f90wrap_n0)";
/* extern void F_FUNC_US(f90wrap_m_string_test__string_in_array,F90WRAP_M_STRING_TEST__STRING_IN_ARRAY)(int*,string*,size_t); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_string_test__string_in_array(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,string*,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int f90wrap_n0 = 0;
    string *input = NULL;
    npy_intp input_Dims[1] = {-1};
    const int input_Rank = 1;
    PyArrayObject *capi_input_as_array = NULL;
    int capi_input_intent = 0;
    int slen(input) = 0;
    PyObject *input_capi = Py_None;
    static char *capi_kwlist[] = {"input",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:_pywrapper.f90wrap_m_string_test__string_in_array",\
        capi_kwlist,&input_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable input */
    ;
    capi_input_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_string_test__string_in_array: failed to create array from the 1st argument `input`";
    capi_input_as_array = ndarray_from_pyobj(  NPY_STRING,(6),input_Dims,input_Rank,  capi_input_intent,input_capi,capi_errmess);

    if (capi_input_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      input = (string *)(PyArray_DATA(capi_input_as_array));
    slen(input) = f2py_itemsize(input);
    /* Processing variable f90wrap_n0 */
    f90wrap_n0 = shape(input, 0);
    CHECKSCALAR(shape(input, 0) == f90wrap_n0,"shape(input, 0) == f90wrap_n0","hidden f90wrap_n0","f90wrap_m_string_test__string_in_array:f90wrap_n0=%d",f90wrap_n0) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(&f90wrap_n0,input,slen(input));
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*CHECKSCALAR(shape(input, 0) == f90wrap_n0)*/
    /* End of cleaning variable f90wrap_n0 */
    if((PyObject *)capi_input_as_array!=input_capi) {
        Py_XDECREF(capi_input_as_array); }
    }  /* if (capi_input_as_array == NULL) ... else of input */
    /* End of cleaning variable input */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*************** end of f90wrap_m_string_test__string_in_array ***************/

/*********** f90wrap_m_string_test__string_in_array_hardcoded_size ***********/
static char doc_f2py_rout__pywrapper_f90wrap_m_string_test__string_in_array_hardcoded_size[] = "\
f90wrap_m_string_test__string_in_array_hardcoded_size(input)\n\nWrapper for ``f90wrap_m_string_test__string_in_array_hardcoded_size``.\
\n\nParameters\n----------\n"
"input : input rank-1 array('S') with bounds (2)";
/* extern void F_FUNC_US(f90wrap_m_string_test__string_in_array_hardcoded_size,F90WRAP_M_STRING_TEST__STRING_IN_ARRAY_HARDCODED_SIZE)(string*,size_t); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_string_test__string_in_array_hardcoded_size(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string*,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    string *input = NULL;
    npy_intp input_Dims[1] = {-1};
    const int input_Rank = 1;
    PyArrayObject *capi_input_as_array = NULL;
    int capi_input_intent = 0;
    int slen(input) = 0;
    PyObject *input_capi = Py_None;
    static char *capi_kwlist[] = {"input",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:_pywrapper.f90wrap_m_string_test__string_in_array_hardcoded_size",\
        capi_kwlist,&input_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable input */
    input_Dims[0]=2;
    capi_input_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_string_test__string_in_array_hardcoded_size: failed to create array from the 1st argument `input`";
    capi_input_as_array = ndarray_from_pyobj(  NPY_STRING,(6),input_Dims,input_Rank,  capi_input_intent,input_capi,capi_errmess);

    if (capi_input_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      input = (string *)(PyArray_DATA(capi_input_as_array));
    slen(input) = f2py_itemsize(input);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(input,slen(input));
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_input_as_array!=input_capi) {
        Py_XDECREF(capi_input_as_array); }
    }  /* if (capi_input_as_array == NULL) ... else of input */
    /* End of cleaning variable input */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******** end of f90wrap_m_string_test__string_in_array_hardcoded_size ********/

/****************** f90wrap_m_string_test__string_to_string ******************/
static char doc_f2py_rout__pywrapper_f90wrap_m_string_test__string_to_string[] = "\
output = f90wrap_m_string_test__string_to_string(input)\n\nWrapper for ``f90wrap_m_string_test__string_to_string``.\
\n\nParameters\n----------\n"
"input : input string(len=-1)\n"
"\nReturns\n-------\n"
"output : string(len=1024)";
/* extern void F_FUNC_US(f90wrap_m_string_test__string_to_string,F90WRAP_M_STRING_TEST__STRING_TO_STRING)(string,string,size_t,size_t); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_string_test__string_to_string(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,string,size_t,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    string input = NULL;
    int slen(input);
    PyObject *input_capi = Py_None;
    string output = NULL;
    int slen(output);
    PyObject *output_capi = Py_None;
    static char *capi_kwlist[] = {"input",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:_pywrapper.f90wrap_m_string_test__string_to_string",\
        capi_kwlist,&input_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable input */
    slen(input) = -1;
    f2py_success = string_from_pyobj(&input,&slen(input),"",input_capi,"string_from_pyobj failed in converting 1st argument`input' of _pywrapper.f90wrap_m_string_test__string_to_string to C string");
    if (f2py_success) {
        STRINGPADN(input, slen(input), '\0', ' ');
    /* Processing variable output */
    slen(output) = 1024;
    f2py_success = string_from_pyobj(&output,&slen(output),"",output_capi,"string_from_pyobj failed in converting hidden`output' of _pywrapper.f90wrap_m_string_test__string_to_string to C string");
    if (f2py_success) {
        STRINGPADN(output, slen(output), '\0', ' ');
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(input,output,slen(input),slen(output));
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
        STRINGPADN(output, slen(output), ' ', '\0');
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("y",output);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
        STRINGFREE(output);
    }  /*if (f2py_success) of output*/
    /* End of cleaning variable output */
        STRINGFREE(input);
    }  /*if (f2py_success) of input*/
    /* End of cleaning variable input */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*************** end of f90wrap_m_string_test__string_to_string ***************/

/*************** f90wrap_m_string_test__string_to_string_array ***************/
static char doc_f2py_rout__pywrapper_f90wrap_m_string_test__string_to_string_array[] = "\
f90wrap_m_string_test__string_to_string_array(input,output)\n\nWrapper for ``f90wrap_m_string_test__string_to_string_array``.\
\n\nParameters\n----------\n"
"input : input rank-1 array('S') with bounds (f90wrap_n0)\n"
"output : in/output rank-1 array('S') with bounds (f90wrap_n1)";
/* extern void F_FUNC_US(f90wrap_m_string_test__string_to_string_array,F90WRAP_M_STRING_TEST__STRING_TO_STRING_ARRAY)(int*,int*,string*,string*,size_t,size_t); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_string_test__string_to_string_array(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,string*,string*,size_t,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int f90wrap_n0 = 0;
    int f90wrap_n1 = 0;
    string *input = NULL;
    npy_intp input_Dims[1] = {-1};
    const int input_Rank = 1;
    PyArrayObject *capi_input_as_array = NULL;
    int capi_input_intent = 0;
    int slen(input) = 0;
    PyObject *input_capi = Py_None;
    string *output = NULL;
    npy_intp output_Dims[1] = {-1};
    const int output_Rank = 1;
    PyArrayObject *capi_output_as_array = NULL;
    int capi_output_intent = 0;
    int slen(output) = 0;
    PyObject *output_capi = Py_None;
    static char *capi_kwlist[] = {"input","output",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:_pywrapper.f90wrap_m_string_test__string_to_string_array",\
        capi_kwlist,&input_capi,&output_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable input */
    ;
    capi_input_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_string_test__string_to_string_array: failed to create array from the 1st argument `input`";
    capi_input_as_array = ndarray_from_pyobj(  NPY_STRING,-1,input_Dims,input_Rank,  capi_input_intent,input_capi,capi_errmess);

    if (capi_input_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      input = (string *)(PyArray_DATA(capi_input_as_array));
    slen(input) = f2py_itemsize(input);
    /* Processing variable output */
    ;
    capi_output_intent |= F2PY_INTENT_INOUT;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_string_test__string_to_string_array: failed to create array from the 2nd argument `output`";
    capi_output_as_array = ndarray_from_pyobj(  NPY_STRING,-1,output_Dims,output_Rank,  capi_output_intent,output_capi,capi_errmess);

    if (capi_output_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      output = (string *)(PyArray_DATA(capi_output_as_array));
    slen(output) = f2py_itemsize(output);
    /* Processing variable f90wrap_n0 */
    f90wrap_n0 = shape(input, 0);
    CHECKSCALAR(shape(input, 0) == f90wrap_n0,"shape(input, 0) == f90wrap_n0","hidden f90wrap_n0","f90wrap_m_string_test__string_to_string_array:f90wrap_n0=%d",f90wrap_n0) {
    /* Processing variable f90wrap_n1 */
    f90wrap_n1 = shape(output, 0);
    CHECKSCALAR(shape(output, 0) == f90wrap_n1,"shape(output, 0) == f90wrap_n1","hidden f90wrap_n1","f90wrap_m_string_test__string_to_string_array:f90wrap_n1=%d",f90wrap_n1) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(&f90wrap_n0,&f90wrap_n1,input,output,slen(input),slen(output));
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*CHECKSCALAR(shape(output, 0) == f90wrap_n1)*/
    /* End of cleaning variable f90wrap_n1 */
    } /*CHECKSCALAR(shape(input, 0) == f90wrap_n0)*/
    /* End of cleaning variable f90wrap_n0 */
    if((PyObject *)capi_output_as_array!=output_capi) {
        Py_XDECREF(capi_output_as_array); }
    }  /* if (capi_output_as_array == NULL) ... else of output */
    /* End of cleaning variable output */
    if((PyObject *)capi_input_as_array!=input_capi) {
        Py_XDECREF(capi_input_as_array); }
    }  /* if (capi_input_as_array == NULL) ... else of input */
    /* End of cleaning variable input */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/************ end of f90wrap_m_string_test__string_to_string_array ************/

/********************* f90wrap_m_string_test__string_out *********************/
static char doc_f2py_rout__pywrapper_f90wrap_m_string_test__string_out[] = "\
output = f90wrap_m_string_test__string_out()\n\nWrapper for ``f90wrap_m_string_test__string_out``.\
\n\nReturns\n-------\n"
"output : string(len=13)";
/* extern void F_FUNC_US(f90wrap_m_string_test__string_out,F90WRAP_M_STRING_TEST__STRING_OUT)(string,size_t); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_string_test__string_out(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    string output = NULL;
    int slen(output);
    PyObject *output_capi = Py_None;
    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:_pywrapper.f90wrap_m_string_test__string_out",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
    /* Processing variable output */
    slen(output) = 13;
    f2py_success = string_from_pyobj(&output,&slen(output),"",output_capi,"string_from_pyobj failed in converting hidden`output' of _pywrapper.f90wrap_m_string_test__string_out to C string");
    if (f2py_success) {
        STRINGPADN(output, slen(output), '\0', ' ');
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(output,slen(output));
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
        STRINGPADN(output, slen(output), ' ', '\0');
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("y",output);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
        STRINGFREE(output);
    }  /*if (f2py_success) of output*/
    /* End of cleaning variable output */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************** end of f90wrap_m_string_test__string_out ******************/

/***************** f90wrap_m_string_test__string_out_optional *****************/
static char doc_f2py_rout__pywrapper_f90wrap_m_string_test__string_out_optional[] = "\
f90wrap_m_string_test__string_out_optional([output])\n\nWrapper for ``f90wrap_m_string_test__string_out_optional``.\
\n\nOther Parameters\n----------------\n"
"output : in/output rank-0 array(string(len=13),'c')";
/* extern void F_FUNC_US(f90wrap_m_string_test__string_out_optional,F90WRAP_M_STRING_TEST__STRING_OUT_OPTIONAL)(string,size_t); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_string_test__string_out_optional(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    string output = NULL;
    int slen(output);
    PyObject *output_capi = Py_None;
    static char *capi_kwlist[] = {"output",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|O:_pywrapper.f90wrap_m_string_test__string_out_optional",\
        capi_kwlist,&output_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable output */
    slen(output) = 13;
    f2py_success = string_from_pyobj(&output,&slen(output),"",output_capi,"string_from_pyobj failed in converting 1st keyword`output' of _pywrapper.f90wrap_m_string_test__string_out_optional to C string");
    if (f2py_success) {
        STRINGPADN(output, slen(output), '\0', ' ');
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(output_capi == Py_None ? NULL : output,slen(output));
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
        STRINGPADN(output, slen(output), ' ', '\0');
    f2py_success = try_pyarr_from_string(output_capi, output,
                                          slen(output));
    if (f2py_success) {
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
    } /*if (f2py_success) of output pyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
        STRINGFREE(output);
    }  /*if (f2py_success) of output*/
    /* End of cleaning variable output */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/************* end of f90wrap_m_string_test__string_out_optional *************/

/************** f90wrap_m_string_test__string_out_optional_array **************/
static char doc_f2py_rout__pywrapper_f90wrap_m_string_test__string_out_optional_array[] = "\
f90wrap_m_string_test__string_out_optional_array([output])\n\nWrapper for ``f90wrap_m_string_test__string_out_optional_array``.\
\n\nOther Parameters\n----------------\n"
"output : in/output rank-1 array('S') with bounds (f90wrap_n0)";
/* extern void F_FUNC_US(f90wrap_m_string_test__string_out_optional_array,F90WRAP_M_STRING_TEST__STRING_OUT_OPTIONAL_ARRAY)(int*,string*,size_t); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_string_test__string_out_optional_array(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,string*,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int f90wrap_n0 = 0;
    string *output = NULL;
    npy_intp output_Dims[1] = {-1};
    const int output_Rank = 1;
    PyArrayObject *capi_output_as_array = NULL;
    int capi_output_intent = 0;
    int slen(output) = 0;
    PyObject *output_capi = Py_None;
    static char *capi_kwlist[] = {"output",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|O:_pywrapper.f90wrap_m_string_test__string_out_optional_array",\
        capi_kwlist,&output_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable output */
    ;
    capi_output_intent |= F2PY_INTENT_INOUT|F2PY_OPTIONAL;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_string_test__string_out_optional_array: failed to create array from the 1st keyword `output`";
  if (output_capi != Py_None) {
    capi_output_as_array = ndarray_from_pyobj(  NPY_STRING,(13),output_Dims,output_Rank,  capi_output_intent,output_capi,capi_errmess);
  }
    if (output_capi != Py_None) slen(output) = f2py_itemsize(output);

    if (output_capi != Py_None && capi_output_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      if (output_capi != Py_None) output = (string *)(PyArray_DATA(capi_output_as_array));
    /* Processing variable f90wrap_n0 */
    f90wrap_n0 = shape(output, 0);
    CHECKSCALAR(shape(output, 0) == f90wrap_n0,"shape(output, 0) == f90wrap_n0","hidden f90wrap_n0","f90wrap_m_string_test__string_out_optional_array:f90wrap_n0=%d",f90wrap_n0) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(&f90wrap_n0,output_capi == Py_None ? NULL : output,slen(output));
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*CHECKSCALAR(shape(output, 0) == f90wrap_n0)*/
    /* End of cleaning variable f90wrap_n0 */
    if((PyObject *)capi_output_as_array!=output_capi) {
        Py_XDECREF(capi_output_as_array); }
    }  /* if (capi_output_as_array == NULL) ... else of output */
    /* End of cleaning variable output */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/********** end of f90wrap_m_string_test__string_out_optional_array **********/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"f90wrap_m_string_test__string_in",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_string_test__string_in,F90WRAP_M_STRING_TEST__STRING_IN),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_string_test__string_in,doc_f2py_rout__pywrapper_f90wrap_m_string_test__string_in},
    {"f90wrap_m_string_test__string_in_array",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_string_test__string_in_array,F90WRAP_M_STRING_TEST__STRING_IN_ARRAY),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_string_test__string_in_array,doc_f2py_rout__pywrapper_f90wrap_m_string_test__string_in_array},
    {"f90wrap_m_string_test__string_in_array_hardcoded_size",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_string_test__string_in_array_hardcoded_size,F90WRAP_M_STRING_TEST__STRING_IN_ARRAY_HARDCODED_SIZE),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_string_test__string_in_array_hardcoded_size,doc_f2py_rout__pywrapper_f90wrap_m_string_test__string_in_array_hardcoded_size},
    {"f90wrap_m_string_test__string_to_string",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_string_test__string_to_string,F90WRAP_M_STRING_TEST__STRING_TO_STRING),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_string_test__string_to_string,doc_f2py_rout__pywrapper_f90wrap_m_string_test__string_to_string},
    {"f90wrap_m_string_test__string_to_string_array",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_string_test__string_to_string_array,F90WRAP_M_STRING_TEST__STRING_TO_STRING_ARRAY),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_string_test__string_to_string_array,doc_f2py_rout__pywrapper_f90wrap_m_string_test__string_to_string_array},
    {"f90wrap_m_string_test__string_out",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_string_test__string_out,F90WRAP_M_STRING_TEST__STRING_OUT),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_string_test__string_out,doc_f2py_rout__pywrapper_f90wrap_m_string_test__string_out},
    {"f90wrap_m_string_test__string_out_optional",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_string_test__string_out_optional,F90WRAP_M_STRING_TEST__STRING_OUT_OPTIONAL),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_string_test__string_out_optional,doc_f2py_rout__pywrapper_f90wrap_m_string_test__string_out_optional},
    {"f90wrap_m_string_test__string_out_optional_array",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_string_test__string_out_optional_array,F90WRAP_M_STRING_TEST__STRING_OUT_OPTIONAL_ARRAY),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_string_test__string_out_optional_array,doc_f2py_rout__pywrapper_f90wrap_m_string_test__string_out_optional_array},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "_pywrapper",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit__pywrapper(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = _pywrapper_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module _pywrapper (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("2.3.3");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module '_pywrapper' is auto-generated with f2py (version:2.3.3).\nFunctions:\n"
"    f90wrap_m_string_test__string_in(input)\n"
"    f90wrap_m_string_test__string_in_array(input)\n"
"    f90wrap_m_string_test__string_in_array_hardcoded_size(input)\n"
"    output = f90wrap_m_string_test__string_to_string(input)\n"
"    f90wrap_m_string_test__string_to_string_array(input,output)\n"
"    output = f90wrap_m_string_test__string_out()\n"
"    f90wrap_m_string_test__string_out_optional(output='')\n"
"    f90wrap_m_string_test__string_out_optional_array(output=)\n"
".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("2.3.3");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    _pywrapper_error = PyErr_NewException ("_pywrapper.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "__pywrapper_error", _pywrapper_error);
    Py_DECREF(_pywrapper_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }








/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#if Py_GIL_DISABLED
    // signal whether this module supports running with the GIL disabled
    PyUnstable_Module_SetGIL(m , Py_MOD_GIL_USED);
#endif

#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"_pywrapper");
#endif

    if (PyType_Ready(&PyFortran_Type) < 0) {
        return NULL;
    }

    return m;
}
#ifdef __cplusplus
}
#endif
