! Fortran support module for direct C wrappers
! Auto-generated by f90wrap

module f90wrap__cyldnad_support

    use dual_num_auto_diff
    use mcyldnad
    use iso_c_binding
    implicit none

contains

    subroutine f90wrap_dual_num__allocate(ptr) bind(C, name='__dual_num_auto_diff_MOD_f90wrap_dual_num__allocate')
        type(c_ptr), intent(out) :: ptr
        type(dual_num), pointer :: fptr

        allocate(fptr)
        ptr = c_loc(fptr)
    end subroutine f90wrap_dual_num__allocate

    subroutine f90wrap_dual_num__deallocate(ptr) bind(C, name='__dual_num_auto_diff_MOD_f90wrap_dual_num__deallocate')
        type(c_ptr), intent(inout) :: ptr
        type(dual_num), pointer :: fptr

        if (c_associated(ptr)) then
            call c_f_pointer(ptr, fptr)
            deallocate(fptr)
            ptr = c_null_ptr
        end if
    end subroutine f90wrap_dual_num__deallocate

    subroutine dual_num_initialise(self, this) bind(C, name='__dual_num_auto_diff_MOD_dual_num_initialise')
        type(c_ptr), value :: self
        type(c_ptr), intent(out) :: this

        ! Default initialization (Fortran handles this automatically)
        ! Just return the same pointer
        this = self
    end subroutine dual_num_initialise

    subroutine dual_num_finalise(self, this) bind(C, name='__dual_num_auto_diff_MOD_dual_num_finalise')
        type(c_ptr), value :: self
        type(c_ptr), intent(inout) :: this

        ! Default finalization (cleanup happens at deallocation)
        ! Return the same pointer
        this = self
    end subroutine dual_num_finalise

    subroutine f90wrap_dual_num__get__x_ad_(self_ptr, value) bind(C, name='__dual_num_auto_diff_MOD_f90wrap_dual_num__get__x_ad_')
        type(c_ptr), value :: self_ptr
        real(c_double), intent(out) :: value
        type(dual_num), pointer :: self

        call c_f_pointer(self_ptr, self)
        value = self%x_ad_
    end subroutine f90wrap_dual_num__get__x_ad_

    subroutine f90wrap_dual_num__set__x_ad_(self_ptr, value) bind(C, name='__dual_num_auto_diff_MOD_f90wrap_dual_num__set__x_ad_')
        type(c_ptr), value :: self_ptr
        real(c_double), intent(in) :: value
        type(dual_num), pointer :: self

        call c_f_pointer(self_ptr, self)
        self%x_ad_ = value
    end subroutine f90wrap_dual_num__set__x_ad_

end module f90wrap__cyldnad_support
