/* File: _pywrappermodule.c
 * This file is auto-generated with f2py (version:2.3.3).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Tue Oct 21 20:19:23 2025
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
/*need_includes0*/


    /* custom abort handler - James Kermode <james.kermode@gmail.com> */
    #include <signal.h>
#include <setjmp.h>

    #define ABORT_BUFFER_SIZE 1024
    extern jmp_buf environment_buffer;
    extern char abort_message[ABORT_BUFFER_SIZE];
    void f90wrap_abort_(char *message, int len);
    void f90wrap_abort_int_handler(int signum);

    #include <stdlib.h>
    #include <string.h>

    jmp_buf environment_buffer;
    char abort_message[ABORT_BUFFER_SIZE];

    void f90wrap_abort_(char *message, int len_message)
    {
      strncpy(abort_message, message, ABORT_BUFFER_SIZE);
      abort_message[ABORT_BUFFER_SIZE-1] = '\0';
      longjmp(environment_buffer, 0);
    }

    // copy of f90wrap_abort_ with a second underscore
    // void (*f90wrap_abort__)(char *, int) = &f90wrap_abort_;
    void f90wrap_abort__(char *message, int len_message)
    {
      strncpy(abort_message, message, ABORT_BUFFER_SIZE);
      abort_message[ABORT_BUFFER_SIZE-1] = '\0';
      longjmp(environment_buffer, 0);
    }


    void f90wrap_abort_int_handler(int signum)
    {
      char message[] = "Interrupt occured";
      f90wrap_abort_(message, strlen(message));
    }

    /* end of custom abort handler  */
    
/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *_pywrapper_error;
static PyObject *_pywrapper_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef signed char signed_char;

#if defined(NPY_OS_WIN32)
typedef __int64 long_long;
#else
typedef long long long_long;
typedef unsigned long long unsigned_long_long;
#endif

typedef signed char signed_char;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif


#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/* See fortranobject.h for definitions. The macros here are provided for BC. */
#define rank f2py_rank
#define shape f2py_shape
#define fshape f2py_shape
#define len f2py_len
#define flen f2py_flen
#define slen f2py_slen
#define size f2py_size


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
/*need_cfuncs*/

/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(f90wrap_m_out_test__out_scalar_int1,F90WRAP_M_OUT_TEST__OUT_SCALAR_INT1)(signed_char*);
extern void F_FUNC_US(f90wrap_m_out_test__out_scalar_int2,F90WRAP_M_OUT_TEST__OUT_SCALAR_INT2)(short*);
extern void F_FUNC_US(f90wrap_m_out_test__out_scalar_int4,F90WRAP_M_OUT_TEST__OUT_SCALAR_INT4)(int*);
extern void F_FUNC_US(f90wrap_m_out_test__out_scalar_int8,F90WRAP_M_OUT_TEST__OUT_SCALAR_INT8)(long*);
extern void F_FUNC_US(f90wrap_m_out_test__out_scalar_real4,F90WRAP_M_OUT_TEST__OUT_SCALAR_REAL4)(float*);
extern void F_FUNC_US(f90wrap_m_out_test__out_scalar_real8,F90WRAP_M_OUT_TEST__OUT_SCALAR_REAL8)(double*);
extern void F_FUNC_US(f90wrap_m_out_test__out_array_int4,F90WRAP_M_OUT_TEST__OUT_ARRAY_INT4)(int*);
extern void F_FUNC_US(f90wrap_m_out_test__out_array_int8,F90WRAP_M_OUT_TEST__OUT_ARRAY_INT8)(long*);
extern void F_FUNC_US(f90wrap_m_out_test__out_array_real4,F90WRAP_M_OUT_TEST__OUT_ARRAY_REAL4)(float*);
extern void F_FUNC_US(f90wrap_m_out_test__out_array_real8,F90WRAP_M_OUT_TEST__OUT_ARRAY_REAL8)(double*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/******************** f90wrap_m_out_test__out_scalar_int1 ********************/
static char doc_f2py_rout__pywrapper_f90wrap_m_out_test__out_scalar_int1[] = "\
ret_output = f90wrap_m_out_test__out_scalar_int1()\n\nWrapper for ``f90wrap_m_out_test__out_scalar_int1``.\
\n\nReturns\n-------\n"
"ret_output : int";
/* extern void F_FUNC_US(f90wrap_m_out_test__out_scalar_int1,F90WRAP_M_OUT_TEST__OUT_SCALAR_INT1)(signed_char*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_out_test__out_scalar_int1(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(signed_char*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    signed_char ret_output = 0;
    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:_pywrapper.f90wrap_m_out_test__out_scalar_int1",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
    /* Processing variable ret_output */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(&ret_output);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("b",ret_output);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable ret_output */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************** end of f90wrap_m_out_test__out_scalar_int1 *****************/

/******************** f90wrap_m_out_test__out_scalar_int2 ********************/
static char doc_f2py_rout__pywrapper_f90wrap_m_out_test__out_scalar_int2[] = "\
ret_output = f90wrap_m_out_test__out_scalar_int2()\n\nWrapper for ``f90wrap_m_out_test__out_scalar_int2``.\
\n\nReturns\n-------\n"
"ret_output : int";
/* extern void F_FUNC_US(f90wrap_m_out_test__out_scalar_int2,F90WRAP_M_OUT_TEST__OUT_SCALAR_INT2)(short*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_out_test__out_scalar_int2(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(short*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    short ret_output = 0;
    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:_pywrapper.f90wrap_m_out_test__out_scalar_int2",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
    /* Processing variable ret_output */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(&ret_output);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("h",ret_output);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable ret_output */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************** end of f90wrap_m_out_test__out_scalar_int2 *****************/

/******************** f90wrap_m_out_test__out_scalar_int4 ********************/
static char doc_f2py_rout__pywrapper_f90wrap_m_out_test__out_scalar_int4[] = "\
ret_output = f90wrap_m_out_test__out_scalar_int4()\n\nWrapper for ``f90wrap_m_out_test__out_scalar_int4``.\
\n\nReturns\n-------\n"
"ret_output : int";
/* extern void F_FUNC_US(f90wrap_m_out_test__out_scalar_int4,F90WRAP_M_OUT_TEST__OUT_SCALAR_INT4)(int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_out_test__out_scalar_int4(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int ret_output = 0;
    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:_pywrapper.f90wrap_m_out_test__out_scalar_int4",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
    /* Processing variable ret_output */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(&ret_output);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("i",ret_output);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable ret_output */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************** end of f90wrap_m_out_test__out_scalar_int4 *****************/

/******************** f90wrap_m_out_test__out_scalar_int8 ********************/
static char doc_f2py_rout__pywrapper_f90wrap_m_out_test__out_scalar_int8[] = "\
ret_output = f90wrap_m_out_test__out_scalar_int8()\n\nWrapper for ``f90wrap_m_out_test__out_scalar_int8``.\
\n\nReturns\n-------\n"
"ret_output : int";
/* extern void F_FUNC_US(f90wrap_m_out_test__out_scalar_int8,F90WRAP_M_OUT_TEST__OUT_SCALAR_INT8)(long*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_out_test__out_scalar_int8(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(long*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    long ret_output = 0;
    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:_pywrapper.f90wrap_m_out_test__out_scalar_int8",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
    /* Processing variable ret_output */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(&ret_output);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("l",ret_output);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable ret_output */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************** end of f90wrap_m_out_test__out_scalar_int8 *****************/

/******************** f90wrap_m_out_test__out_scalar_real4 ********************/
static char doc_f2py_rout__pywrapper_f90wrap_m_out_test__out_scalar_real4[] = "\
ret_output = f90wrap_m_out_test__out_scalar_real4()\n\nWrapper for ``f90wrap_m_out_test__out_scalar_real4``.\
\n\nReturns\n-------\n"
"ret_output : float";
/* extern void F_FUNC_US(f90wrap_m_out_test__out_scalar_real4,F90WRAP_M_OUT_TEST__OUT_SCALAR_REAL4)(float*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_out_test__out_scalar_real4(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    float ret_output = 0;
    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:_pywrapper.f90wrap_m_out_test__out_scalar_real4",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
    /* Processing variable ret_output */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(&ret_output);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("f",ret_output);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable ret_output */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/**************** end of f90wrap_m_out_test__out_scalar_real4 ****************/

/******************** f90wrap_m_out_test__out_scalar_real8 ********************/
static char doc_f2py_rout__pywrapper_f90wrap_m_out_test__out_scalar_real8[] = "\
ret_output = f90wrap_m_out_test__out_scalar_real8()\n\nWrapper for ``f90wrap_m_out_test__out_scalar_real8``.\
\n\nReturns\n-------\n"
"ret_output : float";
/* extern void F_FUNC_US(f90wrap_m_out_test__out_scalar_real8,F90WRAP_M_OUT_TEST__OUT_SCALAR_REAL8)(double*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_out_test__out_scalar_real8(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    double ret_output = 0;
    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:_pywrapper.f90wrap_m_out_test__out_scalar_real8",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
    /* Processing variable ret_output */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(&ret_output);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("d",ret_output);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable ret_output */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/**************** end of f90wrap_m_out_test__out_scalar_real8 ****************/

/********************* f90wrap_m_out_test__out_array_int4 *********************/
static char doc_f2py_rout__pywrapper_f90wrap_m_out_test__out_array_int4[] = "\
ret_output = f90wrap_m_out_test__out_array_int4()\n\nWrapper for ``f90wrap_m_out_test__out_array_int4``.\
\n\nReturns\n-------\n"
"ret_output : rank-1 array('i') with bounds (1)";
/* extern void F_FUNC_US(f90wrap_m_out_test__out_array_int4,F90WRAP_M_OUT_TEST__OUT_ARRAY_INT4)(int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_out_test__out_array_int4(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *ret_output = NULL;
    npy_intp ret_output_Dims[1] = {-1};
    const int ret_output_Rank = 1;
    PyArrayObject *capi_ret_output_as_array = NULL;
    int capi_ret_output_intent = 0;
    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:_pywrapper.f90wrap_m_out_test__out_array_int4",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
    /* Processing variable ret_output */
    ret_output_Dims[0]=1;
    capi_ret_output_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_out_test__out_array_int4: failed to create array from the hidden `ret_output`";
    capi_ret_output_as_array = ndarray_from_pyobj(  NPY_INT,1,ret_output_Dims,ret_output_Rank,  capi_ret_output_intent,Py_None,capi_errmess);

    if (capi_ret_output_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      ret_output = (int *)(PyArray_DATA(capi_ret_output_as_array));
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(ret_output);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_ret_output_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_ret_output_as_array == NULL) ... else of ret_output */
    /* End of cleaning variable ret_output */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************** end of f90wrap_m_out_test__out_array_int4 *****************/

/********************* f90wrap_m_out_test__out_array_int8 *********************/
static char doc_f2py_rout__pywrapper_f90wrap_m_out_test__out_array_int8[] = "\
ret_output = f90wrap_m_out_test__out_array_int8()\n\nWrapper for ``f90wrap_m_out_test__out_array_int8``.\
\n\nReturns\n-------\n"
"ret_output : rank-1 array('l') with bounds (1)";
/* extern void F_FUNC_US(f90wrap_m_out_test__out_array_int8,F90WRAP_M_OUT_TEST__OUT_ARRAY_INT8)(long*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_out_test__out_array_int8(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(long*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    long *ret_output = NULL;
    npy_intp ret_output_Dims[1] = {-1};
    const int ret_output_Rank = 1;
    PyArrayObject *capi_ret_output_as_array = NULL;
    int capi_ret_output_intent = 0;
    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:_pywrapper.f90wrap_m_out_test__out_array_int8",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
    /* Processing variable ret_output */
    ret_output_Dims[0]=1;
    capi_ret_output_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_out_test__out_array_int8: failed to create array from the hidden `ret_output`";
    capi_ret_output_as_array = ndarray_from_pyobj(  NPY_LONG,1,ret_output_Dims,ret_output_Rank,  capi_ret_output_intent,Py_None,capi_errmess);

    if (capi_ret_output_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      ret_output = (long *)(PyArray_DATA(capi_ret_output_as_array));
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(ret_output);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_ret_output_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_ret_output_as_array == NULL) ... else of ret_output */
    /* End of cleaning variable ret_output */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************** end of f90wrap_m_out_test__out_array_int8 *****************/

/******************** f90wrap_m_out_test__out_array_real4 ********************/
static char doc_f2py_rout__pywrapper_f90wrap_m_out_test__out_array_real4[] = "\
ret_output = f90wrap_m_out_test__out_array_real4()\n\nWrapper for ``f90wrap_m_out_test__out_array_real4``.\
\n\nReturns\n-------\n"
"ret_output : rank-1 array('f') with bounds (1)";
/* extern void F_FUNC_US(f90wrap_m_out_test__out_array_real4,F90WRAP_M_OUT_TEST__OUT_ARRAY_REAL4)(float*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_out_test__out_array_real4(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    float *ret_output = NULL;
    npy_intp ret_output_Dims[1] = {-1};
    const int ret_output_Rank = 1;
    PyArrayObject *capi_ret_output_as_array = NULL;
    int capi_ret_output_intent = 0;
    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:_pywrapper.f90wrap_m_out_test__out_array_real4",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
    /* Processing variable ret_output */
    ret_output_Dims[0]=1;
    capi_ret_output_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_out_test__out_array_real4: failed to create array from the hidden `ret_output`";
    capi_ret_output_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,ret_output_Dims,ret_output_Rank,  capi_ret_output_intent,Py_None,capi_errmess);

    if (capi_ret_output_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      ret_output = (float *)(PyArray_DATA(capi_ret_output_as_array));
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(ret_output);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_ret_output_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_ret_output_as_array == NULL) ... else of ret_output */
    /* End of cleaning variable ret_output */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************** end of f90wrap_m_out_test__out_array_real4 *****************/

/******************** f90wrap_m_out_test__out_array_real8 ********************/
static char doc_f2py_rout__pywrapper_f90wrap_m_out_test__out_array_real8[] = "\
ret_output = f90wrap_m_out_test__out_array_real8()\n\nWrapper for ``f90wrap_m_out_test__out_array_real8``.\
\n\nReturns\n-------\n"
"ret_output : rank-1 array('d') with bounds (1)";
/* extern void F_FUNC_US(f90wrap_m_out_test__out_array_real8,F90WRAP_M_OUT_TEST__OUT_ARRAY_REAL8)(double*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_out_test__out_array_real8(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    double *ret_output = NULL;
    npy_intp ret_output_Dims[1] = {-1};
    const int ret_output_Rank = 1;
    PyArrayObject *capi_ret_output_as_array = NULL;
    int capi_ret_output_intent = 0;
    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:_pywrapper.f90wrap_m_out_test__out_array_real8",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
    /* Processing variable ret_output */
    ret_output_Dims[0]=1;
    capi_ret_output_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_out_test__out_array_real8: failed to create array from the hidden `ret_output`";
    capi_ret_output_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,ret_output_Dims,ret_output_Rank,  capi_ret_output_intent,Py_None,capi_errmess);

    if (capi_ret_output_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      ret_output = (double *)(PyArray_DATA(capi_ret_output_as_array));
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(ret_output);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_ret_output_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_ret_output_as_array == NULL) ... else of ret_output */
    /* End of cleaning variable ret_output */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************** end of f90wrap_m_out_test__out_array_real8 *****************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"f90wrap_m_out_test__out_scalar_int1",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_out_test__out_scalar_int1,F90WRAP_M_OUT_TEST__OUT_SCALAR_INT1),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_out_test__out_scalar_int1,doc_f2py_rout__pywrapper_f90wrap_m_out_test__out_scalar_int1},
    {"f90wrap_m_out_test__out_scalar_int2",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_out_test__out_scalar_int2,F90WRAP_M_OUT_TEST__OUT_SCALAR_INT2),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_out_test__out_scalar_int2,doc_f2py_rout__pywrapper_f90wrap_m_out_test__out_scalar_int2},
    {"f90wrap_m_out_test__out_scalar_int4",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_out_test__out_scalar_int4,F90WRAP_M_OUT_TEST__OUT_SCALAR_INT4),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_out_test__out_scalar_int4,doc_f2py_rout__pywrapper_f90wrap_m_out_test__out_scalar_int4},
    {"f90wrap_m_out_test__out_scalar_int8",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_out_test__out_scalar_int8,F90WRAP_M_OUT_TEST__OUT_SCALAR_INT8),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_out_test__out_scalar_int8,doc_f2py_rout__pywrapper_f90wrap_m_out_test__out_scalar_int8},
    {"f90wrap_m_out_test__out_scalar_real4",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_out_test__out_scalar_real4,F90WRAP_M_OUT_TEST__OUT_SCALAR_REAL4),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_out_test__out_scalar_real4,doc_f2py_rout__pywrapper_f90wrap_m_out_test__out_scalar_real4},
    {"f90wrap_m_out_test__out_scalar_real8",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_out_test__out_scalar_real8,F90WRAP_M_OUT_TEST__OUT_SCALAR_REAL8),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_out_test__out_scalar_real8,doc_f2py_rout__pywrapper_f90wrap_m_out_test__out_scalar_real8},
    {"f90wrap_m_out_test__out_array_int4",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_out_test__out_array_int4,F90WRAP_M_OUT_TEST__OUT_ARRAY_INT4),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_out_test__out_array_int4,doc_f2py_rout__pywrapper_f90wrap_m_out_test__out_array_int4},
    {"f90wrap_m_out_test__out_array_int8",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_out_test__out_array_int8,F90WRAP_M_OUT_TEST__OUT_ARRAY_INT8),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_out_test__out_array_int8,doc_f2py_rout__pywrapper_f90wrap_m_out_test__out_array_int8},
    {"f90wrap_m_out_test__out_array_real4",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_out_test__out_array_real4,F90WRAP_M_OUT_TEST__OUT_ARRAY_REAL4),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_out_test__out_array_real4,doc_f2py_rout__pywrapper_f90wrap_m_out_test__out_array_real4},
    {"f90wrap_m_out_test__out_array_real8",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_out_test__out_array_real8,F90WRAP_M_OUT_TEST__OUT_ARRAY_REAL8),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_out_test__out_array_real8,doc_f2py_rout__pywrapper_f90wrap_m_out_test__out_array_real8},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "_pywrapper",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit__pywrapper(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = _pywrapper_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module _pywrapper (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("2.3.3");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module '_pywrapper' is auto-generated with f2py (version:2.3.3).\nFunctions:\n"
"    ret_output = f90wrap_m_out_test__out_scalar_int1()\n"
"    ret_output = f90wrap_m_out_test__out_scalar_int2()\n"
"    ret_output = f90wrap_m_out_test__out_scalar_int4()\n"
"    ret_output = f90wrap_m_out_test__out_scalar_int8()\n"
"    ret_output = f90wrap_m_out_test__out_scalar_real4()\n"
"    ret_output = f90wrap_m_out_test__out_scalar_real8()\n"
"    ret_output = f90wrap_m_out_test__out_array_int4()\n"
"    ret_output = f90wrap_m_out_test__out_array_int8()\n"
"    ret_output = f90wrap_m_out_test__out_array_real4()\n"
"    ret_output = f90wrap_m_out_test__out_array_real8()\n"
".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("2.3.3");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    _pywrapper_error = PyErr_NewException ("_pywrapper.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "__pywrapper_error", _pywrapper_error);
    Py_DECREF(_pywrapper_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }










/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#if Py_GIL_DISABLED
    // signal whether this module supports running with the GIL disabled
    PyUnstable_Module_SetGIL(m , Py_MOD_GIL_USED);
#endif

#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"_pywrapper");
#endif

    if (PyType_Ready(&PyFortran_Type) < 0) {
        return NULL;
    }

    return m;
}
#ifdef __cplusplus
}
#endif
