/* File: _pywrappermodule.c
 * This file is auto-generated with f2py (version:2.3.3).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Tue Oct 21 20:19:36 2025
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
/*need_includes0*/


    /* custom abort handler - James Kermode <james.kermode@gmail.com> */
    #include <signal.h>
#include <setjmp.h>

    #define ABORT_BUFFER_SIZE 1024
    extern jmp_buf environment_buffer;
    extern char abort_message[ABORT_BUFFER_SIZE];
    void f90wrap_abort_(char *message, int len);
    void f90wrap_abort_int_handler(int signum);

    #include <stdlib.h>
    #include <string.h>

    jmp_buf environment_buffer;
    char abort_message[ABORT_BUFFER_SIZE];

    void f90wrap_abort_(char *message, int len_message)
    {
      strncpy(abort_message, message, ABORT_BUFFER_SIZE);
      abort_message[ABORT_BUFFER_SIZE-1] = '\0';
      longjmp(environment_buffer, 0);
    }

    // copy of f90wrap_abort_ with a second underscore
    // void (*f90wrap_abort__)(char *, int) = &f90wrap_abort_;
    void f90wrap_abort__(char *message, int len_message)
    {
      strncpy(abort_message, message, ABORT_BUFFER_SIZE);
      abort_message[ABORT_BUFFER_SIZE-1] = '\0';
      longjmp(environment_buffer, 0);
    }


    void f90wrap_abort_int_handler(int signum)
    {
      char message[] = "Interrupt occured";
      f90wrap_abort_(message, strlen(message));
    }

    /* end of custom abort handler  */
    
/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *_pywrapper_error;
static PyObject *_pywrapper_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/* See fortranobject.h for definitions. The macros here are provided for BC. */
#define rank f2py_rank
#define shape f2py_shape
#define fshape f2py_shape
#define len f2py_len
#define flen f2py_flen
#define slen f2py_slen
#define size f2py_size


#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif


#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/

static int
double_from_pyobj(double* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
        *v = PyFloat_AsDouble(obj);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    tmp = PyNumber_Float(obj);
    if (tmp) {
        *v = PyFloat_AsDouble(tmp);
        Py_DECREF(tmp);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = _pywrapper_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


static int
float_from_pyobj(float* v, PyObject *obj, const char *errmess)
{
    double d=0.0;
    if (double_from_pyobj(&d,obj,errmess)) {
        *v = (float)d;
        return 1;
    }
    return 0;
}


static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = _pywrapper_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(f90wrap_t_base_type__get__real_number,F90WRAP_T_BASE_TYPE__GET__REAL_NUMBER)(int*,float*);
extern void F_FUNC_US(f90wrap_t_base_type__set__real_number,F90WRAP_T_BASE_TYPE__SET__REAL_NUMBER)(int*,float*);
extern void F_FUNC_US(f90wrap_m_base_type__t_base_type_initialise,F90WRAP_M_BASE_TYPE__T_BASE_TYPE_INITIALISE)(int*);
extern void F_FUNC_US(f90wrap_m_base_type__t_base_type_finalise,F90WRAP_M_BASE_TYPE__T_BASE_TYPE_FINALISE)(int*);
extern void F_FUNC_US(f90wrap_t_composition__get__member,F90WRAP_T_COMPOSITION__GET__MEMBER)(int*,int*);
extern void F_FUNC_US(f90wrap_t_composition__set__member,F90WRAP_T_COMPOSITION__SET__MEMBER)(int*,int*);
extern void F_FUNC_US(f90wrap_m_composition__t_composition_initialise,F90WRAP_M_COMPOSITION__T_COMPOSITION_INITIALISE)(int*);
extern void F_FUNC_US(f90wrap_m_composition__t_composition_finalise,F90WRAP_M_COMPOSITION__T_COMPOSITION_FINALISE)(int*);
extern void F_FUNC_US(f90wrap_t_inheritance__get__integer_number,F90WRAP_T_INHERITANCE__GET__INTEGER_NUMBER)(int*,int*);
extern void F_FUNC_US(f90wrap_t_inheritance__set__integer_number,F90WRAP_T_INHERITANCE__SET__INTEGER_NUMBER)(int*,int*);
extern void F_FUNC_US(f90wrap_m_inheritance__t_inheritance_initialise,F90WRAP_M_INHERITANCE__T_INHERITANCE_INITIALISE)(int*);
extern void F_FUNC_US(f90wrap_m_inheritance__t_inheritance_finalise,F90WRAP_M_INHERITANCE__T_INHERITANCE_FINALISE)(int*);
extern void F_FUNC_US(f90wrap_m_fortran_module__a_subroutine,F90WRAP_M_FORTRAN_MODULE__A_SUBROUTINE)(int*);
extern void F_FUNC_US(f90wrap_m_fortran_module__b_subroutine,F90WRAP_M_FORTRAN_MODULE__B_SUBROUTINE)(int*);
extern void F_FUNC_US(f90wrap_m_fortran_module__c_subroutine,F90WRAP_M_FORTRAN_MODULE__C_SUBROUTINE)(int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/******************* f90wrap_t_base_type__get__real_number *******************/
static char doc_f2py_rout__pywrapper_f90wrap_t_base_type__get__real_number[] = "\
f90wrap_real_number = f90wrap_t_base_type__get__real_number(this)\n\nWrapper for ``f90wrap_t_base_type__get__real_number``.\
\n\nParameters\n----------\n"
"this : input rank-1 array('i') with bounds (4)\n"
"\nReturns\n-------\n"
"f90wrap_real_number : float";
/* extern void F_FUNC_US(f90wrap_t_base_type__get__real_number,F90WRAP_T_BASE_TYPE__GET__REAL_NUMBER)(int*,float*); */
static PyObject *f2py_rout__pywrapper_f90wrap_t_base_type__get__real_number(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_as_array = NULL;
    int capi_this_intent = 0;
    PyObject *this_capi = Py_None;
    float f90wrap_real_number = 0;
    static char *capi_kwlist[] = {"this",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:_pywrapper.f90wrap_t_base_type__get__real_number",\
        capi_kwlist,&this_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=4;
    capi_this_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_t_base_type__get__real_number: failed to create array from the 1st argument `this`";
    capi_this_as_array = ndarray_from_pyobj(  NPY_INT,1,this_Dims,this_Rank,  capi_this_intent,this_capi,capi_errmess);

    if (capi_this_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      this = (int *)(PyArray_DATA(capi_this_as_array));
    /* Processing variable f90wrap_real_number */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(this,&f90wrap_real_number);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("f",f90wrap_real_number);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable f90wrap_real_number */
    if((PyObject *)capi_this_as_array!=this_capi) {
        Py_XDECREF(capi_this_as_array); }
    }  /* if (capi_this_as_array == NULL) ... else of this */
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/**************** end of f90wrap_t_base_type__get__real_number ****************/

/******************* f90wrap_t_base_type__set__real_number *******************/
static char doc_f2py_rout__pywrapper_f90wrap_t_base_type__set__real_number[] = "\
f90wrap_t_base_type__set__real_number(this,f90wrap_real_number)\n\nWrapper for ``f90wrap_t_base_type__set__real_number``.\
\n\nParameters\n----------\n"
"this : input rank-1 array('i') with bounds (4)\n"
"f90wrap_real_number : input float";
/* extern void F_FUNC_US(f90wrap_t_base_type__set__real_number,F90WRAP_T_BASE_TYPE__SET__REAL_NUMBER)(int*,float*); */
static PyObject *f2py_rout__pywrapper_f90wrap_t_base_type__set__real_number(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_as_array = NULL;
    int capi_this_intent = 0;
    PyObject *this_capi = Py_None;
    float f90wrap_real_number = 0;
    PyObject *f90wrap_real_number_capi = Py_None;
    static char *capi_kwlist[] = {"this","f90wrap_real_number",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:_pywrapper.f90wrap_t_base_type__set__real_number",\
        capi_kwlist,&this_capi,&f90wrap_real_number_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=4;
    capi_this_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_t_base_type__set__real_number: failed to create array from the 1st argument `this`";
    capi_this_as_array = ndarray_from_pyobj(  NPY_INT,1,this_Dims,this_Rank,  capi_this_intent,this_capi,capi_errmess);

    if (capi_this_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      this = (int *)(PyArray_DATA(capi_this_as_array));
    /* Processing variable f90wrap_real_number */
        f2py_success = float_from_pyobj(&f90wrap_real_number,f90wrap_real_number_capi,"_pywrapper.f90wrap_t_base_type__set__real_number() 2nd argument (f90wrap_real_number) can't be converted to float");
    if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(this,&f90wrap_real_number);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*if (f2py_success) of f90wrap_real_number*/
    /* End of cleaning variable f90wrap_real_number */
    if((PyObject *)capi_this_as_array!=this_capi) {
        Py_XDECREF(capi_this_as_array); }
    }  /* if (capi_this_as_array == NULL) ... else of this */
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/**************** end of f90wrap_t_base_type__set__real_number ****************/

/**************** f90wrap_m_base_type__t_base_type_initialise ****************/
static char doc_f2py_rout__pywrapper_f90wrap_m_base_type__t_base_type_initialise[] = "\
this = f90wrap_m_base_type__t_base_type_initialise()\n\nWrapper for ``f90wrap_m_base_type__t_base_type_initialise``.\
\n\nReturns\n-------\n"
"this : rank-1 array('i') with bounds (4)";
/* extern void F_FUNC_US(f90wrap_m_base_type__t_base_type_initialise,F90WRAP_M_BASE_TYPE__T_BASE_TYPE_INITIALISE)(int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_base_type__t_base_type_initialise(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_as_array = NULL;
    int capi_this_intent = 0;
    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:_pywrapper.f90wrap_m_base_type__t_base_type_initialise",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=4;
    capi_this_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_base_type__t_base_type_initialise: failed to create array from the hidden `this`";
    capi_this_as_array = ndarray_from_pyobj(  NPY_INT,1,this_Dims,this_Rank,  capi_this_intent,Py_None,capi_errmess);

    if (capi_this_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      this = (int *)(PyArray_DATA(capi_this_as_array));
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(this);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_this_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_this_as_array == NULL) ... else of this */
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/************* end of f90wrap_m_base_type__t_base_type_initialise *************/

/***************** f90wrap_m_base_type__t_base_type_finalise *****************/
static char doc_f2py_rout__pywrapper_f90wrap_m_base_type__t_base_type_finalise[] = "\
f90wrap_m_base_type__t_base_type_finalise(this)\n\nWrapper for ``f90wrap_m_base_type__t_base_type_finalise``.\
\n\nParameters\n----------\n"
"this : input rank-1 array('i') with bounds (4)";
/* extern void F_FUNC_US(f90wrap_m_base_type__t_base_type_finalise,F90WRAP_M_BASE_TYPE__T_BASE_TYPE_FINALISE)(int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_base_type__t_base_type_finalise(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_as_array = NULL;
    int capi_this_intent = 0;
    PyObject *this_capi = Py_None;
    static char *capi_kwlist[] = {"this",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:_pywrapper.f90wrap_m_base_type__t_base_type_finalise",\
        capi_kwlist,&this_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=4;
    capi_this_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_base_type__t_base_type_finalise: failed to create array from the 1st argument `this`";
    capi_this_as_array = ndarray_from_pyobj(  NPY_INT,1,this_Dims,this_Rank,  capi_this_intent,this_capi,capi_errmess);

    if (capi_this_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      this = (int *)(PyArray_DATA(capi_this_as_array));
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(this);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_this_as_array!=this_capi) {
        Py_XDECREF(capi_this_as_array); }
    }  /* if (capi_this_as_array == NULL) ... else of this */
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/************** end of f90wrap_m_base_type__t_base_type_finalise **************/

/********************* f90wrap_t_composition__get__member *********************/
static char doc_f2py_rout__pywrapper_f90wrap_t_composition__get__member[] = "\
f90wrap_member = f90wrap_t_composition__get__member(this)\n\nWrapper for ``f90wrap_t_composition__get__member``.\
\n\nParameters\n----------\n"
"this : input rank-1 array('i') with bounds (4)\n"
"\nReturns\n-------\n"
"f90wrap_member : rank-1 array('i') with bounds (4)";
/* extern void F_FUNC_US(f90wrap_t_composition__get__member,F90WRAP_T_COMPOSITION__GET__MEMBER)(int*,int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_t_composition__get__member(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_as_array = NULL;
    int capi_this_intent = 0;
    PyObject *this_capi = Py_None;
    int *f90wrap_member = NULL;
    npy_intp f90wrap_member_Dims[1] = {-1};
    const int f90wrap_member_Rank = 1;
    PyArrayObject *capi_f90wrap_member_as_array = NULL;
    int capi_f90wrap_member_intent = 0;
    static char *capi_kwlist[] = {"this",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:_pywrapper.f90wrap_t_composition__get__member",\
        capi_kwlist,&this_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=4;
    capi_this_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_t_composition__get__member: failed to create array from the 1st argument `this`";
    capi_this_as_array = ndarray_from_pyobj(  NPY_INT,1,this_Dims,this_Rank,  capi_this_intent,this_capi,capi_errmess);

    if (capi_this_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      this = (int *)(PyArray_DATA(capi_this_as_array));
    /* Processing variable f90wrap_member */
    f90wrap_member_Dims[0]=4;
    capi_f90wrap_member_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_t_composition__get__member: failed to create array from the hidden `f90wrap_member`";
    capi_f90wrap_member_as_array = ndarray_from_pyobj(  NPY_INT,1,f90wrap_member_Dims,f90wrap_member_Rank,  capi_f90wrap_member_intent,Py_None,capi_errmess);

    if (capi_f90wrap_member_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      f90wrap_member = (int *)(PyArray_DATA(capi_f90wrap_member_as_array));
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(this,f90wrap_member);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_f90wrap_member_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_f90wrap_member_as_array == NULL) ... else of f90wrap_member */
    /* End of cleaning variable f90wrap_member */
    if((PyObject *)capi_this_as_array!=this_capi) {
        Py_XDECREF(capi_this_as_array); }
    }  /* if (capi_this_as_array == NULL) ... else of this */
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************** end of f90wrap_t_composition__get__member *****************/

/********************* f90wrap_t_composition__set__member *********************/
static char doc_f2py_rout__pywrapper_f90wrap_t_composition__set__member[] = "\
f90wrap_t_composition__set__member(this,f90wrap_member)\n\nWrapper for ``f90wrap_t_composition__set__member``.\
\n\nParameters\n----------\n"
"this : input rank-1 array('i') with bounds (4)\n"
"f90wrap_member : input rank-1 array('i') with bounds (4)";
/* extern void F_FUNC_US(f90wrap_t_composition__set__member,F90WRAP_T_COMPOSITION__SET__MEMBER)(int*,int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_t_composition__set__member(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_as_array = NULL;
    int capi_this_intent = 0;
    PyObject *this_capi = Py_None;
    int *f90wrap_member = NULL;
    npy_intp f90wrap_member_Dims[1] = {-1};
    const int f90wrap_member_Rank = 1;
    PyArrayObject *capi_f90wrap_member_as_array = NULL;
    int capi_f90wrap_member_intent = 0;
    PyObject *f90wrap_member_capi = Py_None;
    static char *capi_kwlist[] = {"this","f90wrap_member",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:_pywrapper.f90wrap_t_composition__set__member",\
        capi_kwlist,&this_capi,&f90wrap_member_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=4;
    capi_this_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_t_composition__set__member: failed to create array from the 1st argument `this`";
    capi_this_as_array = ndarray_from_pyobj(  NPY_INT,1,this_Dims,this_Rank,  capi_this_intent,this_capi,capi_errmess);

    if (capi_this_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      this = (int *)(PyArray_DATA(capi_this_as_array));
    /* Processing variable f90wrap_member */
    f90wrap_member_Dims[0]=4;
    capi_f90wrap_member_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_t_composition__set__member: failed to create array from the 2nd argument `f90wrap_member`";
    capi_f90wrap_member_as_array = ndarray_from_pyobj(  NPY_INT,1,f90wrap_member_Dims,f90wrap_member_Rank,  capi_f90wrap_member_intent,f90wrap_member_capi,capi_errmess);

    if (capi_f90wrap_member_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      f90wrap_member = (int *)(PyArray_DATA(capi_f90wrap_member_as_array));
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(this,f90wrap_member);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_f90wrap_member_as_array!=f90wrap_member_capi) {
        Py_XDECREF(capi_f90wrap_member_as_array); }
    }  /* if (capi_f90wrap_member_as_array == NULL) ... else of f90wrap_member */
    /* End of cleaning variable f90wrap_member */
    if((PyObject *)capi_this_as_array!=this_capi) {
        Py_XDECREF(capi_this_as_array); }
    }  /* if (capi_this_as_array == NULL) ... else of this */
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************** end of f90wrap_t_composition__set__member *****************/

/************** f90wrap_m_composition__t_composition_initialise **************/
static char doc_f2py_rout__pywrapper_f90wrap_m_composition__t_composition_initialise[] = "\
this = f90wrap_m_composition__t_composition_initialise()\n\nWrapper for ``f90wrap_m_composition__t_composition_initialise``.\
\n\nReturns\n-------\n"
"this : rank-1 array('i') with bounds (4)";
/* extern void F_FUNC_US(f90wrap_m_composition__t_composition_initialise,F90WRAP_M_COMPOSITION__T_COMPOSITION_INITIALISE)(int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_composition__t_composition_initialise(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_as_array = NULL;
    int capi_this_intent = 0;
    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:_pywrapper.f90wrap_m_composition__t_composition_initialise",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=4;
    capi_this_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_composition__t_composition_initialise: failed to create array from the hidden `this`";
    capi_this_as_array = ndarray_from_pyobj(  NPY_INT,1,this_Dims,this_Rank,  capi_this_intent,Py_None,capi_errmess);

    if (capi_this_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      this = (int *)(PyArray_DATA(capi_this_as_array));
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(this);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_this_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_this_as_array == NULL) ... else of this */
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*********** end of f90wrap_m_composition__t_composition_initialise ***********/

/*************** f90wrap_m_composition__t_composition_finalise ***************/
static char doc_f2py_rout__pywrapper_f90wrap_m_composition__t_composition_finalise[] = "\
f90wrap_m_composition__t_composition_finalise(this)\n\nWrapper for ``f90wrap_m_composition__t_composition_finalise``.\
\n\nParameters\n----------\n"
"this : input rank-1 array('i') with bounds (4)";
/* extern void F_FUNC_US(f90wrap_m_composition__t_composition_finalise,F90WRAP_M_COMPOSITION__T_COMPOSITION_FINALISE)(int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_composition__t_composition_finalise(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_as_array = NULL;
    int capi_this_intent = 0;
    PyObject *this_capi = Py_None;
    static char *capi_kwlist[] = {"this",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:_pywrapper.f90wrap_m_composition__t_composition_finalise",\
        capi_kwlist,&this_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=4;
    capi_this_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_composition__t_composition_finalise: failed to create array from the 1st argument `this`";
    capi_this_as_array = ndarray_from_pyobj(  NPY_INT,1,this_Dims,this_Rank,  capi_this_intent,this_capi,capi_errmess);

    if (capi_this_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      this = (int *)(PyArray_DATA(capi_this_as_array));
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(this);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_this_as_array!=this_capi) {
        Py_XDECREF(capi_this_as_array); }
    }  /* if (capi_this_as_array == NULL) ... else of this */
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/************ end of f90wrap_m_composition__t_composition_finalise ************/

/***************** f90wrap_t_inheritance__get__integer_number *****************/
static char doc_f2py_rout__pywrapper_f90wrap_t_inheritance__get__integer_number[] = "\
f90wrap_integer_number = f90wrap_t_inheritance__get__integer_number(this)\n\nWrapper for ``f90wrap_t_inheritance__get__integer_number``.\
\n\nParameters\n----------\n"
"this : input rank-1 array('i') with bounds (4)\n"
"\nReturns\n-------\n"
"f90wrap_integer_number : int";
/* extern void F_FUNC_US(f90wrap_t_inheritance__get__integer_number,F90WRAP_T_INHERITANCE__GET__INTEGER_NUMBER)(int*,int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_t_inheritance__get__integer_number(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_as_array = NULL;
    int capi_this_intent = 0;
    PyObject *this_capi = Py_None;
    int f90wrap_integer_number = 0;
    static char *capi_kwlist[] = {"this",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:_pywrapper.f90wrap_t_inheritance__get__integer_number",\
        capi_kwlist,&this_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=4;
    capi_this_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_t_inheritance__get__integer_number: failed to create array from the 1st argument `this`";
    capi_this_as_array = ndarray_from_pyobj(  NPY_INT,1,this_Dims,this_Rank,  capi_this_intent,this_capi,capi_errmess);

    if (capi_this_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      this = (int *)(PyArray_DATA(capi_this_as_array));
    /* Processing variable f90wrap_integer_number */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(this,&f90wrap_integer_number);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("i",f90wrap_integer_number);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable f90wrap_integer_number */
    if((PyObject *)capi_this_as_array!=this_capi) {
        Py_XDECREF(capi_this_as_array); }
    }  /* if (capi_this_as_array == NULL) ... else of this */
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/************* end of f90wrap_t_inheritance__get__integer_number *************/

/***************** f90wrap_t_inheritance__set__integer_number *****************/
static char doc_f2py_rout__pywrapper_f90wrap_t_inheritance__set__integer_number[] = "\
f90wrap_t_inheritance__set__integer_number(this,f90wrap_integer_number)\n\nWrapper for ``f90wrap_t_inheritance__set__integer_number``.\
\n\nParameters\n----------\n"
"this : input rank-1 array('i') with bounds (4)\n"
"f90wrap_integer_number : input int";
/* extern void F_FUNC_US(f90wrap_t_inheritance__set__integer_number,F90WRAP_T_INHERITANCE__SET__INTEGER_NUMBER)(int*,int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_t_inheritance__set__integer_number(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_as_array = NULL;
    int capi_this_intent = 0;
    PyObject *this_capi = Py_None;
    int f90wrap_integer_number = 0;
    PyObject *f90wrap_integer_number_capi = Py_None;
    static char *capi_kwlist[] = {"this","f90wrap_integer_number",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:_pywrapper.f90wrap_t_inheritance__set__integer_number",\
        capi_kwlist,&this_capi,&f90wrap_integer_number_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=4;
    capi_this_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_t_inheritance__set__integer_number: failed to create array from the 1st argument `this`";
    capi_this_as_array = ndarray_from_pyobj(  NPY_INT,1,this_Dims,this_Rank,  capi_this_intent,this_capi,capi_errmess);

    if (capi_this_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      this = (int *)(PyArray_DATA(capi_this_as_array));
    /* Processing variable f90wrap_integer_number */
        f2py_success = int_from_pyobj(&f90wrap_integer_number,f90wrap_integer_number_capi,"_pywrapper.f90wrap_t_inheritance__set__integer_number() 2nd argument (f90wrap_integer_number) can't be converted to int");
    if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(this,&f90wrap_integer_number);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*if (f2py_success) of f90wrap_integer_number*/
    /* End of cleaning variable f90wrap_integer_number */
    if((PyObject *)capi_this_as_array!=this_capi) {
        Py_XDECREF(capi_this_as_array); }
    }  /* if (capi_this_as_array == NULL) ... else of this */
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/************* end of f90wrap_t_inheritance__set__integer_number *************/

/************** f90wrap_m_inheritance__t_inheritance_initialise **************/
static char doc_f2py_rout__pywrapper_f90wrap_m_inheritance__t_inheritance_initialise[] = "\
this = f90wrap_m_inheritance__t_inheritance_initialise()\n\nWrapper for ``f90wrap_m_inheritance__t_inheritance_initialise``.\
\n\nReturns\n-------\n"
"this : rank-1 array('i') with bounds (4)";
/* extern void F_FUNC_US(f90wrap_m_inheritance__t_inheritance_initialise,F90WRAP_M_INHERITANCE__T_INHERITANCE_INITIALISE)(int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_inheritance__t_inheritance_initialise(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_as_array = NULL;
    int capi_this_intent = 0;
    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:_pywrapper.f90wrap_m_inheritance__t_inheritance_initialise",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=4;
    capi_this_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_inheritance__t_inheritance_initialise: failed to create array from the hidden `this`";
    capi_this_as_array = ndarray_from_pyobj(  NPY_INT,1,this_Dims,this_Rank,  capi_this_intent,Py_None,capi_errmess);

    if (capi_this_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      this = (int *)(PyArray_DATA(capi_this_as_array));
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(this);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_this_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_this_as_array == NULL) ... else of this */
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*********** end of f90wrap_m_inheritance__t_inheritance_initialise ***********/

/*************** f90wrap_m_inheritance__t_inheritance_finalise ***************/
static char doc_f2py_rout__pywrapper_f90wrap_m_inheritance__t_inheritance_finalise[] = "\
f90wrap_m_inheritance__t_inheritance_finalise(this)\n\nWrapper for ``f90wrap_m_inheritance__t_inheritance_finalise``.\
\n\nParameters\n----------\n"
"this : input rank-1 array('i') with bounds (4)";
/* extern void F_FUNC_US(f90wrap_m_inheritance__t_inheritance_finalise,F90WRAP_M_INHERITANCE__T_INHERITANCE_FINALISE)(int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_inheritance__t_inheritance_finalise(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_as_array = NULL;
    int capi_this_intent = 0;
    PyObject *this_capi = Py_None;
    static char *capi_kwlist[] = {"this",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:_pywrapper.f90wrap_m_inheritance__t_inheritance_finalise",\
        capi_kwlist,&this_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=4;
    capi_this_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_inheritance__t_inheritance_finalise: failed to create array from the 1st argument `this`";
    capi_this_as_array = ndarray_from_pyobj(  NPY_INT,1,this_Dims,this_Rank,  capi_this_intent,this_capi,capi_errmess);

    if (capi_this_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      this = (int *)(PyArray_DATA(capi_this_as_array));
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(this);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_this_as_array!=this_capi) {
        Py_XDECREF(capi_this_as_array); }
    }  /* if (capi_this_as_array == NULL) ... else of this */
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/************ end of f90wrap_m_inheritance__t_inheritance_finalise ************/

/******************* f90wrap_m_fortran_module__a_subroutine *******************/
static char doc_f2py_rout__pywrapper_f90wrap_m_fortran_module__a_subroutine[] = "\
f90wrap_m_fortran_module__a_subroutine(input)\n\nWrapper for ``f90wrap_m_fortran_module__a_subroutine``.\
\n\nParameters\n----------\n"
"input : input rank-1 array('i') with bounds (4)";
/* extern void F_FUNC_US(f90wrap_m_fortran_module__a_subroutine,F90WRAP_M_FORTRAN_MODULE__A_SUBROUTINE)(int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_fortran_module__a_subroutine(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *input = NULL;
    npy_intp input_Dims[1] = {-1};
    const int input_Rank = 1;
    PyArrayObject *capi_input_as_array = NULL;
    int capi_input_intent = 0;
    PyObject *input_capi = Py_None;
    static char *capi_kwlist[] = {"input",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:_pywrapper.f90wrap_m_fortran_module__a_subroutine",\
        capi_kwlist,&input_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable input */
    input_Dims[0]=4;
    capi_input_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_fortran_module__a_subroutine: failed to create array from the 1st argument `input`";
    capi_input_as_array = ndarray_from_pyobj(  NPY_INT,1,input_Dims,input_Rank,  capi_input_intent,input_capi,capi_errmess);

    if (capi_input_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      input = (int *)(PyArray_DATA(capi_input_as_array));
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(input);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_input_as_array!=input_capi) {
        Py_XDECREF(capi_input_as_array); }
    }  /* if (capi_input_as_array == NULL) ... else of input */
    /* End of cleaning variable input */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*************** end of f90wrap_m_fortran_module__a_subroutine ***************/

/******************* f90wrap_m_fortran_module__b_subroutine *******************/
static char doc_f2py_rout__pywrapper_f90wrap_m_fortran_module__b_subroutine[] = "\
f90wrap_m_fortran_module__b_subroutine(input)\n\nWrapper for ``f90wrap_m_fortran_module__b_subroutine``.\
\n\nParameters\n----------\n"
"input : input rank-1 array('i') with bounds (4)";
/* extern void F_FUNC_US(f90wrap_m_fortran_module__b_subroutine,F90WRAP_M_FORTRAN_MODULE__B_SUBROUTINE)(int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_fortran_module__b_subroutine(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *input = NULL;
    npy_intp input_Dims[1] = {-1};
    const int input_Rank = 1;
    PyArrayObject *capi_input_as_array = NULL;
    int capi_input_intent = 0;
    PyObject *input_capi = Py_None;
    static char *capi_kwlist[] = {"input",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:_pywrapper.f90wrap_m_fortran_module__b_subroutine",\
        capi_kwlist,&input_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable input */
    input_Dims[0]=4;
    capi_input_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_fortran_module__b_subroutine: failed to create array from the 1st argument `input`";
    capi_input_as_array = ndarray_from_pyobj(  NPY_INT,1,input_Dims,input_Rank,  capi_input_intent,input_capi,capi_errmess);

    if (capi_input_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      input = (int *)(PyArray_DATA(capi_input_as_array));
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(input);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_input_as_array!=input_capi) {
        Py_XDECREF(capi_input_as_array); }
    }  /* if (capi_input_as_array == NULL) ... else of input */
    /* End of cleaning variable input */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*************** end of f90wrap_m_fortran_module__b_subroutine ***************/

/******************* f90wrap_m_fortran_module__c_subroutine *******************/
static char doc_f2py_rout__pywrapper_f90wrap_m_fortran_module__c_subroutine[] = "\
f90wrap_m_fortran_module__c_subroutine(input)\n\nWrapper for ``f90wrap_m_fortran_module__c_subroutine``.\
\n\nParameters\n----------\n"
"input : input rank-1 array('i') with bounds (4)";
/* extern void F_FUNC_US(f90wrap_m_fortran_module__c_subroutine,F90WRAP_M_FORTRAN_MODULE__C_SUBROUTINE)(int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_fortran_module__c_subroutine(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *input = NULL;
    npy_intp input_Dims[1] = {-1};
    const int input_Rank = 1;
    PyArrayObject *capi_input_as_array = NULL;
    int capi_input_intent = 0;
    PyObject *input_capi = Py_None;
    static char *capi_kwlist[] = {"input",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:_pywrapper.f90wrap_m_fortran_module__c_subroutine",\
        capi_kwlist,&input_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable input */
    input_Dims[0]=4;
    capi_input_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_fortran_module__c_subroutine: failed to create array from the 1st argument `input`";
    capi_input_as_array = ndarray_from_pyobj(  NPY_INT,1,input_Dims,input_Rank,  capi_input_intent,input_capi,capi_errmess);

    if (capi_input_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      input = (int *)(PyArray_DATA(capi_input_as_array));
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(input);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_input_as_array!=input_capi) {
        Py_XDECREF(capi_input_as_array); }
    }  /* if (capi_input_as_array == NULL) ... else of input */
    /* End of cleaning variable input */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*************** end of f90wrap_m_fortran_module__c_subroutine ***************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"f90wrap_t_base_type__get__real_number",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_t_base_type__get__real_number,F90WRAP_T_BASE_TYPE__GET__REAL_NUMBER),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_t_base_type__get__real_number,doc_f2py_rout__pywrapper_f90wrap_t_base_type__get__real_number},
    {"f90wrap_t_base_type__set__real_number",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_t_base_type__set__real_number,F90WRAP_T_BASE_TYPE__SET__REAL_NUMBER),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_t_base_type__set__real_number,doc_f2py_rout__pywrapper_f90wrap_t_base_type__set__real_number},
    {"f90wrap_m_base_type__t_base_type_initialise",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_base_type__t_base_type_initialise,F90WRAP_M_BASE_TYPE__T_BASE_TYPE_INITIALISE),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_base_type__t_base_type_initialise,doc_f2py_rout__pywrapper_f90wrap_m_base_type__t_base_type_initialise},
    {"f90wrap_m_base_type__t_base_type_finalise",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_base_type__t_base_type_finalise,F90WRAP_M_BASE_TYPE__T_BASE_TYPE_FINALISE),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_base_type__t_base_type_finalise,doc_f2py_rout__pywrapper_f90wrap_m_base_type__t_base_type_finalise},
    {"f90wrap_t_composition__get__member",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_t_composition__get__member,F90WRAP_T_COMPOSITION__GET__MEMBER),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_t_composition__get__member,doc_f2py_rout__pywrapper_f90wrap_t_composition__get__member},
    {"f90wrap_t_composition__set__member",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_t_composition__set__member,F90WRAP_T_COMPOSITION__SET__MEMBER),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_t_composition__set__member,doc_f2py_rout__pywrapper_f90wrap_t_composition__set__member},
    {"f90wrap_m_composition__t_composition_initialise",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_composition__t_composition_initialise,F90WRAP_M_COMPOSITION__T_COMPOSITION_INITIALISE),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_composition__t_composition_initialise,doc_f2py_rout__pywrapper_f90wrap_m_composition__t_composition_initialise},
    {"f90wrap_m_composition__t_composition_finalise",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_composition__t_composition_finalise,F90WRAP_M_COMPOSITION__T_COMPOSITION_FINALISE),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_composition__t_composition_finalise,doc_f2py_rout__pywrapper_f90wrap_m_composition__t_composition_finalise},
    {"f90wrap_t_inheritance__get__integer_number",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_t_inheritance__get__integer_number,F90WRAP_T_INHERITANCE__GET__INTEGER_NUMBER),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_t_inheritance__get__integer_number,doc_f2py_rout__pywrapper_f90wrap_t_inheritance__get__integer_number},
    {"f90wrap_t_inheritance__set__integer_number",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_t_inheritance__set__integer_number,F90WRAP_T_INHERITANCE__SET__INTEGER_NUMBER),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_t_inheritance__set__integer_number,doc_f2py_rout__pywrapper_f90wrap_t_inheritance__set__integer_number},
    {"f90wrap_m_inheritance__t_inheritance_initialise",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_inheritance__t_inheritance_initialise,F90WRAP_M_INHERITANCE__T_INHERITANCE_INITIALISE),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_inheritance__t_inheritance_initialise,doc_f2py_rout__pywrapper_f90wrap_m_inheritance__t_inheritance_initialise},
    {"f90wrap_m_inheritance__t_inheritance_finalise",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_inheritance__t_inheritance_finalise,F90WRAP_M_INHERITANCE__T_INHERITANCE_FINALISE),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_inheritance__t_inheritance_finalise,doc_f2py_rout__pywrapper_f90wrap_m_inheritance__t_inheritance_finalise},
    {"f90wrap_m_fortran_module__a_subroutine",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_fortran_module__a_subroutine,F90WRAP_M_FORTRAN_MODULE__A_SUBROUTINE),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_fortran_module__a_subroutine,doc_f2py_rout__pywrapper_f90wrap_m_fortran_module__a_subroutine},
    {"f90wrap_m_fortran_module__b_subroutine",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_fortran_module__b_subroutine,F90WRAP_M_FORTRAN_MODULE__B_SUBROUTINE),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_fortran_module__b_subroutine,doc_f2py_rout__pywrapper_f90wrap_m_fortran_module__b_subroutine},
    {"f90wrap_m_fortran_module__c_subroutine",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_fortran_module__c_subroutine,F90WRAP_M_FORTRAN_MODULE__C_SUBROUTINE),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_fortran_module__c_subroutine,doc_f2py_rout__pywrapper_f90wrap_m_fortran_module__c_subroutine},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "_pywrapper",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit__pywrapper(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = _pywrapper_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module _pywrapper (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("2.3.3");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module '_pywrapper' is auto-generated with f2py (version:2.3.3).\nFunctions:\n"
"    f90wrap_real_number = f90wrap_t_base_type__get__real_number(this)\n"
"    f90wrap_t_base_type__set__real_number(this,f90wrap_real_number)\n"
"    this = f90wrap_m_base_type__t_base_type_initialise()\n"
"    f90wrap_m_base_type__t_base_type_finalise(this)\n"
"    f90wrap_member = f90wrap_t_composition__get__member(this)\n"
"    f90wrap_t_composition__set__member(this,f90wrap_member)\n"
"    this = f90wrap_m_composition__t_composition_initialise()\n"
"    f90wrap_m_composition__t_composition_finalise(this)\n"
"    f90wrap_integer_number = f90wrap_t_inheritance__get__integer_number(this)\n"
"    f90wrap_t_inheritance__set__integer_number(this,f90wrap_integer_number)\n"
"    this = f90wrap_m_inheritance__t_inheritance_initialise()\n"
"    f90wrap_m_inheritance__t_inheritance_finalise(this)\n"
"    f90wrap_m_fortran_module__a_subroutine(input)\n"
"    f90wrap_m_fortran_module__b_subroutine(input)\n"
"    f90wrap_m_fortran_module__c_subroutine(input)\n"
".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("2.3.3");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    _pywrapper_error = PyErr_NewException ("_pywrapper.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "__pywrapper_error", _pywrapper_error);
    Py_DECREF(_pywrapper_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }















/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#if Py_GIL_DISABLED
    // signal whether this module supports running with the GIL disabled
    PyUnstable_Module_SetGIL(m , Py_MOD_GIL_USED);
#endif

#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"_pywrapper");
#endif

    if (PyType_Ready(&PyFortran_Type) < 0) {
        return NULL;
    }

    return m;
}
#ifdef __cplusplus
}
#endif
