/* File: _pywrappermodule.c
 * This file is auto-generated with f2py (version:2.3.3).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Tue Oct 21 20:19:20 2025
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
/*need_includes0*/


    /* custom abort handler - James Kermode <james.kermode@gmail.com> */
    #include <signal.h>
#include <setjmp.h>

    #define ABORT_BUFFER_SIZE 1024
    extern jmp_buf environment_buffer;
    extern char abort_message[ABORT_BUFFER_SIZE];
    void f90wrap_abort_(char *message, int len);
    void f90wrap_abort_int_handler(int signum);

    #include <stdlib.h>
    #include <string.h>

    jmp_buf environment_buffer;
    char abort_message[ABORT_BUFFER_SIZE];

    void f90wrap_abort_(char *message, int len_message)
    {
      strncpy(abort_message, message, ABORT_BUFFER_SIZE);
      abort_message[ABORT_BUFFER_SIZE-1] = '\0';
      longjmp(environment_buffer, 0);
    }

    // copy of f90wrap_abort_ with a second underscore
    // void (*f90wrap_abort__)(char *, int) = &f90wrap_abort_;
    void f90wrap_abort__(char *message, int len_message)
    {
      strncpy(abort_message, message, ABORT_BUFFER_SIZE);
      abort_message[ABORT_BUFFER_SIZE-1] = '\0';
      longjmp(environment_buffer, 0);
    }


    void f90wrap_abort_int_handler(int signum)
    {
      char message[] = "Interrupt occured";
      f90wrap_abort_(message, strlen(message));
    }

    /* end of custom abort handler  */
    
/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *_pywrapper_error;
static PyObject *_pywrapper_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif


#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/

static int
double_from_pyobj(double* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
        *v = PyFloat_AsDouble(obj);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    tmp = PyNumber_Float(obj);
    if (tmp) {
        *v = PyFloat_AsDouble(tmp);
        Py_DECREF(tmp);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = _pywrapper_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


static int
float_from_pyobj(float* v, PyObject *obj, const char *errmess)
{
    double d=0.0;
    if (double_from_pyobj(&d,obj,errmess)) {
        *v = (float)d;
        return 1;
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(f90wrap_m_test__test_real,F90WRAP_M_TEST__TEST_REAL)(float*,int*);
extern void F_FUNC_US(f90wrap_m_test__test_real4,F90WRAP_M_TEST__TEST_REAL4)(float*,int*);
extern void F_FUNC_US(f90wrap_m_test__test_real8,F90WRAP_M_TEST__TEST_REAL8)(double*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/************************* f90wrap_m_test__test_real *************************/
static char doc_f2py_rout__pywrapper_f90wrap_m_test__test_real[] = "\
ret_out_int = f90wrap_m_test__test_real(in_real)\n\nWrapper for ``f90wrap_m_test__test_real``.\
\n\nParameters\n----------\n"
"in_real : input float\n"
"\nReturns\n-------\n"
"ret_out_int : int";
/* extern void F_FUNC_US(f90wrap_m_test__test_real,F90WRAP_M_TEST__TEST_REAL)(float*,int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_test__test_real(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    float in_real = 0;
    PyObject *in_real_capi = Py_None;
    int ret_out_int = 0;
    static char *capi_kwlist[] = {"in_real",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:_pywrapper.f90wrap_m_test__test_real",\
        capi_kwlist,&in_real_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable in_real */
        f2py_success = float_from_pyobj(&in_real,in_real_capi,"_pywrapper.f90wrap_m_test__test_real() 1st argument (in_real) can't be converted to float");
    if (f2py_success) {
    /* Processing variable ret_out_int */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(&in_real,&ret_out_int);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("i",ret_out_int);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable ret_out_int */
    } /*if (f2py_success) of in_real*/
    /* End of cleaning variable in_real */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/********************** end of f90wrap_m_test__test_real **********************/

/************************* f90wrap_m_test__test_real4 *************************/
static char doc_f2py_rout__pywrapper_f90wrap_m_test__test_real4[] = "\
ret_out_int = f90wrap_m_test__test_real4(in_real)\n\nWrapper for ``f90wrap_m_test__test_real4``.\
\n\nParameters\n----------\n"
"in_real : input float\n"
"\nReturns\n-------\n"
"ret_out_int : int";
/* extern void F_FUNC_US(f90wrap_m_test__test_real4,F90WRAP_M_TEST__TEST_REAL4)(float*,int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_test__test_real4(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    float in_real = 0;
    PyObject *in_real_capi = Py_None;
    int ret_out_int = 0;
    static char *capi_kwlist[] = {"in_real",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:_pywrapper.f90wrap_m_test__test_real4",\
        capi_kwlist,&in_real_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable in_real */
        f2py_success = float_from_pyobj(&in_real,in_real_capi,"_pywrapper.f90wrap_m_test__test_real4() 1st argument (in_real) can't be converted to float");
    if (f2py_success) {
    /* Processing variable ret_out_int */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(&in_real,&ret_out_int);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("i",ret_out_int);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable ret_out_int */
    } /*if (f2py_success) of in_real*/
    /* End of cleaning variable in_real */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/********************* end of f90wrap_m_test__test_real4 *********************/

/************************* f90wrap_m_test__test_real8 *************************/
static char doc_f2py_rout__pywrapper_f90wrap_m_test__test_real8[] = "\
ret_out_int = f90wrap_m_test__test_real8(in_real)\n\nWrapper for ``f90wrap_m_test__test_real8``.\
\n\nParameters\n----------\n"
"in_real : input float\n"
"\nReturns\n-------\n"
"ret_out_int : int";
/* extern void F_FUNC_US(f90wrap_m_test__test_real8,F90WRAP_M_TEST__TEST_REAL8)(double*,int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_test__test_real8(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    double in_real = 0;
    PyObject *in_real_capi = Py_None;
    int ret_out_int = 0;
    static char *capi_kwlist[] = {"in_real",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:_pywrapper.f90wrap_m_test__test_real8",\
        capi_kwlist,&in_real_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable in_real */
        f2py_success = double_from_pyobj(&in_real,in_real_capi,"_pywrapper.f90wrap_m_test__test_real8() 1st argument (in_real) can't be converted to double");
    if (f2py_success) {
    /* Processing variable ret_out_int */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(&in_real,&ret_out_int);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("i",ret_out_int);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable ret_out_int */
    } /*if (f2py_success) of in_real*/
    /* End of cleaning variable in_real */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/********************* end of f90wrap_m_test__test_real8 *********************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"f90wrap_m_test__test_real",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_test__test_real,F90WRAP_M_TEST__TEST_REAL),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_test__test_real,doc_f2py_rout__pywrapper_f90wrap_m_test__test_real},
    {"f90wrap_m_test__test_real4",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_test__test_real4,F90WRAP_M_TEST__TEST_REAL4),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_test__test_real4,doc_f2py_rout__pywrapper_f90wrap_m_test__test_real4},
    {"f90wrap_m_test__test_real8",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_test__test_real8,F90WRAP_M_TEST__TEST_REAL8),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_test__test_real8,doc_f2py_rout__pywrapper_f90wrap_m_test__test_real8},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "_pywrapper",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit__pywrapper(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = _pywrapper_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module _pywrapper (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("2.3.3");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module '_pywrapper' is auto-generated with f2py (version:2.3.3).\nFunctions:\n"
"    ret_out_int = f90wrap_m_test__test_real(in_real)\n"
"    ret_out_int = f90wrap_m_test__test_real4(in_real)\n"
"    ret_out_int = f90wrap_m_test__test_real8(in_real)\n"
".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("2.3.3");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    _pywrapper_error = PyErr_NewException ("_pywrapper.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "__pywrapper_error", _pywrapper_error);
    Py_DECREF(_pywrapper_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }



/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#if Py_GIL_DISABLED
    // signal whether this module supports running with the GIL disabled
    PyUnstable_Module_SetGIL(m , Py_MOD_GIL_USED);
#endif

#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"_pywrapper");
#endif

    if (PyType_Ready(&PyFortran_Type) < 0) {
        return NULL;
    }

    return m;
}
#ifdef __cplusplus
}
#endif
