/* File: _pywrappermodule.c
 * This file is auto-generated with f2py (version:2.3.3).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Tue Oct 21 20:19:35 2025
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
/*need_includes0*/


    /* custom abort handler - James Kermode <james.kermode@gmail.com> */
    #include <signal.h>
#include <setjmp.h>

    #define ABORT_BUFFER_SIZE 1024
    extern jmp_buf environment_buffer;
    extern char abort_message[ABORT_BUFFER_SIZE];
    void f90wrap_abort_(char *message, int len);
    void f90wrap_abort_int_handler(int signum);

    #include <stdlib.h>
    #include <string.h>

    jmp_buf environment_buffer;
    char abort_message[ABORT_BUFFER_SIZE];

    void f90wrap_abort_(char *message, int len_message)
    {
      strncpy(abort_message, message, ABORT_BUFFER_SIZE);
      abort_message[ABORT_BUFFER_SIZE-1] = '\0';
      longjmp(environment_buffer, 0);
    }

    // copy of f90wrap_abort_ with a second underscore
    // void (*f90wrap_abort__)(char *, int) = &f90wrap_abort_;
    void f90wrap_abort__(char *message, int len_message)
    {
      strncpy(abort_message, message, ABORT_BUFFER_SIZE);
      abort_message[ABORT_BUFFER_SIZE-1] = '\0';
      longjmp(environment_buffer, 0);
    }


    void f90wrap_abort_int_handler(int signum)
    {
      char message[] = "Interrupt occured";
      f90wrap_abort_(message, strlen(message));
    }

    /* end of custom abort handler  */
    
/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *_pywrapper_error;
static PyObject *_pywrapper_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/

#if defined(NPY_OS_WIN32)
typedef __int64 long_long;
#else
typedef long long long_long;
typedef unsigned long long unsigned_long_long;
#endif


/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/* See fortranobject.h for definitions. The macros here are provided for BC. */
#define rank f2py_rank
#define shape f2py_shape
#define fshape f2py_shape
#define len f2py_len
#define flen f2py_flen
#define slen f2py_slen
#define size f2py_size


#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif


#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/

static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = _pywrapper_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(f90wrap_array__array__buffer,F90WRAP_ARRAY__ARRAY__BUFFER)(int*,int*,int*,int*,long_long*);
extern void F_FUNC_US(f90wrap_array__get__array_size,F90WRAP_ARRAY__GET__ARRAY_SIZE)(int*,int*);
extern void F_FUNC_US(f90wrap_array__set__array_size,F90WRAP_ARRAY__SET__ARRAY_SIZE)(int*,int*);
extern void F_FUNC_US(f90wrap_m_array__array_initialise,F90WRAP_M_ARRAY__ARRAY_INITIALISE)(int*);
extern void F_FUNC_US(f90wrap_m_array__array_finalise,F90WRAP_M_ARRAY__ARRAY_FINALISE)(int*);
extern void F_FUNC_US(f90wrap_m_array__init__binding__array,F90WRAP_M_ARRAY__INIT__BINDING__ARRAY)(int*,int*);
extern void F_FUNC_US(f90wrap_m_array__init_optional__binding__array,F90WRAP_M_ARRAY__INIT_OPTIONAL__BINDING__ARRAY)(int*,int*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/************************ f90wrap_array__array__buffer ************************/
static char doc_f2py_rout__pywrapper_f90wrap_array__array__buffer[] = "\
nd,dtype,dshape,dloc = f90wrap_array__array__buffer(this)\n\nWrapper for ``f90wrap_array__array__buffer``.\
\n\nParameters\n----------\n"
"this : input rank-1 array('i') with bounds (4)\n"
"\nReturns\n-------\n"
"nd : int\n"
"dtype : int\n"
"dshape : rank-1 array('i') with bounds (10)\n"
"dloc : long";
/* extern void F_FUNC_US(f90wrap_array__array__buffer,F90WRAP_ARRAY__ARRAY__BUFFER)(int*,int*,int*,int*,long_long*); */
static PyObject *f2py_rout__pywrapper_f90wrap_array__array__buffer(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,long_long*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_as_array = NULL;
    int capi_this_intent = 0;
    PyObject *this_capi = Py_None;
    int nd = 0;
    int dtype = 0;
    int *dshape = NULL;
    npy_intp dshape_Dims[1] = {-1};
    const int dshape_Rank = 1;
    PyArrayObject *capi_dshape_as_array = NULL;
    int capi_dshape_intent = 0;
    long_long dloc = 0;
    static char *capi_kwlist[] = {"this",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:_pywrapper.f90wrap_array__array__buffer",\
        capi_kwlist,&this_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=4;
    capi_this_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_array__array__buffer: failed to create array from the 1st argument `this`";
    capi_this_as_array = ndarray_from_pyobj(  NPY_INT,1,this_Dims,this_Rank,  capi_this_intent,this_capi,capi_errmess);

    if (capi_this_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      this = (int *)(PyArray_DATA(capi_this_as_array));
    /* Processing variable nd */
    /* Processing variable dtype */
    /* Processing variable dshape */
    dshape_Dims[0]=10;
    capi_dshape_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_array__array__buffer: failed to create array from the hidden `dshape`";
    capi_dshape_as_array = ndarray_from_pyobj(  NPY_INT,1,dshape_Dims,dshape_Rank,  capi_dshape_intent,Py_None,capi_errmess);

    if (capi_dshape_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      dshape = (int *)(PyArray_DATA(capi_dshape_as_array));
    /* Processing variable dloc */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(this,&nd,&dtype,dshape,&dloc);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("iiNL",nd,dtype,capi_dshape_as_array,dloc);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable dloc */
    }  /* if (capi_dshape_as_array == NULL) ... else of dshape */
    /* End of cleaning variable dshape */
    /* End of cleaning variable dtype */
    /* End of cleaning variable nd */
    if((PyObject *)capi_this_as_array!=this_capi) {
        Py_XDECREF(capi_this_as_array); }
    }  /* if (capi_this_as_array == NULL) ... else of this */
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************** end of f90wrap_array__array__buffer ********************/

/*********************** f90wrap_array__get__array_size ***********************/
static char doc_f2py_rout__pywrapper_f90wrap_array__get__array_size[] = "\
f90wrap_array_size = f90wrap_array__get__array_size(this)\n\nWrapper for ``f90wrap_array__get__array_size``.\
\n\nParameters\n----------\n"
"this : input rank-1 array('i') with bounds (4)\n"
"\nReturns\n-------\n"
"f90wrap_array_size : int";
/* extern void F_FUNC_US(f90wrap_array__get__array_size,F90WRAP_ARRAY__GET__ARRAY_SIZE)(int*,int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_array__get__array_size(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_as_array = NULL;
    int capi_this_intent = 0;
    PyObject *this_capi = Py_None;
    int f90wrap_array_size = 0;
    static char *capi_kwlist[] = {"this",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:_pywrapper.f90wrap_array__get__array_size",\
        capi_kwlist,&this_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=4;
    capi_this_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_array__get__array_size: failed to create array from the 1st argument `this`";
    capi_this_as_array = ndarray_from_pyobj(  NPY_INT,1,this_Dims,this_Rank,  capi_this_intent,this_capi,capi_errmess);

    if (capi_this_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      this = (int *)(PyArray_DATA(capi_this_as_array));
    /* Processing variable f90wrap_array_size */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(this,&f90wrap_array_size);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("i",f90wrap_array_size);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable f90wrap_array_size */
    if((PyObject *)capi_this_as_array!=this_capi) {
        Py_XDECREF(capi_this_as_array); }
    }  /* if (capi_this_as_array == NULL) ... else of this */
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************* end of f90wrap_array__get__array_size *******************/

/*********************** f90wrap_array__set__array_size ***********************/
static char doc_f2py_rout__pywrapper_f90wrap_array__set__array_size[] = "\
f90wrap_array__set__array_size(this,f90wrap_array_size)\n\nWrapper for ``f90wrap_array__set__array_size``.\
\n\nParameters\n----------\n"
"this : input rank-1 array('i') with bounds (4)\n"
"f90wrap_array_size : input int";
/* extern void F_FUNC_US(f90wrap_array__set__array_size,F90WRAP_ARRAY__SET__ARRAY_SIZE)(int*,int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_array__set__array_size(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_as_array = NULL;
    int capi_this_intent = 0;
    PyObject *this_capi = Py_None;
    int f90wrap_array_size = 0;
    PyObject *f90wrap_array_size_capi = Py_None;
    static char *capi_kwlist[] = {"this","f90wrap_array_size",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:_pywrapper.f90wrap_array__set__array_size",\
        capi_kwlist,&this_capi,&f90wrap_array_size_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=4;
    capi_this_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_array__set__array_size: failed to create array from the 1st argument `this`";
    capi_this_as_array = ndarray_from_pyobj(  NPY_INT,1,this_Dims,this_Rank,  capi_this_intent,this_capi,capi_errmess);

    if (capi_this_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      this = (int *)(PyArray_DATA(capi_this_as_array));
    /* Processing variable f90wrap_array_size */
        f2py_success = int_from_pyobj(&f90wrap_array_size,f90wrap_array_size_capi,"_pywrapper.f90wrap_array__set__array_size() 2nd argument (f90wrap_array_size) can't be converted to int");
    if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(this,&f90wrap_array_size);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*if (f2py_success) of f90wrap_array_size*/
    /* End of cleaning variable f90wrap_array_size */
    if((PyObject *)capi_this_as_array!=this_capi) {
        Py_XDECREF(capi_this_as_array); }
    }  /* if (capi_this_as_array == NULL) ... else of this */
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************* end of f90wrap_array__set__array_size *******************/

/********************* f90wrap_m_array__array_initialise *********************/
static char doc_f2py_rout__pywrapper_f90wrap_m_array__array_initialise[] = "\
this = f90wrap_m_array__array_initialise()\n\nWrapper for ``f90wrap_m_array__array_initialise``.\
\n\nReturns\n-------\n"
"this : rank-1 array('i') with bounds (4)";
/* extern void F_FUNC_US(f90wrap_m_array__array_initialise,F90WRAP_M_ARRAY__ARRAY_INITIALISE)(int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_array__array_initialise(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_as_array = NULL;
    int capi_this_intent = 0;
    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:_pywrapper.f90wrap_m_array__array_initialise",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=4;
    capi_this_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_array__array_initialise: failed to create array from the hidden `this`";
    capi_this_as_array = ndarray_from_pyobj(  NPY_INT,1,this_Dims,this_Rank,  capi_this_intent,Py_None,capi_errmess);

    if (capi_this_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      this = (int *)(PyArray_DATA(capi_this_as_array));
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(this);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_this_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_this_as_array == NULL) ... else of this */
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************** end of f90wrap_m_array__array_initialise ******************/

/********************** f90wrap_m_array__array_finalise **********************/
static char doc_f2py_rout__pywrapper_f90wrap_m_array__array_finalise[] = "\
f90wrap_m_array__array_finalise(this)\n\nWrapper for ``f90wrap_m_array__array_finalise``.\
\n\nParameters\n----------\n"
"this : input rank-1 array('i') with bounds (4)";
/* extern void F_FUNC_US(f90wrap_m_array__array_finalise,F90WRAP_M_ARRAY__ARRAY_FINALISE)(int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_array__array_finalise(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_as_array = NULL;
    int capi_this_intent = 0;
    PyObject *this_capi = Py_None;
    static char *capi_kwlist[] = {"this",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:_pywrapper.f90wrap_m_array__array_finalise",\
        capi_kwlist,&this_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=4;
    capi_this_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_array__array_finalise: failed to create array from the 1st argument `this`";
    capi_this_as_array = ndarray_from_pyobj(  NPY_INT,1,this_Dims,this_Rank,  capi_this_intent,this_capi,capi_errmess);

    if (capi_this_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      this = (int *)(PyArray_DATA(capi_this_as_array));
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(this);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_this_as_array!=this_capi) {
        Py_XDECREF(capi_this_as_array); }
    }  /* if (capi_this_as_array == NULL) ... else of this */
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************* end of f90wrap_m_array__array_finalise *******************/

/******************* f90wrap_m_array__init__binding__array *******************/
static char doc_f2py_rout__pywrapper_f90wrap_m_array__init__binding__array[] = "\
f90wrap_m_array__init__binding__array(this,n)\n\nWrapper for ``f90wrap_m_array__init__binding__array``.\
\n\nParameters\n----------\n"
"this : input rank-1 array('i') with bounds (4)\n"
"n : input int";
/* extern void F_FUNC_US(f90wrap_m_array__init__binding__array,F90WRAP_M_ARRAY__INIT__BINDING__ARRAY)(int*,int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_array__init__binding__array(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_as_array = NULL;
    int capi_this_intent = 0;
    PyObject *this_capi = Py_None;
    int n = 0;
    PyObject *n_capi = Py_None;
    static char *capi_kwlist[] = {"this","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:_pywrapper.f90wrap_m_array__init__binding__array",\
        capi_kwlist,&this_capi,&n_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=4;
    capi_this_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_array__init__binding__array: failed to create array from the 1st argument `this`";
    capi_this_as_array = ndarray_from_pyobj(  NPY_INT,1,this_Dims,this_Rank,  capi_this_intent,this_capi,capi_errmess);

    if (capi_this_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      this = (int *)(PyArray_DATA(capi_this_as_array));
    /* Processing variable n */
        f2py_success = int_from_pyobj(&n,n_capi,"_pywrapper.f90wrap_m_array__init__binding__array() 2nd argument (n) can't be converted to int");
    if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(this,&n);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*if (f2py_success) of n*/
    /* End of cleaning variable n */
    if((PyObject *)capi_this_as_array!=this_capi) {
        Py_XDECREF(capi_this_as_array); }
    }  /* if (capi_this_as_array == NULL) ... else of this */
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/**************** end of f90wrap_m_array__init__binding__array ****************/

/*************** f90wrap_m_array__init_optional__binding__array ***************/
static char doc_f2py_rout__pywrapper_f90wrap_m_array__init_optional__binding__array[] = "\
f90wrap_m_array__init_optional__binding__array(this,n,[optional_arg])\n\nWrapper for ``f90wrap_m_array__init_optional__binding__array``.\
\n\nParameters\n----------\n"
"this : input rank-1 array('i') with bounds (4)\n"
"n : input int\n"
"\nOther Parameters\n----------------\n"
"optional_arg : input rank-1 array('i') with bounds (4)";
/* extern void F_FUNC_US(f90wrap_m_array__init_optional__binding__array,F90WRAP_M_ARRAY__INIT_OPTIONAL__BINDING__ARRAY)(int*,int*,int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_array__init_optional__binding__array(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_as_array = NULL;
    int capi_this_intent = 0;
    PyObject *this_capi = Py_None;
    int n = 0;
    PyObject *n_capi = Py_None;
    int *optional_arg = NULL;
    npy_intp optional_arg_Dims[1] = {-1};
    const int optional_arg_Rank = 1;
    PyArrayObject *capi_optional_arg_as_array = NULL;
    int capi_optional_arg_intent = 0;
    PyObject *optional_arg_capi = Py_None;
    static char *capi_kwlist[] = {"this","n","optional_arg",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|O:_pywrapper.f90wrap_m_array__init_optional__binding__array",\
        capi_kwlist,&this_capi,&n_capi,&optional_arg_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=4;
    capi_this_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_array__init_optional__binding__array: failed to create array from the 1st argument `this`";
    capi_this_as_array = ndarray_from_pyobj(  NPY_INT,1,this_Dims,this_Rank,  capi_this_intent,this_capi,capi_errmess);

    if (capi_this_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      this = (int *)(PyArray_DATA(capi_this_as_array));
    /* Processing variable n */
        f2py_success = int_from_pyobj(&n,n_capi,"_pywrapper.f90wrap_m_array__init_optional__binding__array() 2nd argument (n) can't be converted to int");
    if (f2py_success) {
    /* Processing variable optional_arg */
    optional_arg_Dims[0]=4;
    capi_optional_arg_intent |= F2PY_INTENT_IN|F2PY_OPTIONAL;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_array__init_optional__binding__array: failed to create array from the 1st keyword `optional_arg`";
  if (optional_arg_capi != Py_None) {
    capi_optional_arg_as_array = ndarray_from_pyobj(  NPY_INT,1,optional_arg_Dims,optional_arg_Rank,  capi_optional_arg_intent,optional_arg_capi,capi_errmess);
  }

    if (optional_arg_capi != Py_None && capi_optional_arg_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      if (optional_arg_capi != Py_None) optional_arg = (int *)(PyArray_DATA(capi_optional_arg_as_array));
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(this,&n,optional_arg_capi == Py_None ? NULL : optional_arg);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_optional_arg_as_array!=optional_arg_capi) {
        Py_XDECREF(capi_optional_arg_as_array); }
    }  /* if (capi_optional_arg_as_array == NULL) ... else of optional_arg */
    /* End of cleaning variable optional_arg */
    } /*if (f2py_success) of n*/
    /* End of cleaning variable n */
    if((PyObject *)capi_this_as_array!=this_capi) {
        Py_XDECREF(capi_this_as_array); }
    }  /* if (capi_this_as_array == NULL) ... else of this */
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*********** end of f90wrap_m_array__init_optional__binding__array ***********/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"f90wrap_array__array__buffer",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_array__array__buffer,F90WRAP_ARRAY__ARRAY__BUFFER),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_array__array__buffer,doc_f2py_rout__pywrapper_f90wrap_array__array__buffer},
    {"f90wrap_array__get__array_size",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_array__get__array_size,F90WRAP_ARRAY__GET__ARRAY_SIZE),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_array__get__array_size,doc_f2py_rout__pywrapper_f90wrap_array__get__array_size},
    {"f90wrap_array__set__array_size",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_array__set__array_size,F90WRAP_ARRAY__SET__ARRAY_SIZE),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_array__set__array_size,doc_f2py_rout__pywrapper_f90wrap_array__set__array_size},
    {"f90wrap_m_array__array_initialise",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_array__array_initialise,F90WRAP_M_ARRAY__ARRAY_INITIALISE),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_array__array_initialise,doc_f2py_rout__pywrapper_f90wrap_m_array__array_initialise},
    {"f90wrap_m_array__array_finalise",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_array__array_finalise,F90WRAP_M_ARRAY__ARRAY_FINALISE),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_array__array_finalise,doc_f2py_rout__pywrapper_f90wrap_m_array__array_finalise},
    {"f90wrap_m_array__init__binding__array",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_array__init__binding__array,F90WRAP_M_ARRAY__INIT__BINDING__ARRAY),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_array__init__binding__array,doc_f2py_rout__pywrapper_f90wrap_m_array__init__binding__array},
    {"f90wrap_m_array__init_optional__binding__array",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_array__init_optional__binding__array,F90WRAP_M_ARRAY__INIT_OPTIONAL__BINDING__ARRAY),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_array__init_optional__binding__array,doc_f2py_rout__pywrapper_f90wrap_m_array__init_optional__binding__array},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "_pywrapper",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit__pywrapper(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = _pywrapper_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module _pywrapper (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("2.3.3");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module '_pywrapper' is auto-generated with f2py (version:2.3.3).\nFunctions:\n"
"    nd,dtype,dshape,dloc = f90wrap_array__array__buffer(this)\n"
"    f90wrap_array_size = f90wrap_array__get__array_size(this)\n"
"    f90wrap_array__set__array_size(this,f90wrap_array_size)\n"
"    this = f90wrap_m_array__array_initialise()\n"
"    f90wrap_m_array__array_finalise(this)\n"
"    f90wrap_m_array__init__binding__array(this,n)\n"
"    f90wrap_m_array__init_optional__binding__array(this,n,optional_arg=)\n"
".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("2.3.3");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    _pywrapper_error = PyErr_NewException ("_pywrapper.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "__pywrapper_error", _pywrapper_error);
    Py_DECREF(_pywrapper_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }







/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#if Py_GIL_DISABLED
    // signal whether this module supports running with the GIL disabled
    PyUnstable_Module_SetGIL(m , Py_MOD_GIL_USED);
#endif

#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"_pywrapper");
#endif

    if (PyType_Ready(&PyFortran_Type) < 0) {
        return NULL;
    }

    return m;
}
#ifdef __cplusplus
}
#endif
