! Fortran support module for direct C wrappers
! Auto-generated by f90wrap

module f90wrap__type_bn_fixed_support

    use module_structure
    use iso_c_binding
    implicit none

contains

    subroutine f90wrap_type_face__allocate(ptr) bind(C, name='__module_structure_MOD_f90wrap_type_face__allocate')
        type(c_ptr), intent(out) :: ptr
        type(type_face), pointer :: fptr

        allocate(fptr)
        ptr = c_loc(fptr)
    end subroutine f90wrap_type_face__allocate

    subroutine f90wrap_type_face__deallocate(ptr) bind(C, name='__module_structure_MOD_f90wrap_type_face__deallocate')
        type(c_ptr), intent(inout) :: ptr
        type(type_face), pointer :: fptr

        if (c_associated(ptr)) then
            call c_f_pointer(ptr, fptr)
            deallocate(fptr)
            ptr = c_null_ptr
        end if
    end subroutine f90wrap_type_face__deallocate

    subroutine type_face_initialise(self, this) bind(C, name='__module_structure_MOD_type_face_initialise')
        type(c_ptr), value :: self
        type(c_ptr), intent(out) :: this

        ! Default initialization (Fortran handles this automatically)
        ! Just return the same pointer
        this = self
    end subroutine type_face_initialise

    subroutine type_face_finalise(self, this) bind(C, name='__module_structure_MOD_type_face_finalise')
        type(c_ptr), value :: self
        type(c_ptr), intent(inout) :: this

        ! Default finalization (cleanup happens at deallocation)
        ! Return the same pointer
        this = self
    end subroutine type_face_finalise

    subroutine f90wrap_type_face__get__type_bn(self_ptr, value) bind(C, name='__module_structure_MOD_f90wrap_type_face__get__type_bn')
        type(c_ptr), value :: self_ptr
        integer , intent(out) :: value
        type(type_face), pointer :: self

        call c_f_pointer(self_ptr, self)
        value = self%type
    end subroutine f90wrap_type_face__get__type_bn

    subroutine f90wrap_type_face__set__type_bn(self_ptr, value) bind(C, name='__module_structure_MOD_f90wrap_type_face__set__type_bn')
        type(c_ptr), value :: self_ptr
        integer , intent(in) :: value
        type(type_face), pointer :: self

        call c_f_pointer(self_ptr, self)
        self%type = value
    end subroutine f90wrap_type_face__set__type_bn

end module f90wrap__type_bn_fixed_support
