/* File: _pywrappermodule.c
 * This file is auto-generated with f2py (version:2.3.3).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Tue Oct 21 20:19:18 2025
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
/*need_includes0*/


    /* custom abort handler - James Kermode <james.kermode@gmail.com> */
    #include <signal.h>
#include <setjmp.h>

    #define ABORT_BUFFER_SIZE 1024
    extern jmp_buf environment_buffer;
    extern char abort_message[ABORT_BUFFER_SIZE];
    void f90wrap_abort_(char *message, int len);
    void f90wrap_abort_int_handler(int signum);

    #include <stdlib.h>
    #include <string.h>

    jmp_buf environment_buffer;
    char abort_message[ABORT_BUFFER_SIZE];

    void f90wrap_abort_(char *message, int len_message)
    {
      strncpy(abort_message, message, ABORT_BUFFER_SIZE);
      abort_message[ABORT_BUFFER_SIZE-1] = '\0';
      longjmp(environment_buffer, 0);
    }

    // copy of f90wrap_abort_ with a second underscore
    // void (*f90wrap_abort__)(char *, int) = &f90wrap_abort_;
    void f90wrap_abort__(char *message, int len_message)
    {
      strncpy(abort_message, message, ABORT_BUFFER_SIZE);
      abort_message[ABORT_BUFFER_SIZE-1] = '\0';
      longjmp(environment_buffer, 0);
    }


    void f90wrap_abort_int_handler(int signum)
    {
      char message[] = "Interrupt occured";
      f90wrap_abort_(message, strlen(message));
    }

    /* end of custom abort handler  */
    
/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *_pywrapper_error;
static PyObject *_pywrapper_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/

#if defined(NPY_OS_WIN32)
typedef __int64 long_long;
#else
typedef long long long_long;
typedef unsigned long long unsigned_long_long;
#endif


/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/* See fortranobject.h for definitions. The macros here are provided for BC. */
#define rank f2py_rank
#define shape f2py_shape
#define fshape f2py_shape
#define len f2py_len
#define flen f2py_flen
#define slen f2py_slen
#define size f2py_size


#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif


#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/

static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = _pywrapper_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(f90wrap_m_long_subroutine_name_type__get__m_long_subroutine0485,F90WRAP_M_LONG_SUBROUTINE_NAME_TYPE__GET__M_LONG_SUBROUTINE0485)(int*,int*);
extern void F_FUNC_US(f90wrap_m_long_subroutine_name_type__set__m_long_subroutine7044,F90WRAP_M_LONG_SUBROUTINE_NAME_TYPE__SET__M_LONG_SUBROUTINE7044)(int*,int*);
extern void F_FUNC_US(f90wrap_m_long_subroutine_name_type__array__m_long_subrouti6cde,F90WRAP_M_LONG_SUBROUTINE_NAME_TYPE__ARRAY__M_LONG_SUBROUTI6CDE)(int*,int*,int*,int*,long_long*);
extern void F_FUNC_US(f90wrap_m_long_subroutine_name__m_long_subroutine_name_typefcc3,F90WRAP_M_LONG_SUBROUTINE_NAME__M_LONG_SUBROUTINE_NAME_TYPEFCC3)(int*);
extern void F_FUNC_US(f90wrap_m_long_subroutine_name__m_long_subroutine_name_type6ffd,F90WRAP_M_LONG_SUBROUTINE_NAME__M_LONG_SUBROUTINE_NAME_TYPE6FFD)(int*);
extern void F_FUNC_US(f90wrap_m_long_subroutine_name_type_2__array_getitem__m_lonf40c,F90WRAP_M_LONG_SUBROUTINE_NAME_TYPE_2__ARRAY_GETITEM__M_LONF40C)(int*,int*,int*);
extern void F_FUNC_US(f90wrap_m_long_subroutine_name_type_2__array_setitem__m_lonc291,F90WRAP_M_LONG_SUBROUTINE_NAME_TYPE_2__ARRAY_SETITEM__M_LONC291)(int*,int*,int*);
extern void F_FUNC_US(f90wrap_m_long_subroutine_name_type_2__array_len__m_long_su541d,F90WRAP_M_LONG_SUBROUTINE_NAME_TYPE_2__ARRAY_LEN__M_LONG_SU541D)(int*,int*);
extern void F_FUNC_US(f90wrap_m_long_subroutine_name__m_long_subroutine_name_typebe6a,F90WRAP_M_LONG_SUBROUTINE_NAME__M_LONG_SUBROUTINE_NAME_TYPEBE6A)(int*);
extern void F_FUNC_US(f90wrap_m_long_subroutine_name__m_long_subroutine_name_type1fc3,F90WRAP_M_LONG_SUBROUTINE_NAME__M_LONG_SUBROUTINE_NAME_TYPE1FC3)(int*);
extern void F_FUNC_US(f90wrap_m_long_subroutine_name__m_long_subroutine_name_subra0ea,F90WRAP_M_LONG_SUBROUTINE_NAME__M_LONG_SUBROUTINE_NAME_SUBRA0EA)(void);
extern void F_FUNC_US(f90wrap_m_long_subroutine_name__get__m_long_subroutine_namebc01,F90WRAP_M_LONG_SUBROUTINE_NAME__GET__M_LONG_SUBROUTINE_NAMEBC01)(int*);
extern void F_FUNC_US(f90wrap_m_long_subroutine_name__set__m_long_subroutine_name860c,F90WRAP_M_LONG_SUBROUTINE_NAME__SET__M_LONG_SUBROUTINE_NAME860C)(int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/****** f90wrap_m_long_subroutine_name_type__get__m_long_subroutine0485 ******/
static char doc_f2py_rout__pywrapper_f90wrap_m_long_subroutine_name_type__get__m_long_subroutine0485[] = "\
f90wrap_m_long_subroutine_name_type_integer = f90wrap_m_long_subroutine_name_type__get__m_long_subroutine0485(this)\n\nWrapper for ``f90wrap_m_long_subroutine_name_type__get__m_long_subroutine0485``.\
\n\nParameters\n----------\n"
"this : input rank-1 array('i') with bounds (4)\n"
"\nReturns\n-------\n"
"f90wrap_m_long_subroutine_name_type_integer : int";
/* extern void F_FUNC_US(f90wrap_m_long_subroutine_name_type__get__m_long_subroutine0485,F90WRAP_M_LONG_SUBROUTINE_NAME_TYPE__GET__M_LONG_SUBROUTINE0485)(int*,int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_long_subroutine_name_type__get__m_long_subroutine0485(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_as_array = NULL;
    int capi_this_intent = 0;
    PyObject *this_capi = Py_None;
    int f90wrap_m_long_subroutine_name_type_integer = 0;
    static char *capi_kwlist[] = {"this",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:_pywrapper.f90wrap_m_long_subroutine_name_type__get__m_long_subroutine0485",\
        capi_kwlist,&this_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=4;
    capi_this_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_long_subroutine_name_type__get__m_long_subroutine0485: failed to create array from the 1st argument `this`";
    capi_this_as_array = ndarray_from_pyobj(  NPY_INT,1,this_Dims,this_Rank,  capi_this_intent,this_capi,capi_errmess);

    if (capi_this_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      this = (int *)(PyArray_DATA(capi_this_as_array));
    /* Processing variable f90wrap_m_long_subroutine_name_type_integer */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(this,&f90wrap_m_long_subroutine_name_type_integer);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("i",f90wrap_m_long_subroutine_name_type_integer);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable f90wrap_m_long_subroutine_name_type_integer */
    if((PyObject *)capi_this_as_array!=this_capi) {
        Py_XDECREF(capi_this_as_array); }
    }  /* if (capi_this_as_array == NULL) ... else of this */
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*** end of f90wrap_m_long_subroutine_name_type__get__m_long_subroutine0485 ***/

/****** f90wrap_m_long_subroutine_name_type__set__m_long_subroutine7044 ******/
static char doc_f2py_rout__pywrapper_f90wrap_m_long_subroutine_name_type__set__m_long_subroutine7044[] = "\
f90wrap_m_long_subroutine_name_type__set__m_long_subroutine7044(this,f90wrap_m_long_subroutine_name_type_integer)\n\nWrapper for ``f90wrap_m_long_subroutine_name_type__set__m_long_subroutine7044``.\
\n\nParameters\n----------\n"
"this : input rank-1 array('i') with bounds (4)\n"
"f90wrap_m_long_subroutine_name_type_integer : input int";
/* extern void F_FUNC_US(f90wrap_m_long_subroutine_name_type__set__m_long_subroutine7044,F90WRAP_M_LONG_SUBROUTINE_NAME_TYPE__SET__M_LONG_SUBROUTINE7044)(int*,int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_long_subroutine_name_type__set__m_long_subroutine7044(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_as_array = NULL;
    int capi_this_intent = 0;
    PyObject *this_capi = Py_None;
    int f90wrap_m_long_subroutine_name_type_integer = 0;
    PyObject *f90wrap_m_long_subroutine_name_type_integer_capi = Py_None;
    static char *capi_kwlist[] = {"this","f90wrap_m_long_subroutine_name_type_integer",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:_pywrapper.f90wrap_m_long_subroutine_name_type__set__m_long_subroutine7044",\
        capi_kwlist,&this_capi,&f90wrap_m_long_subroutine_name_type_integer_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=4;
    capi_this_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_long_subroutine_name_type__set__m_long_subroutine7044: failed to create array from the 1st argument `this`";
    capi_this_as_array = ndarray_from_pyobj(  NPY_INT,1,this_Dims,this_Rank,  capi_this_intent,this_capi,capi_errmess);

    if (capi_this_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      this = (int *)(PyArray_DATA(capi_this_as_array));
    /* Processing variable f90wrap_m_long_subroutine_name_type_integer */
        f2py_success = int_from_pyobj(&f90wrap_m_long_subroutine_name_type_integer,f90wrap_m_long_subroutine_name_type_integer_capi,"_pywrapper.f90wrap_m_long_subroutine_name_type__set__m_long_subroutine7044() 2nd argument (f90wrap_m_long_subroutine_name_type_integer) can't be converted to int");
    if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(this,&f90wrap_m_long_subroutine_name_type_integer);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*if (f2py_success) of f90wrap_m_long_subroutine_name_type_integer*/
    /* End of cleaning variable f90wrap_m_long_subroutine_name_type_integer */
    if((PyObject *)capi_this_as_array!=this_capi) {
        Py_XDECREF(capi_this_as_array); }
    }  /* if (capi_this_as_array == NULL) ... else of this */
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*** end of f90wrap_m_long_subroutine_name_type__set__m_long_subroutine7044 ***/

/****** f90wrap_m_long_subroutine_name_type__array__m_long_subrouti6cde ******/
static char doc_f2py_rout__pywrapper_f90wrap_m_long_subroutine_name_type__array__m_long_subrouti6cde[] = "\
nd,dtype,dshape,dloc = f90wrap_m_long_subroutine_name_type__array__m_long_subrouti6cde(this)\n\nWrapper for ``f90wrap_m_long_subroutine_name_type__array__m_long_subrouti6cde``.\
\n\nParameters\n----------\n"
"this : input rank-1 array('i') with bounds (4)\n"
"\nReturns\n-------\n"
"nd : int\n"
"dtype : int\n"
"dshape : rank-1 array('i') with bounds (10)\n"
"dloc : long";
/* extern void F_FUNC_US(f90wrap_m_long_subroutine_name_type__array__m_long_subrouti6cde,F90WRAP_M_LONG_SUBROUTINE_NAME_TYPE__ARRAY__M_LONG_SUBROUTI6CDE)(int*,int*,int*,int*,long_long*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_long_subroutine_name_type__array__m_long_subrouti6cde(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,long_long*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_as_array = NULL;
    int capi_this_intent = 0;
    PyObject *this_capi = Py_None;
    int nd = 0;
    int dtype = 0;
    int *dshape = NULL;
    npy_intp dshape_Dims[1] = {-1};
    const int dshape_Rank = 1;
    PyArrayObject *capi_dshape_as_array = NULL;
    int capi_dshape_intent = 0;
    long_long dloc = 0;
    static char *capi_kwlist[] = {"this",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:_pywrapper.f90wrap_m_long_subroutine_name_type__array__m_long_subrouti6cde",\
        capi_kwlist,&this_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=4;
    capi_this_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_long_subroutine_name_type__array__m_long_subrouti6cde: failed to create array from the 1st argument `this`";
    capi_this_as_array = ndarray_from_pyobj(  NPY_INT,1,this_Dims,this_Rank,  capi_this_intent,this_capi,capi_errmess);

    if (capi_this_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      this = (int *)(PyArray_DATA(capi_this_as_array));
    /* Processing variable nd */
    /* Processing variable dtype */
    /* Processing variable dshape */
    dshape_Dims[0]=10;
    capi_dshape_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_long_subroutine_name_type__array__m_long_subrouti6cde: failed to create array from the hidden `dshape`";
    capi_dshape_as_array = ndarray_from_pyobj(  NPY_INT,1,dshape_Dims,dshape_Rank,  capi_dshape_intent,Py_None,capi_errmess);

    if (capi_dshape_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      dshape = (int *)(PyArray_DATA(capi_dshape_as_array));
    /* Processing variable dloc */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(this,&nd,&dtype,dshape,&dloc);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("iiNL",nd,dtype,capi_dshape_as_array,dloc);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable dloc */
    }  /* if (capi_dshape_as_array == NULL) ... else of dshape */
    /* End of cleaning variable dshape */
    /* End of cleaning variable dtype */
    /* End of cleaning variable nd */
    if((PyObject *)capi_this_as_array!=this_capi) {
        Py_XDECREF(capi_this_as_array); }
    }  /* if (capi_this_as_array == NULL) ... else of this */
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*** end of f90wrap_m_long_subroutine_name_type__array__m_long_subrouti6cde ***/

/****** f90wrap_m_long_subroutine_name__m_long_subroutine_name_typefcc3 ******/
static char doc_f2py_rout__pywrapper_f90wrap_m_long_subroutine_name__m_long_subroutine_name_typefcc3[] = "\
this = f90wrap_m_long_subroutine_name__m_long_subroutine_name_typefcc3()\n\nWrapper for ``f90wrap_m_long_subroutine_name__m_long_subroutine_name_typefcc3``.\
\n\nReturns\n-------\n"
"this : rank-1 array('i') with bounds (4)";
/* extern void F_FUNC_US(f90wrap_m_long_subroutine_name__m_long_subroutine_name_typefcc3,F90WRAP_M_LONG_SUBROUTINE_NAME__M_LONG_SUBROUTINE_NAME_TYPEFCC3)(int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_long_subroutine_name__m_long_subroutine_name_typefcc3(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_as_array = NULL;
    int capi_this_intent = 0;
    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:_pywrapper.f90wrap_m_long_subroutine_name__m_long_subroutine_name_typefcc3",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=4;
    capi_this_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_long_subroutine_name__m_long_subroutine_name_typefcc3: failed to create array from the hidden `this`";
    capi_this_as_array = ndarray_from_pyobj(  NPY_INT,1,this_Dims,this_Rank,  capi_this_intent,Py_None,capi_errmess);

    if (capi_this_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      this = (int *)(PyArray_DATA(capi_this_as_array));
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(this);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_this_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_this_as_array == NULL) ... else of this */
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*** end of f90wrap_m_long_subroutine_name__m_long_subroutine_name_typefcc3 ***/

/****** f90wrap_m_long_subroutine_name__m_long_subroutine_name_type6ffd ******/
static char doc_f2py_rout__pywrapper_f90wrap_m_long_subroutine_name__m_long_subroutine_name_type6ffd[] = "\
f90wrap_m_long_subroutine_name__m_long_subroutine_name_type6ffd(this)\n\nWrapper for ``f90wrap_m_long_subroutine_name__m_long_subroutine_name_type6ffd``.\
\n\nParameters\n----------\n"
"this : input rank-1 array('i') with bounds (4)";
/* extern void F_FUNC_US(f90wrap_m_long_subroutine_name__m_long_subroutine_name_type6ffd,F90WRAP_M_LONG_SUBROUTINE_NAME__M_LONG_SUBROUTINE_NAME_TYPE6FFD)(int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_long_subroutine_name__m_long_subroutine_name_type6ffd(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_as_array = NULL;
    int capi_this_intent = 0;
    PyObject *this_capi = Py_None;
    static char *capi_kwlist[] = {"this",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:_pywrapper.f90wrap_m_long_subroutine_name__m_long_subroutine_name_type6ffd",\
        capi_kwlist,&this_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=4;
    capi_this_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_long_subroutine_name__m_long_subroutine_name_type6ffd: failed to create array from the 1st argument `this`";
    capi_this_as_array = ndarray_from_pyobj(  NPY_INT,1,this_Dims,this_Rank,  capi_this_intent,this_capi,capi_errmess);

    if (capi_this_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      this = (int *)(PyArray_DATA(capi_this_as_array));
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(this);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_this_as_array!=this_capi) {
        Py_XDECREF(capi_this_as_array); }
    }  /* if (capi_this_as_array == NULL) ... else of this */
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*** end of f90wrap_m_long_subroutine_name__m_long_subroutine_name_type6ffd ***/

/****** f90wrap_m_long_subroutine_name_type_2__array_getitem__m_lonf40c ******/
static char doc_f2py_rout__pywrapper_f90wrap_m_long_subroutine_name_type_2__array_getitem__m_lonf40c[] = "\
m_long_subroutine_name_type_2_type_arrayitem = f90wrap_m_long_subroutine_name_type_2__array_getitem__m_lonf40c(f90wrap_this,f90wrap_i)\n\nWrapper for ``f90wrap_m_long_subroutine_name_type_2__array_getitem__m_lonf40c``.\
\n\nParameters\n----------\n"
"f90wrap_this : input rank-1 array('i') with bounds (4)\n"
"f90wrap_i : input int\n"
"\nReturns\n-------\n"
"m_long_subroutine_name_type_2_type_arrayitem : rank-1 array('i') with bounds (4)";
/* extern void F_FUNC_US(f90wrap_m_long_subroutine_name_type_2__array_getitem__m_lonf40c,F90WRAP_M_LONG_SUBROUTINE_NAME_TYPE_2__ARRAY_GETITEM__M_LONF40C)(int*,int*,int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_long_subroutine_name_type_2__array_getitem__m_lonf40c(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *f90wrap_this = NULL;
    npy_intp f90wrap_this_Dims[1] = {-1};
    const int f90wrap_this_Rank = 1;
    PyArrayObject *capi_f90wrap_this_as_array = NULL;
    int capi_f90wrap_this_intent = 0;
    PyObject *f90wrap_this_capi = Py_None;
    int f90wrap_i = 0;
    PyObject *f90wrap_i_capi = Py_None;
    int *m_long_subroutine_name_type_2_type_arrayitem = NULL;
    npy_intp m_long_subroutine_name_type_2_type_arrayitem_Dims[1] = {-1};
    const int m_long_subroutine_name_type_2_type_arrayitem_Rank = 1;
    PyArrayObject *capi_m_long_subroutine_name_type_2_type_arrayitem_as_array = NULL;
    int capi_m_long_subroutine_name_type_2_type_arrayitem_intent = 0;
    static char *capi_kwlist[] = {"f90wrap_this","f90wrap_i",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:_pywrapper.f90wrap_m_long_subroutine_name_type_2__array_getitem__m_lonf40c",\
        capi_kwlist,&f90wrap_this_capi,&f90wrap_i_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable f90wrap_this */
    f90wrap_this_Dims[0]=4;
    capi_f90wrap_this_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_long_subroutine_name_type_2__array_getitem__m_lonf40c: failed to create array from the 1st argument `f90wrap_this`";
    capi_f90wrap_this_as_array = ndarray_from_pyobj(  NPY_INT,1,f90wrap_this_Dims,f90wrap_this_Rank,  capi_f90wrap_this_intent,f90wrap_this_capi,capi_errmess);

    if (capi_f90wrap_this_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      f90wrap_this = (int *)(PyArray_DATA(capi_f90wrap_this_as_array));
    /* Processing variable f90wrap_i */
        f2py_success = int_from_pyobj(&f90wrap_i,f90wrap_i_capi,"_pywrapper.f90wrap_m_long_subroutine_name_type_2__array_getitem__m_lonf40c() 2nd argument (f90wrap_i) can't be converted to int");
    if (f2py_success) {
    /* Processing variable m_long_subroutine_name_type_2_type_arrayitem */
    m_long_subroutine_name_type_2_type_arrayitem_Dims[0]=4;
    capi_m_long_subroutine_name_type_2_type_arrayitem_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_long_subroutine_name_type_2__array_getitem__m_lonf40c: failed to create array from the hidden `m_long_subroutine_name_type_2_type_arrayitem`";
    capi_m_long_subroutine_name_type_2_type_arrayitem_as_array = ndarray_from_pyobj(  NPY_INT,1,m_long_subroutine_name_type_2_type_arrayitem_Dims,m_long_subroutine_name_type_2_type_arrayitem_Rank,  capi_m_long_subroutine_name_type_2_type_arrayitem_intent,Py_None,capi_errmess);

    if (capi_m_long_subroutine_name_type_2_type_arrayitem_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      m_long_subroutine_name_type_2_type_arrayitem = (int *)(PyArray_DATA(capi_m_long_subroutine_name_type_2_type_arrayitem_as_array));
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(f90wrap_this,&f90wrap_i,m_long_subroutine_name_type_2_type_arrayitem);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_m_long_subroutine_name_type_2_type_arrayitem_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_m_long_subroutine_name_type_2_type_arrayitem_as_array == NULL) ... else of m_long_subroutine_name_type_2_type_arrayitem */
    /* End of cleaning variable m_long_subroutine_name_type_2_type_arrayitem */
    } /*if (f2py_success) of f90wrap_i*/
    /* End of cleaning variable f90wrap_i */
    if((PyObject *)capi_f90wrap_this_as_array!=f90wrap_this_capi) {
        Py_XDECREF(capi_f90wrap_this_as_array); }
    }  /* if (capi_f90wrap_this_as_array == NULL) ... else of f90wrap_this */
    /* End of cleaning variable f90wrap_this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*** end of f90wrap_m_long_subroutine_name_type_2__array_getitem__m_lonf40c ***/

/****** f90wrap_m_long_subroutine_name_type_2__array_setitem__m_lonc291 ******/
static char doc_f2py_rout__pywrapper_f90wrap_m_long_subroutine_name_type_2__array_setitem__m_lonc291[] = "\
f90wrap_m_long_subroutine_name_type_2__array_setitem__m_lonc291(f90wrap_this,f90wrap_i,m_long_subroutine_name_type_2_type_arrayitem)\n\nWrapper for ``f90wrap_m_long_subroutine_name_type_2__array_setitem__m_lonc291``.\
\n\nParameters\n----------\n"
"f90wrap_this : input rank-1 array('i') with bounds (4)\n"
"f90wrap_i : input int\n"
"m_long_subroutine_name_type_2_type_arrayitem : input rank-1 array('i') with bounds (4)";
/* extern void F_FUNC_US(f90wrap_m_long_subroutine_name_type_2__array_setitem__m_lonc291,F90WRAP_M_LONG_SUBROUTINE_NAME_TYPE_2__ARRAY_SETITEM__M_LONC291)(int*,int*,int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_long_subroutine_name_type_2__array_setitem__m_lonc291(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *f90wrap_this = NULL;
    npy_intp f90wrap_this_Dims[1] = {-1};
    const int f90wrap_this_Rank = 1;
    PyArrayObject *capi_f90wrap_this_as_array = NULL;
    int capi_f90wrap_this_intent = 0;
    PyObject *f90wrap_this_capi = Py_None;
    int f90wrap_i = 0;
    PyObject *f90wrap_i_capi = Py_None;
    int *m_long_subroutine_name_type_2_type_arrayitem = NULL;
    npy_intp m_long_subroutine_name_type_2_type_arrayitem_Dims[1] = {-1};
    const int m_long_subroutine_name_type_2_type_arrayitem_Rank = 1;
    PyArrayObject *capi_m_long_subroutine_name_type_2_type_arrayitem_as_array = NULL;
    int capi_m_long_subroutine_name_type_2_type_arrayitem_intent = 0;
    PyObject *m_long_subroutine_name_type_2_type_arrayitem_capi = Py_None;
    static char *capi_kwlist[] = {"f90wrap_this","f90wrap_i","m_long_subroutine_name_type_2_type_arrayitem",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOO|:_pywrapper.f90wrap_m_long_subroutine_name_type_2__array_setitem__m_lonc291",\
        capi_kwlist,&f90wrap_this_capi,&f90wrap_i_capi,&m_long_subroutine_name_type_2_type_arrayitem_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable f90wrap_this */
    f90wrap_this_Dims[0]=4;
    capi_f90wrap_this_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_long_subroutine_name_type_2__array_setitem__m_lonc291: failed to create array from the 1st argument `f90wrap_this`";
    capi_f90wrap_this_as_array = ndarray_from_pyobj(  NPY_INT,1,f90wrap_this_Dims,f90wrap_this_Rank,  capi_f90wrap_this_intent,f90wrap_this_capi,capi_errmess);

    if (capi_f90wrap_this_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      f90wrap_this = (int *)(PyArray_DATA(capi_f90wrap_this_as_array));
    /* Processing variable f90wrap_i */
        f2py_success = int_from_pyobj(&f90wrap_i,f90wrap_i_capi,"_pywrapper.f90wrap_m_long_subroutine_name_type_2__array_setitem__m_lonc291() 2nd argument (f90wrap_i) can't be converted to int");
    if (f2py_success) {
    /* Processing variable m_long_subroutine_name_type_2_type_arrayitem */
    m_long_subroutine_name_type_2_type_arrayitem_Dims[0]=4;
    capi_m_long_subroutine_name_type_2_type_arrayitem_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_long_subroutine_name_type_2__array_setitem__m_lonc291: failed to create array from the 3rd argument `m_long_subroutine_name_type_2_type_arrayitem`";
    capi_m_long_subroutine_name_type_2_type_arrayitem_as_array = ndarray_from_pyobj(  NPY_INT,1,m_long_subroutine_name_type_2_type_arrayitem_Dims,m_long_subroutine_name_type_2_type_arrayitem_Rank,  capi_m_long_subroutine_name_type_2_type_arrayitem_intent,m_long_subroutine_name_type_2_type_arrayitem_capi,capi_errmess);

    if (capi_m_long_subroutine_name_type_2_type_arrayitem_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      m_long_subroutine_name_type_2_type_arrayitem = (int *)(PyArray_DATA(capi_m_long_subroutine_name_type_2_type_arrayitem_as_array));
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(f90wrap_this,&f90wrap_i,m_long_subroutine_name_type_2_type_arrayitem);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_m_long_subroutine_name_type_2_type_arrayitem_as_array!=m_long_subroutine_name_type_2_type_arrayitem_capi) {
        Py_XDECREF(capi_m_long_subroutine_name_type_2_type_arrayitem_as_array); }
    }  /* if (capi_m_long_subroutine_name_type_2_type_arrayitem_as_array == NULL) ... else of m_long_subroutine_name_type_2_type_arrayitem */
    /* End of cleaning variable m_long_subroutine_name_type_2_type_arrayitem */
    } /*if (f2py_success) of f90wrap_i*/
    /* End of cleaning variable f90wrap_i */
    if((PyObject *)capi_f90wrap_this_as_array!=f90wrap_this_capi) {
        Py_XDECREF(capi_f90wrap_this_as_array); }
    }  /* if (capi_f90wrap_this_as_array == NULL) ... else of f90wrap_this */
    /* End of cleaning variable f90wrap_this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*** end of f90wrap_m_long_subroutine_name_type_2__array_setitem__m_lonc291 ***/

/****** f90wrap_m_long_subroutine_name_type_2__array_len__m_long_su541d ******/
static char doc_f2py_rout__pywrapper_f90wrap_m_long_subroutine_name_type_2__array_len__m_long_su541d[] = "\
f90wrap_n = f90wrap_m_long_subroutine_name_type_2__array_len__m_long_su541d(f90wrap_this)\n\nWrapper for ``f90wrap_m_long_subroutine_name_type_2__array_len__m_long_su541d``.\
\n\nParameters\n----------\n"
"f90wrap_this : input rank-1 array('i') with bounds (4)\n"
"\nReturns\n-------\n"
"f90wrap_n : int";
/* extern void F_FUNC_US(f90wrap_m_long_subroutine_name_type_2__array_len__m_long_su541d,F90WRAP_M_LONG_SUBROUTINE_NAME_TYPE_2__ARRAY_LEN__M_LONG_SU541D)(int*,int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_long_subroutine_name_type_2__array_len__m_long_su541d(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *f90wrap_this = NULL;
    npy_intp f90wrap_this_Dims[1] = {-1};
    const int f90wrap_this_Rank = 1;
    PyArrayObject *capi_f90wrap_this_as_array = NULL;
    int capi_f90wrap_this_intent = 0;
    PyObject *f90wrap_this_capi = Py_None;
    int f90wrap_n = 0;
    static char *capi_kwlist[] = {"f90wrap_this",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:_pywrapper.f90wrap_m_long_subroutine_name_type_2__array_len__m_long_su541d",\
        capi_kwlist,&f90wrap_this_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable f90wrap_n */
    /* Processing variable f90wrap_this */
    f90wrap_this_Dims[0]=4;
    capi_f90wrap_this_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_long_subroutine_name_type_2__array_len__m_long_su541d: failed to create array from the 1st argument `f90wrap_this`";
    capi_f90wrap_this_as_array = ndarray_from_pyobj(  NPY_INT,1,f90wrap_this_Dims,f90wrap_this_Rank,  capi_f90wrap_this_intent,f90wrap_this_capi,capi_errmess);

    if (capi_f90wrap_this_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      f90wrap_this = (int *)(PyArray_DATA(capi_f90wrap_this_as_array));
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(f90wrap_this,&f90wrap_n);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("i",f90wrap_n);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_f90wrap_this_as_array!=f90wrap_this_capi) {
        Py_XDECREF(capi_f90wrap_this_as_array); }
    }  /* if (capi_f90wrap_this_as_array == NULL) ... else of f90wrap_this */
    /* End of cleaning variable f90wrap_this */
    /* End of cleaning variable f90wrap_n */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*** end of f90wrap_m_long_subroutine_name_type_2__array_len__m_long_su541d ***/

/****** f90wrap_m_long_subroutine_name__m_long_subroutine_name_typebe6a ******/
static char doc_f2py_rout__pywrapper_f90wrap_m_long_subroutine_name__m_long_subroutine_name_typebe6a[] = "\
this = f90wrap_m_long_subroutine_name__m_long_subroutine_name_typebe6a()\n\nWrapper for ``f90wrap_m_long_subroutine_name__m_long_subroutine_name_typebe6a``.\
\n\nReturns\n-------\n"
"this : rank-1 array('i') with bounds (4)";
/* extern void F_FUNC_US(f90wrap_m_long_subroutine_name__m_long_subroutine_name_typebe6a,F90WRAP_M_LONG_SUBROUTINE_NAME__M_LONG_SUBROUTINE_NAME_TYPEBE6A)(int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_long_subroutine_name__m_long_subroutine_name_typebe6a(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_as_array = NULL;
    int capi_this_intent = 0;
    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:_pywrapper.f90wrap_m_long_subroutine_name__m_long_subroutine_name_typebe6a",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=4;
    capi_this_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_long_subroutine_name__m_long_subroutine_name_typebe6a: failed to create array from the hidden `this`";
    capi_this_as_array = ndarray_from_pyobj(  NPY_INT,1,this_Dims,this_Rank,  capi_this_intent,Py_None,capi_errmess);

    if (capi_this_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      this = (int *)(PyArray_DATA(capi_this_as_array));
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(this);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_this_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_this_as_array == NULL) ... else of this */
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*** end of f90wrap_m_long_subroutine_name__m_long_subroutine_name_typebe6a ***/

/****** f90wrap_m_long_subroutine_name__m_long_subroutine_name_type1fc3 ******/
static char doc_f2py_rout__pywrapper_f90wrap_m_long_subroutine_name__m_long_subroutine_name_type1fc3[] = "\
f90wrap_m_long_subroutine_name__m_long_subroutine_name_type1fc3(this)\n\nWrapper for ``f90wrap_m_long_subroutine_name__m_long_subroutine_name_type1fc3``.\
\n\nParameters\n----------\n"
"this : input rank-1 array('i') with bounds (4)";
/* extern void F_FUNC_US(f90wrap_m_long_subroutine_name__m_long_subroutine_name_type1fc3,F90WRAP_M_LONG_SUBROUTINE_NAME__M_LONG_SUBROUTINE_NAME_TYPE1FC3)(int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_long_subroutine_name__m_long_subroutine_name_type1fc3(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int *this = NULL;
    npy_intp this_Dims[1] = {-1};
    const int this_Rank = 1;
    PyArrayObject *capi_this_as_array = NULL;
    int capi_this_intent = 0;
    PyObject *this_capi = Py_None;
    static char *capi_kwlist[] = {"this",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:_pywrapper.f90wrap_m_long_subroutine_name__m_long_subroutine_name_type1fc3",\
        capi_kwlist,&this_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable this */
    this_Dims[0]=4;
    capi_this_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_long_subroutine_name__m_long_subroutine_name_type1fc3: failed to create array from the 1st argument `this`";
    capi_this_as_array = ndarray_from_pyobj(  NPY_INT,1,this_Dims,this_Rank,  capi_this_intent,this_capi,capi_errmess);

    if (capi_this_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      this = (int *)(PyArray_DATA(capi_this_as_array));
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(this);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_this_as_array!=this_capi) {
        Py_XDECREF(capi_this_as_array); }
    }  /* if (capi_this_as_array == NULL) ... else of this */
    /* End of cleaning variable this */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*** end of f90wrap_m_long_subroutine_name__m_long_subroutine_name_type1fc3 ***/

/****** f90wrap_m_long_subroutine_name__m_long_subroutine_name_subra0ea ******/
static char doc_f2py_rout__pywrapper_f90wrap_m_long_subroutine_name__m_long_subroutine_name_subra0ea[] = "\
f90wrap_m_long_subroutine_name__m_long_subroutine_name_subra0ea()\n\nWrapper for ``f90wrap_m_long_subroutine_name__m_long_subroutine_name_subra0ea``.\
\n";
/* extern void F_FUNC_US(f90wrap_m_long_subroutine_name__m_long_subroutine_name_subra0ea,F90WRAP_M_LONG_SUBROUTINE_NAME__M_LONG_SUBROUTINE_NAME_SUBRA0EA)(void); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_long_subroutine_name__m_long_subroutine_name_subra0ea(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(void)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:_pywrapper.f90wrap_m_long_subroutine_name__m_long_subroutine_name_subra0ea",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)();
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*** end of f90wrap_m_long_subroutine_name__m_long_subroutine_name_subra0ea ***/

/****** f90wrap_m_long_subroutine_name__get__m_long_subroutine_namebc01 ******/
static char doc_f2py_rout__pywrapper_f90wrap_m_long_subroutine_name__get__m_long_subroutine_namebc01[] = "\
f90wrap_m_long_subroutine_name_integer = f90wrap_m_long_subroutine_name__get__m_long_subroutine_namebc01()\n\nWrapper for ``f90wrap_m_long_subroutine_name__get__m_long_subroutine_namebc01``.\
\n\nReturns\n-------\n"
"f90wrap_m_long_subroutine_name_integer : int";
/* extern void F_FUNC_US(f90wrap_m_long_subroutine_name__get__m_long_subroutine_namebc01,F90WRAP_M_LONG_SUBROUTINE_NAME__GET__M_LONG_SUBROUTINE_NAMEBC01)(int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_long_subroutine_name__get__m_long_subroutine_namebc01(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int f90wrap_m_long_subroutine_name_integer = 0;
    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:_pywrapper.f90wrap_m_long_subroutine_name__get__m_long_subroutine_namebc01",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
    /* Processing variable f90wrap_m_long_subroutine_name_integer */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(&f90wrap_m_long_subroutine_name_integer);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("i",f90wrap_m_long_subroutine_name_integer);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable f90wrap_m_long_subroutine_name_integer */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*** end of f90wrap_m_long_subroutine_name__get__m_long_subroutine_namebc01 ***/

/****** f90wrap_m_long_subroutine_name__set__m_long_subroutine_name860c ******/
static char doc_f2py_rout__pywrapper_f90wrap_m_long_subroutine_name__set__m_long_subroutine_name860c[] = "\
f90wrap_m_long_subroutine_name__set__m_long_subroutine_name860c(f90wrap_m_long_subroutine_name_integer)\n\nWrapper for ``f90wrap_m_long_subroutine_name__set__m_long_subroutine_name860c``.\
\n\nParameters\n----------\n"
"f90wrap_m_long_subroutine_name_integer : input int";
/* extern void F_FUNC_US(f90wrap_m_long_subroutine_name__set__m_long_subroutine_name860c,F90WRAP_M_LONG_SUBROUTINE_NAME__SET__M_LONG_SUBROUTINE_NAME860C)(int*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_long_subroutine_name__set__m_long_subroutine_name860c(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int f90wrap_m_long_subroutine_name_integer = 0;
    PyObject *f90wrap_m_long_subroutine_name_integer_capi = Py_None;
    static char *capi_kwlist[] = {"f90wrap_m_long_subroutine_name_integer",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:_pywrapper.f90wrap_m_long_subroutine_name__set__m_long_subroutine_name860c",\
        capi_kwlist,&f90wrap_m_long_subroutine_name_integer_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable f90wrap_m_long_subroutine_name_integer */
        f2py_success = int_from_pyobj(&f90wrap_m_long_subroutine_name_integer,f90wrap_m_long_subroutine_name_integer_capi,"_pywrapper.f90wrap_m_long_subroutine_name__set__m_long_subroutine_name860c() 1st argument (f90wrap_m_long_subroutine_name_integer) can't be converted to int");
    if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(&f90wrap_m_long_subroutine_name_integer);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*if (f2py_success) of f90wrap_m_long_subroutine_name_integer*/
    /* End of cleaning variable f90wrap_m_long_subroutine_name_integer */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*** end of f90wrap_m_long_subroutine_name__set__m_long_subroutine_name860c ***/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"f90wrap_m_long_subroutine_name_type__get__m_long_subroutine0485",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_long_subroutine_name_type__get__m_long_subroutine0485,F90WRAP_M_LONG_SUBROUTINE_NAME_TYPE__GET__M_LONG_SUBROUTINE0485),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_long_subroutine_name_type__get__m_long_subroutine0485,doc_f2py_rout__pywrapper_f90wrap_m_long_subroutine_name_type__get__m_long_subroutine0485},
    {"f90wrap_m_long_subroutine_name_type__set__m_long_subroutine7044",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_long_subroutine_name_type__set__m_long_subroutine7044,F90WRAP_M_LONG_SUBROUTINE_NAME_TYPE__SET__M_LONG_SUBROUTINE7044),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_long_subroutine_name_type__set__m_long_subroutine7044,doc_f2py_rout__pywrapper_f90wrap_m_long_subroutine_name_type__set__m_long_subroutine7044},
    {"f90wrap_m_long_subroutine_name_type__array__m_long_subrouti6cde",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_long_subroutine_name_type__array__m_long_subrouti6cde,F90WRAP_M_LONG_SUBROUTINE_NAME_TYPE__ARRAY__M_LONG_SUBROUTI6CDE),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_long_subroutine_name_type__array__m_long_subrouti6cde,doc_f2py_rout__pywrapper_f90wrap_m_long_subroutine_name_type__array__m_long_subrouti6cde},
    {"f90wrap_m_long_subroutine_name__m_long_subroutine_name_typefcc3",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_long_subroutine_name__m_long_subroutine_name_typefcc3,F90WRAP_M_LONG_SUBROUTINE_NAME__M_LONG_SUBROUTINE_NAME_TYPEFCC3),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_long_subroutine_name__m_long_subroutine_name_typefcc3,doc_f2py_rout__pywrapper_f90wrap_m_long_subroutine_name__m_long_subroutine_name_typefcc3},
    {"f90wrap_m_long_subroutine_name__m_long_subroutine_name_type6ffd",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_long_subroutine_name__m_long_subroutine_name_type6ffd,F90WRAP_M_LONG_SUBROUTINE_NAME__M_LONG_SUBROUTINE_NAME_TYPE6FFD),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_long_subroutine_name__m_long_subroutine_name_type6ffd,doc_f2py_rout__pywrapper_f90wrap_m_long_subroutine_name__m_long_subroutine_name_type6ffd},
    {"f90wrap_m_long_subroutine_name_type_2__array_getitem__m_lonf40c",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_long_subroutine_name_type_2__array_getitem__m_lonf40c,F90WRAP_M_LONG_SUBROUTINE_NAME_TYPE_2__ARRAY_GETITEM__M_LONF40C),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_long_subroutine_name_type_2__array_getitem__m_lonf40c,doc_f2py_rout__pywrapper_f90wrap_m_long_subroutine_name_type_2__array_getitem__m_lonf40c},
    {"f90wrap_m_long_subroutine_name_type_2__array_setitem__m_lonc291",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_long_subroutine_name_type_2__array_setitem__m_lonc291,F90WRAP_M_LONG_SUBROUTINE_NAME_TYPE_2__ARRAY_SETITEM__M_LONC291),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_long_subroutine_name_type_2__array_setitem__m_lonc291,doc_f2py_rout__pywrapper_f90wrap_m_long_subroutine_name_type_2__array_setitem__m_lonc291},
    {"f90wrap_m_long_subroutine_name_type_2__array_len__m_long_su541d",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_long_subroutine_name_type_2__array_len__m_long_su541d,F90WRAP_M_LONG_SUBROUTINE_NAME_TYPE_2__ARRAY_LEN__M_LONG_SU541D),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_long_subroutine_name_type_2__array_len__m_long_su541d,doc_f2py_rout__pywrapper_f90wrap_m_long_subroutine_name_type_2__array_len__m_long_su541d},
    {"f90wrap_m_long_subroutine_name__m_long_subroutine_name_typebe6a",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_long_subroutine_name__m_long_subroutine_name_typebe6a,F90WRAP_M_LONG_SUBROUTINE_NAME__M_LONG_SUBROUTINE_NAME_TYPEBE6A),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_long_subroutine_name__m_long_subroutine_name_typebe6a,doc_f2py_rout__pywrapper_f90wrap_m_long_subroutine_name__m_long_subroutine_name_typebe6a},
    {"f90wrap_m_long_subroutine_name__m_long_subroutine_name_type1fc3",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_long_subroutine_name__m_long_subroutine_name_type1fc3,F90WRAP_M_LONG_SUBROUTINE_NAME__M_LONG_SUBROUTINE_NAME_TYPE1FC3),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_long_subroutine_name__m_long_subroutine_name_type1fc3,doc_f2py_rout__pywrapper_f90wrap_m_long_subroutine_name__m_long_subroutine_name_type1fc3},
    {"f90wrap_m_long_subroutine_name__m_long_subroutine_name_subra0ea",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_long_subroutine_name__m_long_subroutine_name_subra0ea,F90WRAP_M_LONG_SUBROUTINE_NAME__M_LONG_SUBROUTINE_NAME_SUBRA0EA),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_long_subroutine_name__m_long_subroutine_name_subra0ea,doc_f2py_rout__pywrapper_f90wrap_m_long_subroutine_name__m_long_subroutine_name_subra0ea},
    {"f90wrap_m_long_subroutine_name__get__m_long_subroutine_namebc01",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_long_subroutine_name__get__m_long_subroutine_namebc01,F90WRAP_M_LONG_SUBROUTINE_NAME__GET__M_LONG_SUBROUTINE_NAMEBC01),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_long_subroutine_name__get__m_long_subroutine_namebc01,doc_f2py_rout__pywrapper_f90wrap_m_long_subroutine_name__get__m_long_subroutine_namebc01},
    {"f90wrap_m_long_subroutine_name__set__m_long_subroutine_name860c",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_long_subroutine_name__set__m_long_subroutine_name860c,F90WRAP_M_LONG_SUBROUTINE_NAME__SET__M_LONG_SUBROUTINE_NAME860C),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_long_subroutine_name__set__m_long_subroutine_name860c,doc_f2py_rout__pywrapper_f90wrap_m_long_subroutine_name__set__m_long_subroutine_name860c},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "_pywrapper",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit__pywrapper(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = _pywrapper_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module _pywrapper (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("2.3.3");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module '_pywrapper' is auto-generated with f2py (version:2.3.3).\nFunctions:\n"
"    f90wrap_m_long_subroutine_name_type_integer = f90wrap_m_long_subroutine_name_type__get__m_long_subroutine0485(this)\n"
"    f90wrap_m_long_subroutine_name_type__set__m_long_subroutine7044(this,f90wrap_m_long_subroutine_name_type_integer)\n"
"    nd,dtype,dshape,dloc = f90wrap_m_long_subroutine_name_type__array__m_long_subrouti6cde(this)\n"
"    this = f90wrap_m_long_subroutine_name__m_long_subroutine_name_typefcc3()\n"
"    f90wrap_m_long_subroutine_name__m_long_subroutine_name_type6ffd(this)\n"
"    m_long_subroutine_name_type_2_type_arrayitem = f90wrap_m_long_subroutine_name_type_2__array_getitem__m_lonf40c(f90wrap_this,f90wrap_i)\n"
"    f90wrap_m_long_subroutine_name_type_2__array_setitem__m_lonc291(f90wrap_this,f90wrap_i,m_long_subroutine_name_type_2_type_arrayitem)\n"
"    f90wrap_n = f90wrap_m_long_subroutine_name_type_2__array_len__m_long_su541d(f90wrap_this)\n"
"    this = f90wrap_m_long_subroutine_name__m_long_subroutine_name_typebe6a()\n"
"    f90wrap_m_long_subroutine_name__m_long_subroutine_name_type1fc3(this)\n"
"    f90wrap_m_long_subroutine_name__m_long_subroutine_name_subra0ea()\n"
"    f90wrap_m_long_subroutine_name_integer = f90wrap_m_long_subroutine_name__get__m_long_subroutine_namebc01()\n"
"    f90wrap_m_long_subroutine_name__set__m_long_subroutine_name860c(f90wrap_m_long_subroutine_name_integer)\n"
".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("2.3.3");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    _pywrapper_error = PyErr_NewException ("_pywrapper.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "__pywrapper_error", _pywrapper_error);
    Py_DECREF(_pywrapper_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }













/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#if Py_GIL_DISABLED
    // signal whether this module supports running with the GIL disabled
    PyUnstable_Module_SetGIL(m , Py_MOD_GIL_USED);
#endif

#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"_pywrapper");
#endif

    if (PyType_Ready(&PyFortran_Type) < 0) {
        return NULL;
    }

    return m;
}
#ifdef __cplusplus
}
#endif
