/* File: _pywrappermodule.c
 * This file is auto-generated with f2py (version:2.3.3).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Tue Oct 21 20:19:21 2025
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
#include <math.h>


    /* custom abort handler - James Kermode <james.kermode@gmail.com> */
    #include <signal.h>
#include <setjmp.h>

    #define ABORT_BUFFER_SIZE 1024
    extern jmp_buf environment_buffer;
    extern char abort_message[ABORT_BUFFER_SIZE];
    void f90wrap_abort_(char *message, int len);
    void f90wrap_abort_int_handler(int signum);

    #include <stdlib.h>
    #include <string.h>

    jmp_buf environment_buffer;
    char abort_message[ABORT_BUFFER_SIZE];

    void f90wrap_abort_(char *message, int len_message)
    {
      strncpy(abort_message, message, ABORT_BUFFER_SIZE);
      abort_message[ABORT_BUFFER_SIZE-1] = '\0';
      longjmp(environment_buffer, 0);
    }

    // copy of f90wrap_abort_ with a second underscore
    // void (*f90wrap_abort__)(char *, int) = &f90wrap_abort_;
    void f90wrap_abort__(char *message, int len_message)
    {
      strncpy(abort_message, message, ABORT_BUFFER_SIZE);
      abort_message[ABORT_BUFFER_SIZE-1] = '\0';
      longjmp(environment_buffer, 0);
    }


    void f90wrap_abort_int_handler(int signum)
    {
      char message[] = "Interrupt occured";
      f90wrap_abort_(message, strlen(message));
    }

    /* end of custom abort handler  */
    
/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *_pywrapper_error;
static PyObject *_pywrapper_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/* See fortranobject.h for definitions. The macros here are provided for BC. */
#define rank f2py_rank
#define shape f2py_shape
#define fshape f2py_shape
#define len f2py_len
#define flen f2py_flen
#define slen f2py_slen
#define size f2py_size


#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(_pywrapper_error,errstring);\
        /*goto capi_fail;*/\
    } else 

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif


#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/

static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = _pywrapper_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(f90wrap_m_intent_out__interpolation,F90WRAP_M_INTENT_OUT__INTERPOLATION)(int*,int*,int*,int*,int*,int*,int*,int*,float*,float*,float*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/******************** f90wrap_m_intent_out__interpolation ********************/
static char doc_f2py_rout__pywrapper_f90wrap_m_intent_out__interpolation[] = "\
f90wrap_m_intent_out__interpolation(n1,n2,a1,a2,output)\n\nWrapper for ``f90wrap_m_intent_out__interpolation``.\
\n\nParameters\n----------\n"
"n1 : input int\n"
"n2 : input int\n"
"a1 : input rank-2 array('f') with bounds (f90wrap_n0,f90wrap_n1)\n"
"a2 : input rank-2 array('f') with bounds (f90wrap_n2,f90wrap_n3)\n"
"output : in/output rank-2 array('f') with bounds (f90wrap_n4,f90wrap_n5)";
/* extern void F_FUNC_US(f90wrap_m_intent_out__interpolation,F90WRAP_M_INTENT_OUT__INTERPOLATION)(int*,int*,int*,int*,int*,int*,int*,int*,float*,float*,float*); */
static PyObject *f2py_rout__pywrapper_f90wrap_m_intent_out__interpolation(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,int*,int*,int*,int*,float*,float*,float*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
        int setjmpvalue; /* James Kermode - for setjmp */
    /*decl*/

    int f90wrap_n0 = 0;
    int f90wrap_n1 = 0;
    int f90wrap_n2 = 0;
    int f90wrap_n3 = 0;
    int f90wrap_n4 = 0;
    int f90wrap_n5 = 0;
    int n1 = 0;
    PyObject *n1_capi = Py_None;
    int n2 = 0;
    PyObject *n2_capi = Py_None;
    float *a1 = NULL;
    npy_intp a1_Dims[2] = {-1, -1};
    const int a1_Rank = 2;
    PyArrayObject *capi_a1_as_array = NULL;
    int capi_a1_intent = 0;
    PyObject *a1_capi = Py_None;
    float *a2 = NULL;
    npy_intp a2_Dims[2] = {-1, -1};
    const int a2_Rank = 2;
    PyArrayObject *capi_a2_as_array = NULL;
    int capi_a2_intent = 0;
    PyObject *a2_capi = Py_None;
    float *output = NULL;
    npy_intp output_Dims[2] = {-1, -1};
    const int output_Rank = 2;
    PyArrayObject *capi_output_as_array = NULL;
    int capi_output_intent = 0;
    PyObject *output_capi = Py_None;
    static char *capi_kwlist[] = {"n1","n2","a1","a2","output",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOO|:_pywrapper.f90wrap_m_intent_out__interpolation",\
        capi_kwlist,&n1_capi,&n2_capi,&a1_capi,&a2_capi,&output_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable n1 */
        f2py_success = int_from_pyobj(&n1,n1_capi,"_pywrapper.f90wrap_m_intent_out__interpolation() 1st argument (n1) can't be converted to int");
    if (f2py_success) {
    /* Processing variable n2 */
        f2py_success = int_from_pyobj(&n2,n2_capi,"_pywrapper.f90wrap_m_intent_out__interpolation() 2nd argument (n2) can't be converted to int");
    if (f2py_success) {
    /* Processing variable a1 */
    ;
    capi_a1_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_intent_out__interpolation: failed to create array from the 3rd argument `a1`";
    capi_a1_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,a1_Dims,a1_Rank,  capi_a1_intent,a1_capi,capi_errmess);

    if (capi_a1_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      a1 = (float *)(PyArray_DATA(capi_a1_as_array));
    /* Processing variable a2 */
    ;
    capi_a2_intent |= F2PY_INTENT_IN;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_intent_out__interpolation: failed to create array from the 4th argument `a2`";
    capi_a2_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,a2_Dims,a2_Rank,  capi_a2_intent,a2_capi,capi_errmess);

    if (capi_a2_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      a2 = (float *)(PyArray_DATA(capi_a2_as_array));
    /* Processing variable output */
    ;
    capi_output_intent |= F2PY_INTENT_INOUT;
    const char capi_errmess[] = "_pywrapper._pywrapper.f90wrap_m_intent_out__interpolation: failed to create array from the 5th argument `output`";
    capi_output_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,output_Dims,output_Rank,  capi_output_intent,output_capi,capi_errmess);

    if (capi_output_as_array == NULL) {
      PyObject* capi_err = PyErr_Occurred();
      if (capi_err == NULL) {
        capi_err = _pywrapper_error;
        PyErr_SetString(capi_err, capi_errmess);
      }
    } else {
      output = (float *)(PyArray_DATA(capi_output_as_array));
    /* Processing variable f90wrap_n0 */
    f90wrap_n0 = shape(a1, 0);
    CHECKSCALAR(shape(a1, 0) == f90wrap_n0,"shape(a1, 0) == f90wrap_n0","hidden f90wrap_n0","f90wrap_m_intent_out__interpolation:f90wrap_n0=%d",f90wrap_n0) {
    /* Processing variable f90wrap_n1 */
    f90wrap_n1 = shape(a1, 1);
    CHECKSCALAR(shape(a1, 1) == f90wrap_n1,"shape(a1, 1) == f90wrap_n1","hidden f90wrap_n1","f90wrap_m_intent_out__interpolation:f90wrap_n1=%d",f90wrap_n1) {
    /* Processing variable f90wrap_n2 */
    f90wrap_n2 = shape(a2, 0);
    CHECKSCALAR(shape(a2, 0) == f90wrap_n2,"shape(a2, 0) == f90wrap_n2","hidden f90wrap_n2","f90wrap_m_intent_out__interpolation:f90wrap_n2=%d",f90wrap_n2) {
    /* Processing variable f90wrap_n3 */
    f90wrap_n3 = shape(a2, 1);
    CHECKSCALAR(shape(a2, 1) == f90wrap_n3,"shape(a2, 1) == f90wrap_n3","hidden f90wrap_n3","f90wrap_m_intent_out__interpolation:f90wrap_n3=%d",f90wrap_n3) {
    /* Processing variable f90wrap_n4 */
    f90wrap_n4 = shape(output, 0);
    CHECKSCALAR(shape(output, 0) == f90wrap_n4,"shape(output, 0) == f90wrap_n4","hidden f90wrap_n4","f90wrap_m_intent_out__interpolation:f90wrap_n4=%d",f90wrap_n4) {
    /* Processing variable f90wrap_n5 */
    f90wrap_n5 = shape(output, 1);
    CHECKSCALAR(shape(output, 1) == f90wrap_n5,"shape(output, 1) == f90wrap_n5","hidden f90wrap_n5","f90wrap_m_intent_out__interpolation:f90wrap_n5=%d",f90wrap_n5) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/* setjmp() exception handling added by James Kermode */
    PyOS_sighandler_t _npy_sig_save;
    _npy_sig_save = PyOS_setsig(SIGINT, f90wrap_abort_int_handler);
    setjmpvalue = setjmp(environment_buffer);
    if (setjmpvalue != 0) {
      PyOS_setsig(SIGINT, _npy_sig_save);
      PyObject *err_msg = PyUnicode_DecodeUTF8(abort_message, strlen(abort_message), "replace");
      if (err_msg != NULL) {
        PyErr_SetObject(PyExc_RuntimeError, err_msg);
        Py_DECREF(err_msg);
      } else {
        PyErr_SetString(PyExc_RuntimeError, "Error decoding abort message");
      }
    } else {
     /*callfortranroutine*/
                (*f2py_func)(&f90wrap_n0,&f90wrap_n1,&f90wrap_n2,&f90wrap_n3,&f90wrap_n4,&f90wrap_n5,&n1,&n2,a1,a2,output);
     PyOS_setsig(SIGINT, _npy_sig_save);
    }
    /* End addition */
    if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*CHECKSCALAR(shape(output, 1) == f90wrap_n5)*/
    /* End of cleaning variable f90wrap_n5 */
    } /*CHECKSCALAR(shape(output, 0) == f90wrap_n4)*/
    /* End of cleaning variable f90wrap_n4 */
    } /*CHECKSCALAR(shape(a2, 1) == f90wrap_n3)*/
    /* End of cleaning variable f90wrap_n3 */
    } /*CHECKSCALAR(shape(a2, 0) == f90wrap_n2)*/
    /* End of cleaning variable f90wrap_n2 */
    } /*CHECKSCALAR(shape(a1, 1) == f90wrap_n1)*/
    /* End of cleaning variable f90wrap_n1 */
    } /*CHECKSCALAR(shape(a1, 0) == f90wrap_n0)*/
    /* End of cleaning variable f90wrap_n0 */
    if((PyObject *)capi_output_as_array!=output_capi) {
        Py_XDECREF(capi_output_as_array); }
    }  /* if (capi_output_as_array == NULL) ... else of output */
    /* End of cleaning variable output */
    if((PyObject *)capi_a2_as_array!=a2_capi) {
        Py_XDECREF(capi_a2_as_array); }
    }  /* if (capi_a2_as_array == NULL) ... else of a2 */
    /* End of cleaning variable a2 */
    if((PyObject *)capi_a1_as_array!=a1_capi) {
        Py_XDECREF(capi_a1_as_array); }
    }  /* if (capi_a1_as_array == NULL) ... else of a1 */
    /* End of cleaning variable a1 */
    } /*if (f2py_success) of n2*/
    /* End of cleaning variable n2 */
    } /*if (f2py_success) of n1*/
    /* End of cleaning variable n1 */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************** end of f90wrap_m_intent_out__interpolation *****************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"f90wrap_m_intent_out__interpolation",-1,{{-1}},0,0,(char *)  F_FUNC_US(f90wrap_m_intent_out__interpolation,F90WRAP_M_INTENT_OUT__INTERPOLATION),  (f2py_init_func)f2py_rout__pywrapper_f90wrap_m_intent_out__interpolation,doc_f2py_rout__pywrapper_f90wrap_m_intent_out__interpolation},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "_pywrapper",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit__pywrapper(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = _pywrapper_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module _pywrapper (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("2.3.3");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module '_pywrapper' is auto-generated with f2py (version:2.3.3).\nFunctions:\n"
"    f90wrap_m_intent_out__interpolation(n1,n2,a1,a2,output)\n"
".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("2.3.3");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    _pywrapper_error = PyErr_NewException ("_pywrapper.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "__pywrapper_error", _pywrapper_error);
    Py_DECREF(_pywrapper_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }

/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#if Py_GIL_DISABLED
    // signal whether this module supports running with the GIL disabled
    PyUnstable_Module_SetGIL(m , Py_MOD_GIL_USED);
#endif

#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"_pywrapper");
#endif

    if (PyType_Ready(&PyFortran_Type) < 0) {
        return NULL;
    }

    return m;
}
#ifdef __cplusplus
}
#endif
